README.md
Make the contribution guide easier to find.
=> Point from README.md to CONTRIBUTING.md

CONTRIBUTING.md
Minor fix to avoid head scratching.
=> Fix grammar in using SSH keys option.

NOTICE.txt, docs/intro.txt
=> Update groovy lang links

README.md
=> Added links to mailing lists and Gitter.

janusgraph-core/pom.xml, pom.xml
to address high severity security vulnerability for remote code execution during object de-serialization.
https://commons.apache.org/proper/commons-collections/security-reports.html
=> Update to Apache Commons Collections 3.2.2 

.travis.yml, README.md
Click on the "View" button in the diffs to see the rendered view on my branch.
=> Added a Travis CI badge.

README.md
We are getting more and more emails with the text "subscribe" so let's clarify
the process for subscribing to the mailing lists as it appears it's non-obvious.
In the [most recent thread](https://groups.google.com/d/msg/janusgraph-users/bSTbt1ZSvHQ/U7zdjzfYAwAJ), I promised to update the `README.md` file to clarify this, hence the PR.
=> Clarify how to subscribe to mailing lists

README.md
This may draw readers' attention to the badge upon finding the homepage and may
bring more visitors to the discussion channel.
=> Add badge for Gitter

NOTICE.txt, docs/bdb.txt, docs/upgrade.txt, janusgraph-berkeleyje/pom.xml
More details in https://github.com/JanusGraph/janusgraph/issues/100
=> Upgrade to BerkeleyDB JE 7.3.7

janusgraph-all/pom.xml, janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-10/src/main/java/org/janusgraph/diskstorage/hbase/HBaseAdmin1_0.java, janusgraph-hbase-parent/janusgraph-hbase-10/src/main/java/org/janusgraph/diskstorage/hbase/HConnection1_0.java, janusgraph-hbase-parent/janusgraph-hbase-10/src/main/java/org/janusgraph/diskstorage/hbase/HTable1_0.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseCompatLoader.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/HBaseStorageSetup.java, pom.xml
=> Support HBase 1.2

docs/hbase.txt
=> Correct name of storage.hbase.ext

docs/datamodel.txt
Essentially: `s/BigTable/Bigtable/`
=> Fix capitalization of Bigtable in the docs

docs/intro.txt, janusgraph-hbase-parent/janusgraph-hbase-098/pom.xml
=> Issue 162: Clean up Hadoop1 from doc and other places

janusgraph-core/src/main/java/org/janusgraph/diskstorage/MetaAnnotated.java
Signed-off-by: Davide Bolcioni <dbolcion@uber.com>
=> Fixed @return comments to remove javadoc warnings

janusgraph-core/src/main/java/org/janusgraph/core/BaseVertexQuery.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/RelationTypeIndex.java, janusgraph-core/src/main/java/org/janusgraph/core/util/JanusGraphId.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsGraph.java
1. change com.tinkerpop to org.apache.tinkerpop
2. remove some comment code
=> java doc fix

janusgraph-all/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-cassandra/pom.xml, janusgraph-core/pom.xml, janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-es/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-2/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop/pom.xml, janusgraph-hadoop-parent/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-098/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml, janusgraph-hbase-parent/janusgraph-hbase/pom.xml, janusgraph-hbase-parent/pom.xml, janusgraph-lucene/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, pom.xml
=> Issue 180: Update project version to 0.2.0-SNAPSHOT

docs/bulkloading.txt
Signed-off-by: Ted Chang <htchang@us.ibm.com>
=> Fixed ETL wiki page url

janusgraph-core/src/main/java/org/janusgraph/example/GraphOfTheGodsFactory.java
This PR is a cherry-pick of PR #194 from `master` to the `0.1` branch.
Thanks to @sdmonov for catching this and sending the original PR.
=> Change "Saturn"'s Vertex label back to "titan" (0.1 branch)

BUILDING.md, CHANGELOG.asc, NOTICE.txt, RELEASING.md, UPGRADE.asc, docs/changelog.txt, janusgraph-dist/src/release/index.html
Updates to partially resolve #184. Required updates not included in this PR are listed below.
* Compatibility matrix, versions.txt (#176 will resolve this)
* Include the actual 0.1.0 release date in CHANGELOG.asc and docs/changelog.txt
=> Issue 184: Documentation updates for 0.1.0 release

docs/intro.txt
Doesn't make much sense now IMHO.
=> Get rid of the Titan-oriented introduction ('JanusGraph of time')

CHANGELOG.asc, docs/changelog.txt
=> CTR Documentation update to fix headers in changelog

.travis.yml, AUTHORS.txt, BUILDING.md, CHANGELOG.asc, NOTICE.txt, README.md, RELEASING.md, UPGRADE.asc, docs/changelog.txt, docs/solr.txt, docs/versions.txt, janusgraph-dist/src/release/index.html, janusgraph-solr/pom.xml
Resolves merge conflicts in all POMs from project version updates.
=> Merge 0.1 into master

docs/basics.txt, docs/textsearch.txt
=> Fix asciidoc warnings in basics.txt and textsearch.txt

janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
=> Do not subclass HashMap when instantiating preregisteredAutoType

janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/StaticBuffer.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/StoreFeatures.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseBinaryInputFormat.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphBaseTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java
=> #228 [WIP] Make ID store name configurable

janusgraph-test/src/main/java/org/janusgraph/blueprints/AbstractJanusGraphProvider.java
=> Do not subclass HashSet when creating IMPLEMENTATION

janusgraph-test/src/main/java/org/janusgraph/diskstorage/log/LogTest.java
When testing DynamoDB LogTest in the multiple item data model for the following methods:
I found that these tests failed because the timeout was too small. I would like to externalize timeoutMS in methods sendReceive and sendReceiveSimple so that I can adjust the timeout so that the tests pass in my dev environment.
Related [issue](https://github.com/awslabs/dynamodb-titan-storage-backend/issues/110) on the DynamoDB backend. [Current build](https://travis-ci.org/awslabs/dynamodb-titan-storage-backend) reproduced the timeout failure in the [MultiIdAuthorityLogLockStore](https://travis-ci.org/awslabs/dynamodb-titan-storage-backend/jobs/227387308) module.
=> Externalize TIMEOUT_MS so that backends can change the timeout

janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/HBaseStorageSetup.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerConfigTest.java
Check and warn if short-cf-names is interleaved or mixed with the same HBase table.
=> Issue 220: storage.hbase.short-cf-names is not fixed

docs/basics.txt, docs/elasticsearch.txt, janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml, janusgraph-dist/src/assembly/descriptor/common.component.xml
=> Move compat-test-files under optional profile and update documentation

docs/basics.txt
=> [Doc] Move 'Extending JanusGraph Server' to the correct section

janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/core/RelationType.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/AttributeSerializer.java
=> Issue 263 Correct links in the source code from thinkaurelius to JanusGraph

CHANGELOG.asc, UPGRADE.asc, docs/changelog.txt, docs/upgrade.txt, docs/versions.txt, janusgraph-all/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-cassandra/pom.xml, janusgraph-core/pom.xml, janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-es/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-2/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop/pom.xml, janusgraph-hadoop-parent/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-098/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml, janusgraph-hbase-parent/janusgraph-hbase/pom.xml, janusgraph-hbase-parent/pom.xml, janusgraph-lucene/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, pom.xml
Updated docs and output of `mvn release:prepare`.
=> 0.1.1 release

docs/advschema.txt, docs/basics.txt, docs/recovery.txt, docs/reindex.txt
=> Issue 272 typos

README.md
Confirmation and permission to list FiNC courtesy of @marcelocf. Also added to the website in https://github.com/JanusGraph/janusgraph.org/pull/10
=> Add FiNC as a production user of JanusGraph.

janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
Refactor out asserts into a separate method and support retrying on failure in JanusGraphIndexTest#testIndexing. This fixes sporadic failures where commits may not be fully visible immediately after commit to indexing backends (e.g. janusgraph-es) in some testing environments (e.g. Travis).
Relevant issue is #74.
=> Retry queries after commit in index testing

README.md
* Renamed "Contact" to "Community", reorganized order of sections, and added Stack Overflow
* Added Maven and Stack Overflow badges to the top of the page; changed Markdown formatting
Note: I added `[skip ci]` to each of the commits so Travis shouldn't run build/test for this PR.
=> Update README badges and community pointers

.gitignore
[skip ci] as this is not a code change and doesn't affect any tests
=> Ignore Vim file backups.

README.md
See also https://github.com/JanusGraph/janusgraph.org/pull/18 for the website update.
=> Add CELUM as a production user [skip ci]

BUILDING.md
=> Remove legacy TinkerPop 3.2.3 testing note

janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml
=> Expose gremlin server port by listening on 0.0.0.0 #141

janusgraph-dist/src/assembly/static/bin/cassandra.in.sh
=> Remove hardcoded slf4j version from cassandra.in.sh

docs/intro.txt
=> Fixed table in master issue #296 [skip ci]

docs/intro.txt
=> Fixes table in 0.1 - Issue #296 [skip ci]

docs/intro.txt
Signed-off-by: Joel Sánchez <webmaster@kazer.es>
=> Backport PR # 156 'Get rid of the Titan-oriented introduction' to branch 0.1 [skip ci]

docs/versions.txt
=> Add Spark/Scala version to version-compat list for branch 0.1 [skip ci] 

docs/versions.txt
=> Add Spark/Scala version to version-compat list  [skip ci] 

janusgraph-core/src/main/java/org/janusgraph/core/Transaction.java
Fixed indexName param description - issue #313
=> Fixed indexName param description in 0.1 - issue #313 [skip ci]

janusgraph-core/src/main/java/org/janusgraph/core/Transaction.java
Fixed indexName param description - issue #313
=> Fixed indexName param description in master - issue #313 [skip ci]

AUTHORS.txt, CONTRIBUTORS.txt, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Geo.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Text.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistry.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-test/pom.xml, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryTest.java
=> Issue #239 Serialize geo and text search predicates in gryo (0.1)

AUTHORS.txt, CONTRIBUTORS.txt, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Geo.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Text.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistry.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-test/pom.xml, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryTest.java
=> Issue #239 Serialize geo and text search predicates in gryo (master)

TESTING.md, docs/versions.txt, janusgraph-core/pom.xml, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Geoshape.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/GeoshapeHelper.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/JtsGeoshapeHelper.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/pom.xml, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneExample.java, janusgraph-solr/pom.xml, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/BerkeleySolrTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrRunner.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/ThriftSolrTest.java, janusgraph-solr/src/test/resources/collections.txt, janusgraph-solr/src/test/resources/docker-compose.yml, janusgraph-solr/src/test/resources/import-collections.sh, janusgraph-solr/src/test/resources/solr/core-template/schema.xml, janusgraph-test/src/test/java/org/janusgraph/graphdb/attribute/GeoshapeTest.java, pom.xml
=> Update Lucene and Solr versions to 6.6.0

janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
Signed-off-by: Rafael Fernandes <luizrafael@gmail.com>
=> Enable property prefetching by default

janusgraph-cassandra/pom.xml, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraGraphComputer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexMemoryHandler.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-solr/pom.xml, janusgraph-test/src/test/java/org/janusgraph/blueprints/process/traversal/strategy/optimization/JanusGraphStepStrategyTest.java, pom.xml
Fixes #350. All tests are passing (ran in two batches).
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JanusGraph-Test: Test Suite for JanusGraph ........ SUCCESS [41:17.523s]
[INFO] JanusGraph-BerkeleyJE: Distributed Graph Database . SUCCESS [2:18:10.966s]
[INFO] JanusGraph-Cassandra: Distributed Graph Database .. SUCCESS [4:18:21.171s]
[INFO] JanusGraph-CQL: Distributed Graph Database ........ SUCCESS [15:03:15.787s]
[INFO] JanusGraph-ElasticSearch: Distributed Indexing Support  SUCCESS [11:02.612s]
[INFO] JanusGraph-Lucene: Indexing Support ............... SUCCESS [1:56.719s]
[INFO] JanusGraph-Solr: Distributed Indexing Support ..... SUCCESS [8:46.541s]
[INFO] …
```
=> Update to TinkerPop 3.2.5

janusgraph-dist/src/assembly/static/conf/remote-graph.properties
=> Added property file for use with withRemote() [skip ci]

janusgraph-dist/src/assembly/static/conf/remote-graph.properties
Added property file for use with withRemote()
=> withRemote() config [skip ci]

README.md
Permission to use the name courtesy of @FlorianHockmann — thank you!
Corresponding change to add logo to the website is in https://github.com/JanusGraph/janusgraph.org/pull/21
=> Add G DATA as a production user [skip ci]

janusgraph-dist/pom.xml, janusgraph-dist/src/assembly/static/conf/es/elasticsearch.yml, janusgraph-es/pom.xml, janusgraph-es/src/main/resources/janusgraph-es.properties, janusgraph-es/src/test/config/elasticsearch.yml, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchRunner.java, janusgraph-es/src/test/resources/janusgraph-es.properties, pom.xml
Also clean up associated configuration properties.
=> Update Elasticsearch client version to 5.4.2

docs/directindex.txt, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphIndexQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/BackendTransaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexProvider.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexTransaction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/IndexQueryBuilder.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/TestMockIndexProvider.java
Signed-off-by: Adam Holley <holleya@us.ibm.com>
=> Issue #318 - New apis for index query totals.  testRawQueries() unit test updated.

janusgraph-all/src/main/resources/META-INF/services/org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.KryoShimService, janusgraph-dist/src/assembly/static/bin/gremlin-server.bat, janusgraph-dist/src/assembly/static/bin/gremlin-server.sh, janusgraph-dist/src/assembly/static/bin/gremlin.bat, janusgraph-dist/src/assembly/static/bin/gremlin.sh, janusgraph-dist/src/pkg/static/pkgcommon/payload/usr/bin/gremlin.sh, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/serialize/JanusGraphKryoShimService.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/META-INF/services/org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.KryoShimService
=> Replace Spark KryoRegistrator with TP KryoShimService

docs/advschema.txt, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerMutationTest.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/graphdb/hbase/HBaseGraphTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/KeyColumnValueStoreTest.java, pom.xml
=> Support HBase cell level TTL

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
Fixes #396. Thanks @srosenthal.
=> Add Content-Type header to ES requests

janusgraph-dist/src/assembly/static/conf/solr/schema.xml, janusgraph-solr/src/test/resources/solr/core-template/schema.xml
=> Use non-JTS SpatialContextFactory in Solr config

TESTING.md, janusgraph-es/pom.xml, janusgraph-es/src/test/config/elasticsearch.docker.yml, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchConfigTest.java
=> Support Elasticsearch testing against a managed Docker container

docs/intro.txt, docs/searchpredicates.txt
Syncing docs to match current state.
=> docs: Add solr, remove data types [skip ci]

buildspec.yml, janusgraph-codepipelines-ci/README.md, janusgraph-codepipelines-ci/pipe.yml, janusgraph-codepipelines-ci/pom.xml, janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/AwsCodePipelinesCi.java, janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/AwsCodePipelinesLogic.java, janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/model/EnvironmentMapping.java, janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/model/ParallelBuildAction.java, janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/model/PipelineDefinition.java, janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/model/PipelineDefinitions.java, janusgraph-codepipelines-ci/tp-pipe.yml
=> [skip ci] Set privileged mode on per build action basis.

docs/appendices.txt
Fixes #213. Thanks @mbrukman for providing the correct link.
=> Add link to API documentation [skip ci]

docs/appendices.txt
Follow-up on #414 (issue #213) based on [suggestion](https://github.com/JanusGraph/janusgraph/pull/414#discussion_r127619209) by @mbrukman.
=> Add project verison to API documentation link [skip ci]

janusgraph-hbase-parent/janusgraph-hbase-098/src/main/java/org/janusgraph/diskstorage/hbase/HBaseAdmin0_98.java, janusgraph-hbase-parent/janusgraph-hbase-10/src/main/java/org/janusgraph/diskstorage/hbase/HBaseAdmin1_0.java
The existing `HBaseAdmin1_0.clearTable()` implementation disables, truncates and then re-enables the table, which performs poorly for integration tests. This update scans and deletes all rows instead of truncating, following the existing [`HBaseAdmin0_98.clearStorage()`](https://github.com/JanusGraph/janusgraph/blob/84ead7d907b62061e30c5d3210e5e8422fd4648c/janusgraph-hbase-parent/janusgraph-hbase-098/src/main/java/org/janusgraph/diskstorage/hbase/HBaseAdmin0_98.java#L65-L95) implementation.
With these updates the full (default+TinkerPop) test suite runtime for the janusgraph-hbase-10 module is decreased from 8.9 hours to 2.7 hours.
This supports #111.
=> Scan and delete rather than truncate in HBase 1.0 clearTable

janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/com/google/common/base/Stopwatch.java
=> Remove JanusGraph copyright header from custom Guava Stopwatch [skip ci]

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/AbstractESCompat.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
Signed-off-by: Adam Holley <holleya@us.ibm.com>
=> Actually process raw query parameters.  Issue 338

janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/JanusGraphConstants.java, janusgraph-core/src/main/java/org/janusgraph/util/system/ConfigurationLint.java
Signed-off-by: Satish Kolli <satish.kolli@gmail.com>
=> Fix for the streams closing issue reported by Fortify

docs/hadoop.txt, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-hbase.properties, janusgraph-dist/src/assembly/static/conf/hadoop-graph/read-hbase.properties
=> Clean up Hadoop documentation and add HBase conf file [skip ci]

docs/searchpredicates.txt, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Geoshape.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/GeoshapeHelper.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/JtsGeoshapeHelper.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-test/src/test/java/org/janusgraph/core/attribute/GeoshapeHelperTest.java, janusgraph-test/src/test/java/org/janusgraph/core/attribute/JtsGeoshapeHelperTest.java
Add test for Collection of Lines, Point and Polygon and support for GeometryCollectionin ES and Solr.
Issue : https://github.com/JanusGraph/janusgraph/issues/387
=> Support all geometries features in ES and Solr.

janusgraph-cql/pom.xml, pom.xml
Updates to more current versions for high vulnerability items in issue #424 
=> Updated versions for Cassandra, Jackson, Netty, Thrift

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
=> ES: Ensure unique script var names

janusgraph-dist/src/assembly/static/conf/solr/schema.xml, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java, janusgraph-solr/src/test/resources/collections.txt, janusgraph-solr/src/test/resources/solr/core-template/schema.xml, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
Signed-off-by: Adam Holley <holleya@us.ibm.com>
=> Issue 327 - Support for List/Set Cardinality in Solr.

janusgraph-dist/pom.xml
Added `data`, `elasticsearch`, `scripts`
Removed unused `rexhome`
=> Clean more dist build dirs 

janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
Signed-off-by: Adam Holley <holleya@us.ibm.com>
=> Issue 329 - Added commits for Solr

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
Issues: https://github.com/JanusGraph/janusgraph/issues/442
=> Fix vertex-centric-index multiplicity constraints

janusgraph-cassandra/pom.xml, pom.xml
=> Bump jline to use same as TinkerPop version

.travis.yml, codecov.yml, janusgraph-cql/pom.xml, janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop/pom.xml, janusgraph-hadoop-parent/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-098/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml, janusgraph-hbase-parent/janusgraph-hbase/pom.xml, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryTest.java, pom.xml
Fixes #21. See https://codecov.io/gh/janusgraph/janusgraph/branch/master.
=> Generate JaCoCo test coverage reports and upload to Codecov from Travis CI

janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/AwsCodePipelinesLogic.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/ConcurrentLRUCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/PriorityQueue.java, janusgraph-core/src/main/java/org/janusgraph/util/encoding/NumericUtils.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/serialize/JanusGraphKryoShimService.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/com/google/common/io/Closeables.java
=> Add missing license headers and use original license headers in derivative classes

janusgraph-cassandra/pom.xml, janusgraph-codepipelines-ci/pom.xml, janusgraph-cql/pom.xml, janusgraph-es/pom.xml, janusgraph-hadoop-parent/pom.xml, janusgraph-hbase-parent/pom.xml, janusgraph-solr/pom.xml, pom.xml
Fixes #517 
Fixes #468 
Fixes #310
=> POM updates to fix issues with netty, log4j and solr-core dependencies

janusgraph-dist/src/assembly/static/bin/janusgraph.sh
Fixes issue #539
- Check if services are running before start, if true, exit
- Added more log files to clean up
=> Improve janusgraph.sh

docs/elasticsearch.txt, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchSetup.java
Issue : https://github.com/JanusGraph/janusgraph/issues/545
=> Remove ES_EXTRAS_NS from Elasticsearch configuration.

janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/AbstractCassandraStoreManager.java, janusgraph-cassandra/src/test/java/org/janusgraph/diskstorage/cassandra/thrift/CassandraThriftStoreManagerTest.java
=> Added frame-size-mb verification function

janusgraph-cassandra/src/test/java/org/janusgraph/diskstorage/cassandra/thrift/CassandraThriftStoreManagerTest.java
=> Completes test for PR #552

BUILDING.md
Removed remaining artifact from #187.
=> Fix typo in BUILDING.md [skip ci]

docs/elasticsearch.txt, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticMajorVersion.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchIndexTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchMultiTypeIndexTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchRunner.java
Issue : https://github.com/JanusGraph/janusgraph/issues/547
=> Add ingest pipeline support for Elasticsearch.

janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java
=> Revert to clearing instead of dropping Solr collection

janusgraph-es/pom.xml, pom.xml
=> Update Elasticsearch client to 5.6.2 and ES 6.x test version to 6.0.0-rc1

docs/basics.txt, docs/bdb.txt, docs/cassandra.txt, docs/hbase.txt, docs/indexbackends.txt, docs/inmemorybackend.txt, docs/intro.txt, docs/textsearch.txt
Fixes #575
Fixes #576
Preview docs available at https://pluradj.github.io/janusgraph.org/latest/
=> Improve naming consistency and additional Gremlin docs [skip ci]

docs/basics.txt
...because there is no RESTful interface.
Fixes issue #579
=> Renaming REST files to HTTP [skip ci]

docs/lucene.txt, docs/solr.txt
Fixes #315
Doc preview is online at https://pluradj.github.io/janusgraph.org/latest/solr.html
=> Improve Apache Solr documentation [skip ci]

janusgraph-examples/README.md, janusgraph-examples/example-berkeleyje/README.md, janusgraph-examples/example-berkeleyje/pom.xml, janusgraph-examples/example-cassandra/README.md, janusgraph-examples/example-cassandra/pom.xml, janusgraph-examples/example-common/README.md, janusgraph-examples/example-common/pom.xml, janusgraph-examples/example-common/src/main/java/org/janusgraph/example/GraphApp.java, janusgraph-examples/example-cql/README.md, janusgraph-examples/example-cql/pom.xml, janusgraph-examples/example-hbase/README.md, janusgraph-examples/example-hbase/pom.xml, janusgraph-examples/example-remotegraph/README.md, janusgraph-examples/example-remotegraph/conf/jgex-remote.properties, janusgraph-examples/example-remotegraph/pom.xml, janusgraph-examples/example-tinkergraph/README.md, janusgraph-examples/example-tinkergraph/pom.xml, janusgraph-examples/pom.xml
Fixes #530 -- addresses comments from @sjudeng on #531
Preview readme files at https://github.com/pluradj/janusgraph/tree/examples-review/janusgraph-examples
=> Additional doc cleanup for examples

janusgraph-all/pom.xml, janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml, janusgraph-examples/example-hbase/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml
Fix #512 
Signed-off-by: Jerry He <jinghe@us.ibm.com>
=> Issue 512 Use hbase shaded client and server

docs/versions.txt
=> Add warning against using older versions of dependencies [skip ci]

NOTICE.txt, docs/bigtable.txt, janusgraph-all/pom.xml, janusgraph-bigtable/pom.xml, pom.xml
This PR resolves issue #587.
/cc: @lindsayismith, @igorbernstein2, @sduskis
=> Add Google Cloud Bigtable module.

docs/upgrade.txt, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
Fixes #589
Preview docs at https://pluradj.github.io/janusgraph.org/latest/upgrade.html and https://pluradj.github.io/janusgraph.org/latest/config-ref.html#_index_x_elasticsearch
=> Upgrade instructions for Elasticsearch

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchConfigTest.java
Fixes #591
- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?
- [] Have you ensured that format looks appropriate for the …
=> Handle migration scenario where ES multitype is not set

janusgraph-examples/example-hbase/README.md
Fixes #512
- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?
Please ensure that once the PR is submitted, you check Travis CI …
=> Update HBase example doc for hbase-shaded-client [skip ci]

CHANGELOG.asc, UPGRADE.asc
=> Sync UPGRADE.asc and CHANGELOG.asc with docs [skip ci]

docs/cassandra.txt, docs/elasticsearch.txt, docs/monitoring.txt, docs/textsearch.txt, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
Fixes #626
Addresses docs issues in the 0.2.0 release found by @robertdale
=> Fixes #626: docs issues in 0.2.0 [skip ci]

janusgraph-codepipelines-ci/pom.xml
=> GPG sign janusgraph-codepipelines-ci after shading

pom.xml
Fixes #649
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [-] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?
- [-] Have you ensured that format looks appropriate for the …
=> Set SCM tag to HEAD

janusgraph-berkeleyje/pom.xml
Fixes issue #652 
```
mvn clean install -pl :janusgraph-berkeleyje 
```
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:25 min
[INFO] Finished at: 2017-10-30T15:46:03-04:00
[INFO] Final Memory: 43M/601M
[INFO] ------------------------------------------------------------------------
```
=> Bump berkeleyje to 7.4.5

janusgraph-dist/pom.xml
=> Issue 674 hadoop jars are missing in janusgraph 0.2.0 distribution

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
Issue : #661
Same PR that https://github.com/JanusGraph/janusgraph/pull/678 but on 0.2 branch
=> [Backport 0.2] Fix 661 issue on TextString on Elasticsearch on equals search 

CONTRIBUTING.md, UPGRADE.asc, docs/advblueprints.txt, docs/basics.txt, docs/bulkloading.txt, docs/configuredgraphfactory.txt, docs/directindex.txt, docs/elasticsearch.txt, docs/hbase.txt, docs/monitoring.txt, docs/partitioning.txt, docs/reindex.txt, docs/solr.txt, docs/textsearch.txt, docs/upgrade.txt
=> [skip ci] [docs] Spell check

CONTRIBUTING.md, UPGRADE.asc, docs/advblueprints.txt, docs/basics.txt, docs/bulkloading.txt, docs/configuredgraphfactory.txt, docs/directindex.txt, docs/elasticsearch.txt, docs/hbase.txt, docs/monitoring.txt, docs/partitioning.txt, docs/reindex.txt, docs/solr.txt, docs/textsearch.txt, docs/upgrade.txt
=> [skip ci][docs] Spelling merge master

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
Issue : https://github.com/JanusGraph/janusgraph/issues/703
=> [Backport 0.2] Add missing slash in Elasticsearch scroll request.

pom.xml
=> Bump Netty 4.0.53

janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MultiKeySliceQuery.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchSetup.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java, pom.xml
Merge to master PR #689
Issue: #688
Replaces PR #720
=> Merge to master PR #689 via github

janusgraph-dist/pom.xml
Fixes #674 
Backport to branch 0.2
=> Issue 674 hadoop jars are missing in janusgraph 0.2.0 distribution 

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/IndexMappings.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchConfigTest.java, janusgraph-es/src/test/resources/dynamic_mapping.json, janusgraph-es/src/test/resources/strict_mapping.json
1) Fix deserialization of Elasticsearch Mapping.
2) Allow using external dynamic mapping.
Issue : https://github.com/JanusGraph/janusgraph/issues/653
=> [Backport 0.2] Fix issue 653 on external Elasticsearch mapping.

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java
Signed-off-by: Nikolai Grigoriev <ngrigoriev@newforma.com>
-----
=> Fix for #731: add unit tests and correct the conditions

janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
Titan had a different way of defining configuration. Does not
apply anymore so removing.
Fixes #756
-----
=> [skip ci] Remove dead code in GraphDatabaseConfiguration

janusgraph-core/src/main/java/org/janusgraph/graphdb/management/ConfigurationManagementGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/management/JanusGraphManager.java
Addresses #746 partially
Signed-off-by: Alexander Patrikalakis amcp@amazon.co.jp
-----
=> Refer to static members without 'this' instance reference

janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CassandraStorageSetup.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java, janusgraph-examples/example-common/src/test/java/org/janusgraph/example/JanusGraphAppTest.java, janusgraph-examples/example-remotegraph/src/main/java/org/janusgraph/example/RemoteGraphApp.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/config/HadoopConfiguration.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cassandra/CqlBridgeRecordReader.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/HBaseStorageSetup.java, janusgraph-test/src/main/java/org/janusgraph/DaemonRunner.java, janusgraph-test/src/main/java/org/janusgraph/TestBed.java, janusgraph-test/src/main/java/org/janusgraph/blueprints/AbstractJanusGraphProvider.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphConcurrentTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIoTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphPerformanceMemoryTest.java, janusgraph-test/src/main/java/org/janusgraph/olap/ShortestDistanceVertexProgram.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/IDPoolTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/VariableLongTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/serializer/SerializerTest.java, janusgraph-test/src/test/java/org/janusgraph/util/StringEncodingTest.java
Addresses #740 partially (will be completely after #743 is incorporated)
-----
=> Use lambda functions/streams instead of Functional objects

.travis.yml
* `[ -v VAR ]` is invalid; should have used `! [ -z "${VAR:-}" ]`
* `! [ -z "${VAR:-}" ]` is equivalent to `[ -n "${VAR:-}" ]`
See https://github.com/JanusGraph/janusgraph/pull/464#discussion_r153372079 for
context.
-----
- [] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of …
=> Fix and simplify var tests in Travis CI config

janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchStatus.java
=> [skip ci] Refer to ES not HBase in ElasticsearchStatus::parsePidFile

janusgraph-dist/src/assembly/descriptor/readmes.component.xml
=> Update assembly changelog and upgrade location [skip ci]

janusgraph-dist/src/assembly/descriptor/readmes.component.xml
=> Merge fix assembly

janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/inmemory/ColumnValueStore.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
Using Joshua Bloch approved idiom.
Fixes #48
-----
=> Improved Double Checked Locking

janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/core/Multiplicity.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Cmp.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Text.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/ConfigNamespace.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayBuffer.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayEntry.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayEntryList.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/JanusGraphIndexWrapper.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BaseVertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/TypeUtil.java, janusgraph-core/src/main/java/org/janusgraph/util/datastructures/ExceptionUtil.java, janusgraph-core/src/main/java/org/janusgraph/util/datastructures/RandomRemovalList.java
=> Short-circuit if-return-else-return statements

BUILDING.md
Add the command to build distribution archive in `BUILDING.md`.
And point to janusgraph-dist/README.md for the details.
Signed-off-by: Yihong Wang <yh.wang@ibm.com>
-----
=> [skip ci] [docs] Add distribution archive command

janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/idmanagement/ConsistentKeyIDAuthority.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/cache/ExpirationKCVSCache.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayEntryList.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/cache/StandardSchemaCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idhandling/VariableLong.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/StringSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/idmanagement/IDManager.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraMemory.java, janusgraph-test/src/main/java/org/janusgraph/StorageSetup.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/IDAuthorityTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphEventualGraphTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/ConfigurationTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/BufferUtilTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/IDManagementTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/VariableLongTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/serializer/SerializerTestCommon.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTxTest.java, janusgraph-test/src/test/java/org/janusgraph/util/datastructures/RelationCacheTest.java
=> Make long constants end in L for legibility

janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/MultiCondition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/ConcurrentAddedRelations.java, janusgraph-core/src/main/java/org/janusgraph/util/datastructures/IntHashSet.java, janusgraph-core/src/main/java/org/janusgraph/util/datastructures/LongCounter.java
=> Remove methods that only call the superclass method or empty

janusgraph-cassandra/src/test/java/org/janusgraph/graphdb/thrift/ThriftConnectionTest.java, janusgraph-core/src/main/java/org/janusgraph/util/system/NetworkUtil.java
=> Fix localhost usage

janusgraph-es/pom.xml, pom.xml
=> Update default Elasticsearch version to ES 6.0.1

janusgraph-core/src/main/java/org/janusgraph/graphdb/management/JanusGraphManager.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/IndexQueryBuilder.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneIndexTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/ExpectedValueCheckingTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/IDAuthorityTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphPartitionGraphTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-test/src/main/java/org/janusgraph/testutil/JanusGraphAssert.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/attribute/GeoshapeTest.java, janusgraph-test/src/test/java/org/janusgraph/testutil/ObjectSizer.java
=> Stop using deprecated methods in janusgraph-test

janusgraph-dist/src/assembly/static/conf/hadoop-graph/read-hbase-snapshot.properties, janusgraph-dist/src/assembly/static/conf/hadoop-graph/read-hbase.properties, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseBinaryInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/HBaseInputFormatIT.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/HBaseSnapshotInputFormatIT.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/hbase-read-snapshot.properties, janusgraph-hbase-parent/janusgraph-hbase-098/src/main/java/org/janusgraph/diskstorage/hbase/HBaseAdmin0_98.java, janusgraph-hbase-parent/janusgraph-hbase-10/src/main/java/org/janusgraph/diskstorage/hbase/HBaseAdmin1_0.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/AdminMask.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/HBaseStorageSetup.java
=> Support JanusGraph OLAP with HBase TableSnapshotInputFormat #656

README.md
Fixes issue #537.
This is a frequently-asked question on mailing lists as well as Stack Overflow, so it's good to have a place we can refer users to for a list of available tools.
-----
- [] If applicable, have you updated the NOTICE.txt file, including …
=> Add a list of visualization tools [skip ci]

janusgraph-core/src/main/java/org/janusgraph/core/util/JanusGraphCleanup.java
Fixes #849: delegate `JanusGraphFactory#drop` in `JanusGraphCleanup#clear`
-----
=> Issue #849: delegate JanusGraphFactory#drop in JanusGraphCleanup#clear

janusgraph-codepipelines-ci/pom.xml, janusgraph-core/pom.xml
Fix #867.
Signed-off-by: David Moles <david.moles@ucop.edu>
=> Update to maven-shade-plugin 3.1.0. 

janusgraph-codepipelines-ci/pom.xml, janusgraph-core/pom.xml
Reverts JanusGraph/janusgraph#868
=> Revert "Update to maven-shade-plugin 3.1.0. "

RELEASING.md, docs/building.adoc, pom.xml
=> Removed sonatype parent

docs/basics.adoc
Resolves #803 
I searched for and encased .sh, .properties, and .yaml files in addition to files that had paths for consistency. 
-----
=> encased filenames in backticks to fix formatting per issue #803 [skip ci]

docs/elasticsearch.adoc
=> Remove TTL support for Elasticsearch in documentation. 

docs/advschema.adoc
Related to #675
Removing until supported
=> [skip ci] [docs] Remove unsupported unidirected usage

docs/advschema.adoc, docs/elasticsearch.adoc
=> Merge docs to master

janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStep.java, pom.xml
- handle empty hasId
- removed dead code
Fixes #844
Passes all tests including TinkerPop tests:
`mvn clean install -Dtest.skip.tp=false`
-----
=> Update to TinkerPop 3.2.7

janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStep.java, pom.xml
=> Update TinkerPop 3.3.1

janusgraph-codepipelines-ci/pom.xml, janusgraph-core/pom.xml
resolves #867 
Completed local testing with java 9 for janusgraph-core.
-----
=> updated maven-shade version in core and codepipelines poms

docs/directindex.adoc
=> Added gotcha on mixed index availability [skip ci]

docs/directindex.adoc
merges #902 
resolves #896
-----
=> Merge gotcha doc

docs/lucene.adoc, docs/textsearch.adoc, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneIndexTest.java
Implementing custom analyzers for the String type and Mapping string or text
Signed-off-by: Olivier Binda <olivier.binda@wanadoo.fr>
-----
=> issue #672 : Custom analyzer support for LuceneIndex

docs/searchpredicates.adoc, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
=> Add support of compare predicates for String on search backend.

docs/basics.adoc, docs/reindex.adoc, janusgraph-all/src/main/java/org/janusgraph/graphdb/tinkerpop/plugin/JanusGraphGremlinPlugin.java
Merge branch '0.2' into master
Fixes #916
-----
=> Issue 916 merge master

janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
=> [skip ci] fixed concat typo and fixed wording

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-test/src/test/java/org/janusgraph/blueprints/process/traversal/strategy/optimization/JanusGraphStepStrategyTest.java
=> Put support ElementValueComparator back for mixed index.

janusgraph-all/pom.xml, janusgraph-hadoop-parent/pom.xml, pom.xml
=> upgrade datastax cassandra driver version to 3.3.2 from 3.1.4

docs/basics.adoc, docs/multinodejanusgraphcluster.adoc
=> Document graph cache and bindings for JG clusters

docs/partitioning.adoc, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
=> removed explicit partitioning docs

README.md
Make logo in read link to janusgraph.org [skip ci]
fixes #972 
-----
=> Make logo in read link to janusgraph.org [skip ci]

docs/basics.adoc
=> Add details on remote sessions to the docs [skip ci]

docs/upgrade.adoc, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/HBaseStorageSetup.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerConfigTest.java
Fix #862
Signed-off-by: Jerry He <jinghe@us.ibm.com>
-----
=> Issue 862 Fix preferred default timestamp provider logic in janusgraph configuration 

README.md
Adding per request of a company representative's post on
janusgraph-users@; more information at the URL.
-----
/cc: @pankajydv — please review and approve.
=> Add Times Internet as a production user [skip ci]

README.md
This note is citing public presentations and video recorded at a [recent public Netflix meetup][1] and video and slides have been previously [posted publicly as well][2].
/cc: @ipapapa, @v1r3n — please review links and wording and approve once it's OK to merge.
[1]: https://polyglotpersistenceatnetflix.splashthat.com
[2]: https://twitter.com/JanusGraph/status/976129905376231424
=> Add Netflix as a production user.

janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseBinaryInputFormat.java
Thanks to @jerryjch this was already fixed on master as part of Issue #656. This commit adds
in support for the extended HBase properties in concert with the HBaseBinaryInputFormat which
also fixes an OLAP/Google Cloud Bigtable connectivity issue.
-----
=> Issue #1008: HBaseBinaryInputFormat does not read ext parameters

docs/cassandra.adoc
=> Added info on start_rpc and container deployment for Cassandra [skip ci]

docs/cassandra.adoc, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLSSLStoreTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
Signed-off-by: Alex Li <alexli@au1.ibm.com>
fix for issue #933 
-----
=> Check CQL keyspace existence before creating a new one. #933

docs/basics.adoc
=> Document which data types can be used in a VCI [skip ci]

docs/changelog.adoc, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModule.java, pom.xml
- fixes #1038
Cherry picked a0b5f31f7a473058129ddf2e7490fc0d7b32af22 from PR #1011 then updated the version to 3.3.2.
Tested against the TinkerPop suite
```
mvn clean install -Dtest.skip.tp=false
```
-----
=> update to TinkerPop 3.3.2

pom.xml
Fixes issue #1067
```
mvn clean install -Dtest.skip.tp=false
```
-----
- [] Have you ensured that format looks appropriate for the output in which it is rendered?
- [] If this PR is a documentation-only change, have you added a `[skip ci]`
=> upgrade to Apache TinkerPop 3.2.9

docs/hbase.adoc
Fixes #887
Signed-off-by: jinghe <jinghe@us.ibm.com>
-----
=> Document timestamp provider for HBase backend #887 [skip ci]

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
Signed-off-by: Alex Li <alexli@au1.ibm.com>
-----
=> Check CQL keyspace existence before getting tables. Fix of CQL tests breaking in Travis #1085

janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/util/GiraphInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/util/GiraphRecordReader.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/HBaseSnapshotInputFormatIT.java
Fixes: #1083 
Signed-off-by: Evgeniy Ignatiev <yevgeniy.ignatyev@gmail.com>
-----
=> Implement OLAP edge filtering by image of GraphFilterInputFormat

pom.xml
Fixes #1072
Recreated PR #1073
-----
=>  Upgrade to Apache TinkerPop 3.3.3

janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerConfigTest.java
=> Use storage.port for HBase backend #492

janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/StandardEdge.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java
Fixes #1081 
Signed-off-by: Evgeniy Ignatiev <yevgeniy.ignatyev@gmail.com>
-----
=> Do not evaluate vertex/edge labels unless constraint checking is enabled

janusgraph-all/src/main/java/org/janusgraph/graphdb/tinkerpop/plugin/JanusGraphGremlinPlugin.java
fixes #1120. Confirmed I could build distro locally after changes were applied.
-----
=> Removing leftover GeoshapeHelper Imports to resolve issue #1120

docs/basics.adoc
The link goes to the GitHub README as that seemed to be the best landing page and because it contains links for the various formats.
Fixes #1109.
Signed-off-by: Florian Hockmann <fh@florian-hockmann.de>
-----
=> Add link to Practical Gremlin book #1109 [skip ci]

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchIndexTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchMultiTypeIndexTest.java
=> Delete only janusgraph-aliased indices in Elasticsearch clearStorage

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchIndexTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchMultiTypeIndexTest.java
This is a request to merge 0.2 into master
-----
=> Merge 0.2 into master

README.md
Partially addresses #1155; will also need to add their logo to the
website to finish the work.
/cc: @woncius, @Icaruszzc, @imbajin
-----
- [/] Have you written and/or updated unit tests to verify your changes?
- [/] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [/] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [/] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of …
=> Add Qihoo 360 as a production user [skip ci]

README.md
RedHat built their application migration and assessment tool with an
open-source project they released (Windup), which directly depends on
JanusGraph.
Partially addresses issue #1153; will be fixed by the corresponding
website update to add the logo.
-----
- [/] Have you written and/or updated unit tests to verify your changes?
- [/] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [/] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this …
=> Add Red Hat to list of production users [skip ci]

janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseKeyColumnValueStore.java
Signed-off-by: Jerry He <jinghe@us.ibm.com>
Fixes #1170 
-----
=> Use column name offset in HBase ColumnPaginationFilter #1170

.travis.yml
=> Run CI batch compile even when not doing coverity scan.

docs/basics.adoc
=> [skip ci] Fixed error in vertex-centric doc.

docs/appendices.adoc, docs/basics.adoc, docs/doc-versions.adoc, docs/static/css/docs.css, docs/xsl/common.xsl
Since the new policy isn't merged yet I'm not sure if I should CTR this even though it seems like great candidate.
-----
=> Merge to master docfixes

README.md
Per issue #1178 (see issue for preview), this change is replacing badges
in the README that which are simply links (and provide no dynamic
information), AND already have equivalent links in the Community
section, namely:
* Gitter chat
* Stack Overflow tag
and replacing them with a new badge which provides an instant view at
the popularity / success of the project, namely:
* Total number of downloads (all time, for all versions)
The number of downloads of each specific version is already covered as I
added a per-version badge to each of the downloads in the releases
section: https://github.com/JanusGraph/janusgraph/releases
Fixes issue #1178.
----- …
=> Replace Gitter & SO badges with Downloads [skip ci]

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementLogger.java
Fixes #1218
-----
- [] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?
- [] Have you ensured that format looks appropriate for the output in which it is rendered?
- [] If this PR is a …
=> Use JanusGraphManagerUtility to avoid NoClassDefFoundError

docs/cassandra.adoc, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java, janusgraph-dist/src/assembly/static/conf/cassandra/cassandraTables.cql
Issue #1103 Cassandra Privilege "Create on Table"
PR #1110 was merged into 0.2 branch
-----
=> Issue #1103 Merge branch 0.2 to master. CTR.

docs/textsearch.adoc, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/ParameterType.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchIndexTest.java
Adds the possibility to use custom properties with Elasticsearch index backend on mapping.
Related discussion: https://groups.google.com/forum/#!topic/janusgraph-dev/xKSouClyIJs
Fixes issue #1242.
-----
=> Use custom properties in ElasticSearchIndex

README.md
Fixes #1149; though this is just a starter list and will be continuously
updated.
-----
- [/] Have you written and/or updated unit tests to verify your changes?
- [/] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [/] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [/] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?
tag to the first line of your …
=> Add projects built with JanusGraph [skip ci]

.travis.yml, janusgraph-all/pom.xml, janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml, janusgraph-examples/example-hbase/README.md, janusgraph-examples/example-hbase/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-2/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseCompatLoader.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/HBaseStorageSetup.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerConfigTest.java, janusgraph-hbase-parent/janusgraph-hbase-server/pom.xml, pom.xml
Signed-off-by: Jerry He <jerryjch@apache.org>
Fixes #1213 
-----
=> Create a HBase 2 profile #1213

.travis.yml
CTR to merge travis-ci fixes from 0.2
-----
=> Travis fix merge

janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/AbstractTypedRelation.java
Signed-off-by: Ranger Tsao <cao.zhifu@gmail.com>
Fix #1114
-----
=> Issue #1114: fix GremlinServer  StackOverflowError

janusgraph-core/src/main/java/org/janusgraph/graphdb/management/ConfigurationManagementGraph.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/management/ConfigurationManagementGraphTest.java
Issue: https://github.com/JanusGraph/janusgraph/issues/1265
Signed-off-by: Peter May <Peter.May@ibm.com>
-----
=> Fixed bug in ConfigurationManagementGraph

janusgraph-core/src/main/java/org/janusgraph/core/Transaction.java
I am not a native speaker, but i think my change is more correct..
-----
=> Simple-fix grammar in javadoc of indexQuery method

janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrRunner.java
Fixes #1165 (merge to master)
-----
- [] Is there an issue associated with this PR? Is it referenced in the commit message?
- [] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [] Is your initial contribution a single, squashed commit?
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as …
=> Merge PR #1282 to master

docs/basics.adoc, docs/connecting-via-dotnet.adoc, docs/connecting-via-java.adoc, docs/connecting-via-python.adoc, docs/connecting.adoc, docs/index.adoc
The new part in the docs simply shows examples for the most frequently used languages Java, Python and .NET/C# on how to connect to JanusGraph Server and points to the lists of available TinkerPop drivers and languages. So, users can also just pick one from there in case they are using a language that is not covered by these docs.
These changes intentionally don't mention the new libraries that we currently work on. I propose that we first just add a part to the docs that explains how to connect to JanusGraph from different languages by using the already available TinkerPop GLVs (this PR). We can then extend this part later when we have first official releases for these libraries with #1276.
A preview of the docs is available [here](https://florianhockmann.github.io/docs.janusgraph.org/0.2 …
=> Add docs on how to connect to JanusGraph Server #205 [skip ci]

docs/serializer.adoc, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/StandardSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/JsonNodeParseException.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/JsonSerializer.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/serializer/SerializerTest.java
=> Add json serializers

janusgraph-test/src/test/java/org/janusgraph/diskstorage/keycolumnvalue/StaticArrayEntryTest.java
=> Refactor duplicate code in StaticArrayEntryTest

janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchConfigTest.java
=> Refactor duplicate code in ElasticSearchConfigTest

janusgraph-core/src/main/java/org/janusgraph/graphdb/management/JanusGraphManager.java
=> Refactor duplicate code in JanusGraphManager

janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLResultSetKeyIteratorTest.java
=> Refactor duplicate code in CQLResultSetKeyIteratorTest

janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/AbstractCassandraStoreManager.java
=> Refactor duplicate code in AbstractCassandraStoreManager

janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneIndexTest.java
I noticed 18 warnings like the one below when I was running the Lucene tests and decided to submit this trivial fix that already exists in Master. I also want to see if travis not building on the 0.2 branch is an isolated incident.
```
[WARNING] /Users/chupman/github/janusgraph/janusgraph/janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneIndexTest.java:[97,72] unchecked call to Parameter(java.lang.String,V) as a member of the raw type org.janusgraph.core.schema.Parameter
```
-----
Travis CI …
=> resolve some unchecked call warnings in Lucene test

CONTRIBUTING.md, docs/development.adoc
I documented what is my understanding of our current policy regarding which branch to target with a PR and how PRs should be merged.
Fixes #197
-----
- [-] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in …
=> Add notes about release branches #197 [skip ci]

BUILDING.md, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/SubqueryIterator.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneIndexTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
Merging 0.2 PRs into master
-----
=> Merge 0.2 commits

janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java
I didn't add the new commands to the docs, but I want to take a look at the indexing docs to include information from the wiki as well as new commands in the next week or two. 
Width is currently 100 characters and does not trim fields so long names can affect the table structure. Personally if I had multiple indexes with matching lengthy prefixes I would rather still see the information and have an ugly table. I may also feel that anyone with index names over 30 characters long deserves an ugly table, but it's easy to change if anyone has a strong opinion about it.
Partially addresses #1163 
-----
to ensure the following steps have …
=> Created commands to print various schema elements within mgmt api

.github/ISSUE_TEMPLATE.md
Creates a default issue template with pointing to the right groups to ask questions if the issue isn't a bug report or feature request.
Fixes #1383 
-----
=> Create issue template #1383 [skip ci]

janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java
-----
- [] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
=> Merge print schema

janusgraph-cassandra/src/test/java/org/janusgraph/graphdb/thrift/ThriftGraphSpeedTest.java, janusgraph-core/src/main/java/org/janusgraph/core/ConfiguredGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/ReadConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/builder/ModifiableConfigurationBuilder.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilder.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/converter/ReadConfigurationConverter.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/idmanagement/AbstractIDAuthority.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StandardBaseTransactionConfig.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/builder/GraphDatabaseConfigurationBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/converter/RegisteredAttributeClassesConverter.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/validator/CompatibilityValidator.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/idmanagement/UniqueInstanceIdRetriever.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphSpeedTest.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerConfigTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/IDAuthorityTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/GraphDatabaseConfigurationInstanceIdTest.java, janusgraph-test/src/test/java/org/janusgraph/core/ConfiguredGraphFactoryTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfigurationTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/management/ConfigurationManagementGraphTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/management/ManagementLoggerGraphCacheEvictionTest.java
Related to #1148 
Partially refactor GraphDatabaseConfiguration class.
What were changed:
- Code was split into smaller logical units (private methods);
- Configurations building code was moved into Builders;
- Compatibility validation code was moved into Validator;
- Some converting code was moved into Converters;
- Methods reordered in GraphDatabaseConfiguration to have all public methods at the top and all private methods at the bottom;
- "Some" methods which should not be in GraphDatabaseConfiguration were moved. getPath method was deleted;
-----
tag to the first line of …
=> Refactor GraphDatabaseConfiguration

docs/basics/index-performance.md, docs/basics/server.md, janusgraph-core/src/main/java/org/janusgraph/util/system/ConfigurationPrinter.java, mkdocs.yml
=> Fix all cherry pick issues

docs/upgrade.adoc, janusgraph-all/pom.xml, janusgraph-cassandra/pom.xml, janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/embedded/CassandraEmbeddedKeyColumnValueStore.java, janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/thrift/CassandraThriftKeyColumnValueStore.java, janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/thrift/CassandraThriftStoreManager.java, janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/thrift/thriftpool/CTConnectionFactory.java, janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/utils/CassandraHelper.java, janusgraph-cassandra/src/test/java/org/janusgraph/diskstorage/cassandra/utils/CassandraHelperTest.java, janusgraph-core/pom.xml, janusgraph-cql/pom.xml, janusgraph-es/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cassandra/CassandraBinaryRecordReader.java, janusgraph-hadoop-parent/pom.xml, janusgraph-solr/pom.xml, pom.xml
This PR includes:
* Upgrade Cassandra from 2.1.20 to 2.2.13.
* Update Astyanax to 3.10.2.
* Include JNA as a test dependency for projects depending on `janusgraph-cassandra`. This was necessary as Cassandra did not start any more without it.
* Updated from `com.codahale.metrics` to `io.dropwizard.metrics` as Cassandra didn't work with the older version from `com.codahale.metrics` any more (the `test.log` contained a lot of errors about a missing method in that package).
This fixes #1398.
-----
- [-] If adding new dependencies to the code, are these dependencies …
=> Upgrade Cassandra to version 2.2 #1398

janusgraph-test/src/test/java/org/janusgraph/graphdb/configuration/validator/CompatibilityValidatorTest.java
This PR is related to a flow to improve test coverage of the old `GraphDatabaseConfiguration`.
-----
=> Cover CompatibilityValidator with unit tests

janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/backend/builder/KCVSConfigurationBuilder.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/builder/GraphDatabaseConfigurationBuilder.java
To have a possibility to cover `ReadConfigurationBuilder` with unit tests I think we should move building logic of `KCVSConfiguration` away from `Backend` because in that case we can't mock `KCVSConfiguration` and that is why we should add some mocks to correctly build `KCVSConfiguration` and use unnecessary assertion to catch backend exceptions. See commit (method `callBuilder`): 
https://github.com/porunov/janusgraph/commit/c8581bec72148394cd2a7b468ced82d08d2419ec
After this PR I will be able to cover `ReadConfigurationBuilder` with unit tests easier.
-----
tag to the first line of your commit message to …
=> Refactor ReadConfigurationBuilder

.travis.yml, TESTING.md, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/log/LogTest.java, janusgraph-test/src/main/java/org/janusgraph/testutil/FlakyTest.java, janusgraph-test/src/main/java/org/janusgraph/testutil/FlakyTestExtension.java, janusgraph-test/src/main/java/org/janusgraph/testutil/RetryInfo.java, janusgraph-test/src/main/java/org/janusgraph/testutil/RetryTemplateContext.java, janusgraph-test/src/main/java/org/janusgraph/testutil/RetryingTestExecutionExtension.java, janusgraph-test/src/main/java/org/janusgraph/testutil/RetryingTestFailure.java, pom.xml
Fixes #1016 
Based on stackoverflow post: https://stackoverflow.com/a/46207476/2978513
-----
=> Allow marking of tests as flaky #1016

janusgraph-dist/janusgraph-dist-hadoop-2/docker-compose.yml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml
This PR is a plain copy paste of #1204 made by @amcp .
Unfortunately I didn't get responses in #1203 . The PR #1204 is stale for half a year that is why I am considering to merge this PR unless there is objections. 
Fixes #1203
-----
=> add non-es berkeleyje configuration #1203

janusgraph-core/src/main/java/org/janusgraph/graphdb/management/ConfigurationManagementGraph.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/management/ConfigurationManagementGraphTest.java
https://github.com/JanusGraph/janusgraph/issues/1401
-----
=> Fix tx leaks in ConfigurationManagementGraph

APACHE-2.0.txt, LICENSE.txt
This line is not supposed to be a specific copyright holder or year;
it's a template line, and should have been transferred as-is from the
Apache 2.0 license, which can be found at
https://www.apache.org/licenses/LICENSE-2.0.txt
-----
@pluradj — should this be applied to the `0.2` branch? or `master`? or all the branches? I noticed there isn't a `0.3` branch for some reason, despite the recent 0.3.x releases...
----
- [-] Is there an issue associated with this PR? Is it referenced in the commit message?
- [-] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [-] Have you written and/or updated unit …
=> Fix Apache license copyright template. [skip ci]

docs/hadoop.adoc, janusgraph-dist/src/assembly/static/conf/hadoop-graph/hadoop-graphson.properties, janusgraph-dist/src/assembly/static/conf/hadoop-graph/hadoop-gryo.properties, janusgraph-dist/src/assembly/static/conf/hadoop-graph/hadoop-load.properties, janusgraph-dist/src/assembly/static/conf/hadoop-graph/hadoop-script.properties, janusgraph-dist/src/assembly/static/ext/plugins.txt, janusgraph-dist/src/release/index.html, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cassandra/Cassandra3InputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cassandra/CassandraInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/util/HadoopInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/util/HadoopRecordReader.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/cassandra-read.properties, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/hbase-read-snapshot.properties, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/hbase-read.properties
All support for Giraph was removed with TinkerPop 3.4.0. So, this pull request removes all mentions of Giraph.
Part of #1364
-----
- [-] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this …
=> Remove all mentions of Giraph

APACHE-2.0.txt, LICENSE.txt
CTR merge
-----
- [] Is there an issue associated with this PR? Is it referenced in the commit message?
=> Merge 0.2 commits licenses

APACHE-2.0.txt, LICENSE.txt
=> Merge 0.3 license

janusgraph-berkeleyje/pom.xml, janusgraph-test/pom.xml, janusgraph-test/src/main/java/org/janusgraph/TestCategory.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/inmemory/InMemoryGraphTest.java
=> Partial cleanup of JanusGraphTest

README.md
The link just points to the [user manual](https://arcadeanalytics.com/usermanual/#arcade-analytics) as that contains a good description about what Arcade Analytics is in general and it also presents the two editions (open source and enterprise). I think this is the information our users are most interested in when they're looking for a visualization tool.
Fixes #1428
This supersedes #1432 as discussed there with @robfrank so he doesn't have to go through our CLA process to add a single line.
-----
- [-] If adding new dependencies to the code, are these dependencies …
=> Add Arcade Analytics visualization tool [skip ci]

janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerMutationTest.java
Fixes #1454
Signed-off-by: Zheng Wang <zhengwang1990@foxmail.com>
-----
=> Convert HBase TTL param from Integer to long JanusGraph#1454

janusgraph-test/src/test/java/org/janusgraph/graphdb/vertices/StandardVertexTest.java
Added deadlock test for PR #1380
Fixes #1451
-----
=> Add deadlock on parallel vertex removal test #1451

janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerMutationTest.java
The PR merges `0.2` into `0.3` with resolved conflicts
-----
=> Merge 0.2 into 0.3

docs/configuredgraphfactory.adoc
Fixes #1372 
Signed-off-by: Prithvi Nambiar <prithvinambiar@gmail.com>
-----
=> Fix for incorrect CFG documentation #1372

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategy.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategyTest.java
https://github.com/JanusGraph/janusgraph/issues/1500
-----
=> Fix adjacent vertex filter stuck

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchIndexTest.java
Current implementation makes no difference between `SET` and `LIST` cardinality when using ES as indexing backend: no deduplication is done thus making ES contain non-unique elements even if SET cardinality specified.
This PR resolves the issue by adding deduplication step to addition script. I'm not sure if it's the right choice to use `distinct` from Stream API, so please suggest any replacement if such approach is not acceptable for some reason.
I've also provided two integration tests to demonstrate the issue with invalid handling of cardinality. Quite probably these tests should be moved from ElastisearchIndexTest to somewhere else (IndexProviderTest?) since they are backend independent. But as far as I know there is no complete support for these cardinalities across different …
=> Value deduplication for fields with SET cardinality for Elasticsearch

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/NumericTranslationQueryParser.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneIndexTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
=> Add numeric query parser to lucene index

janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/converter/RegisteredAttributeClassesConverter.java
Remove unnecessary null checks after `Class.forName(classname);` and `serializerClass.newInstance();`. Add needed spaces in some error messages. Split code to multiple methods for easier readability.
-----
=> Refactor RegisteredAttributeClassesConverter

janusgraph-core/src/main/java/org/janusgraph/graphdb/idmanagement/UniqueInstanceIdRetriever.java
Resolved duplicate code.
-----
=> Refactor UniqueInstanceIdRetriever

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
=> Add sort field for STRING mappings in lucene index

janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/UniqueInstanceIdRetrieverTest.java
=> Cover UniqueInstanceIdRetriever with unit tests

janusgraph-test/src/test/java/org/janusgraph/graphdb/configuration/converter/RegisteredAttributeClassesConverterTest.java
=> Cover RegisteredAttributeClassesConverter with unit tests

janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/converter/ReadConfigurationConverterTest.java
=> Cover ReadConfigurationConverter with unit test

janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphIndexQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/RawQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/IndexQueryBuilder.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
Resolve Issue #1468
Signed-off-by: Vladimir Bogomolov <vladimir.bogomoloff@gmail.com>
-----
=> Add sorting parameters to raw query

docs/basics.adoc, docs/generating.adoc, docs/searchpredicates.adoc, janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/example/GraphOfTheGodsFactory.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/Order.java, janusgraph-dist/src/assembly/static/data/grateful-dead-janusgraph-schema.groovy, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/AbstractIndexManagementIT.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
=> Stop using deprecated Order.incr and Order.decr #1562

docs/basics.adoc
=> [skip ci] Added documentation on printSchema methods

BUILDING.md, janusgraph-dist/pom.xml
replaces #621 
Added in the required fixes in an additional commit.
-----
=> Proxy support amended

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializerTest.java
=> Fix date serializer for string value

BUILDING.md, docs/basics.adoc, janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/CacheVertex.java, janusgraph-dist/pom.xml, janusgraph-test/src/test/java/org/janusgraph/graphdb/vertices/CacheVertexTest.java
I didn't want to do an atomic merge since master was showing over 200 files getting updated. I can look into a merge from 0.3 to master after this goes in.
-----
=> 0.2 to 0.3 merge

docs/upgrade.adoc, janusgraph-berkeleyje/pom.xml
All TinkerPop tests pass with:
```bash
mvn verify -pl janusgraph-berkeleyje -Dtest.skip.tp=false -DskipTests=true
```
(in addition to the normal tests already executed on Travis).
Fixes #1570
-----
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [-] If applicable, have you updated the NOTICE.txt …
=> Upgrade to Berkeley DB JE 7.5.11

BUILDING.md, docs/basics.adoc, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/CacheVertex.java, janusgraph-dist/pom.xml, janusgraph-test/src/test/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializerTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/vertices/CacheVertexTest.java
=> 0.3 merge to master

.travis.yml.cassandra
Tried to run [version testing for Cassandra](https://travis-ci.org/chupman/janusgraph/jobs/534952884) by moving `.travis.yml.cassandra` to `.travis.yml` and ran into the same parsing I fixed in #1252. 
With the line breaks `mvn` gets interpreted with a prepending space and can't be found. Here's the [issue](https://github.com/travis-ci/travis-ci/issues/10111) I opened in travis-ci for reference.
-----
Please ensure that once the PR is submitted, …
=> fixed parsing error caused by line breaks

janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexMutation.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexTransaction.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
=> Fix the problem of index update for the columns that have collection cardinality.

pom.xml
We have the enhancement issue #1510 to update cassandra driver to 4.x version. I think it would be good but it requires more time to test and research pros and cons of this version. I am not sure that we will update Cassandra driver to 4.x version in 0.4.0 release but we can update the driver to 3.7.x release because it introduces some performance improvements in the core module.
Changelog: https://docs.datastax.com/en/developer/java-driver/3.7/changelog/
Travis: https://travis-ci.org/porunov/janusgraph/builds/537711582
-----
tag to the first line of your commit message to …
=> Update Cassandra driver to 3.7.1

.travis.yml.cassandra, docs/changelog.adoc, docs/doc-versions.adoc, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java, janusgraph-dist/src/assembly/static/bin/gremlin-server.sh
=> Merge 0.2.3 release to 0.3 branch

RELEASING.md
partially addresses #629 
I did a first pass on merging my notes with `RELEASING.md`. I would love for this to be validated via the next release. Feedback on the flow would also be greatly appreciated. 
-----
=> [skip ci] lessons learned and notes added to release instructions.

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategy.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategyTest.java
=> Fix adjacent optimization for detached vertices

.travis.yml
fixes #1594 
Here's an [example](https://travis-ci.org/chupman/janusgraph/builds/536458452) from my branch showing how the jobs get added when run in cron.
I actually ran into issues getting it to run on tags, but I did figure out building based of commit message contents which I think is better anyways. Here's an [example](https://travis-ci.org/chupman/janusgraph/builds/536917826)
-----
Please ensure that once the PR is submitted, you check …
=> added additional cassandra jobs to run on cron and [full build] 

RELEASING.md
=> Document lessons learned during the release of 0.3.2 [skip ci]

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
Wrap IndexReader on try-resource
Fix #1643
=> Fix resource leaks in LuceneIndex.restore

pom.xml
I often see this error (described in #1320) when making some unrelated changes. I don't know what really causes it but updating `maven-resources-plugin` to `3.1.0` fixes the issue.
The solution was found in comments here: https://stackoverflow.com/questions/26281322/mavenfailed-to-execute-goal-org-apache-maven-pluginsmaven-resources-plugin2-7
Fixes #1320
Example of failed build: https://travis-ci.org/porunov/janusgraph/jobs/552172181
P.S. PR #1648 has the same fix but I will rebase it after this PR is merged.
-----
tag to the first line of your commit message to avoid spending …
=> Update maven-resources-plugin to 3.1.0

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsTransaction.java, janusgraph-test/src/test/java/org/janusgraph/core/TransactionTest.java
Fix for #1341 and partially for #1278 
-----
=> Fix potential transaction leaks

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
=> Minimize data loading during lucene index lookup

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
This PR prepare fix only for #764. Partially based on this PR #929
After merge I will prepare PR for #670
-----
=> Fix loses index during document updates

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
=> [0.4 is blocked] WIP: Merge 0.3 branch

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/AbstractElement.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/RelationIdentifier.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/lock/IndexLockTuple.java
=> Simplify hashcode for Long

docs/lucene.adoc, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java, janusgraph-solr/src/test/resources/solr/core-template/schema.xml, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
=> Add support set/list cardinality to lucene

pom.xml
Changelog: https://docs.datastax.com/en/developer/java-driver/3.7/changelog/
-----
=> Update Cassandra driver to 3.7.2 [full build]

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/NumericTranslationQueryParser.java, janusgraph-solr/src/test/resources/solr/core-template/schema.xml, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
=> Add support for sort and rawQuery by boolean fields for Lucene

janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexUpdateJob.java
=> Fix logger class in IndexUpdateJob

janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
=> Fix flaky test `IndexProviderTest.testPersistantIndexData`

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
The optimization is tested on a laptop. Tested with unique index stores count from 1 to 1000000 with `^10` gap. Each gap is tested with parallel threads from 1 to 100. The amount of calls in each thread were from `100000` to `10000000`. 
The threads amount and method call didn't influence differences in speedup much.
The amount of unique index stores amount influence the results.
If unique index stores amount is from 1 to 1000 the result speed up is about 3.4 - 3.8 times faster.
If unique index stores amount is from 1000 to 10000 the result speed up is about 2 times faster.
If unique index stores amount is from 10000 to 50000 the result speed up is about 20-30 % faster.
If unique index stores amount is from 50000 to 100000 the result speed up is about 5 % faster.
If unique index stores …
=> Optimize indexStore names generation in ElasticSearchIndex by caching it

docs/cassandra.adoc, janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/astyanax/AstyanaxStoreManager.java, janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/embedded/CassandraEmbeddedStoreManager.java, janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/thrift/CassandraThriftStoreManager.java
=> Mark all non CQL Cassandra backends as deprecated

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/NumericTranslationQueryParser.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
=> Add support for raw lucene date range queries

janusgraph-core/src/main/java/org/janusgraph/core/schema/Parameter.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/ConfigElement.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeyRangeQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeySliceQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/SliceQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/log/util/AbstractMessage.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/log/StandardTransactionId.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/log/StandardTransactionLogProcessor.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/DirectionCondition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/FixedCondition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/IncidenceCondition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/IncidenceDirectionCondition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/MultiCondition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/Not.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/PredicateCondition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/RelationTypeCondition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/VisibilityFilterCondition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/JointIndexQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MultiKeySliceQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/QueryInfo.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/lock/LockTuple.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/IndexField.java, janusgraph-core/src/main/java/org/janusgraph/util/datastructures/RangeInterval.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/KeyColumn.java
Use in-built hasCode builder
-----
=> Change HashCodeBuilder to java Objects.hash/hashCode

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchConstants.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/AbstractESCompat.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/script/ESScript.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/script/ESScriptResponse.java
This is generally very small improvement but it is still an improvement.
Instead of passing the next 257 symbols:
```
"lang":"painless","source":"for (field in params.fields) {if (ctx._source[field.name] == null) {ctx._source[field.name] = [];}if (field.cardinality != 'SET' || ctx._source[field.name].indexOf(field.value) == -1) {ctx._source[field.name].add(field.value);}}"
```
We will pass 21 symbols by default during the addition operation:
```
"id":"janusgraph-add"
```
Instead of passing the next 352 symbols:
```
"lang":"painless","source":"for (field in params.fields) {if (field.cardinality == 'SINGLE') {ctx._source.remove(field.name);} else if (ctx._source.containsKey(field.name)) {def fieldIndex = ctx._source[field.name].indexOf(field.value);if (fieldIndex >= 0 && fieldIndex < …
```
=> Use stored ES scripts instead of inline scripts

janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java, janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJETx.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/BerkeleyTransactionTest.java
=> Fix rollback long running tx in bdb

janusgraph-cql/pom.xml, janusgraph-es/pom.xml, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java, janusgraph-solr/pom.xml, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/CQLSolrTest.java
=> Replace thrift index tests with CQL

.travis.yml
=> Redo changes on branch v0.2

.travis.yml, janusgraph-dist/pom.xml
It seems that i had to remove the coverage on tinkerpop tests only.
* Fix build error of janusgraph-dist
* split up TinkerPop tests and normal tests for module test
-----
=> Remove retry and improve tinkerpop testing

docs/connecting/python.md
Fixes #1706
Based on #1707 
-----
=> Fix code comment for Python doc

CONTRIBUTING.md
=> Update contribution doc to automated CLA [skip ci]

docs/basics/index-performance.md
Fix for #1515 
Signed-off-by: Darwin Yip <yip.darwin@gmail.com>
-----
=> Fix doc on Vertex-centric edge indexing [doc only]

.travis.yml
=> Change docs destination repository [doc only]

docs/CNAME
Blocked by https://github.com/JanusGraph/docs.janusgraph.org/pull/38
Part of #1420 
-----
=> Move docs to docs.janusgraph.org [doc only]

docs/changelog.md, janusgraph-es/pom.xml, pom.xml
=> Bump ElasticSearch to 7.3.1

.travis.yml
=> Check repo before deployment

README.md
=> Fix Unifi link [doc only]

TESTING.md, janusgraph-berkeleyje/pom.xml, janusgraph-cassandra/pom.xml, janusgraph-cassandra/src/test/java/org/janusgraph/diskstorage/cassandra/AbstractCassandraStoreTest.java, janusgraph-cassandra/src/test/java/org/janusgraph/diskstorage/cassandra/embedded/EmbeddedStoreTest.java, janusgraph-cassandra/src/test/java/org/janusgraph/diskstorage/cassandra/thrift/ThriftDistributedStoreManagerTest.java, janusgraph-cql/pom.xml, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLDistributedStoreManagerTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java, janusgraph-dist/pom.xml, janusgraph-hbase-parent/pom.xml, janusgraph-test/pom.xml, janusgraph-test/src/main/java/org/janusgraph/JanusGraphBaseStoreFeaturesTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/DistributedStoreManagerTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/KeyColumnValueStoreTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/KeyValueStoreTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphBaseTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphPartitionGraphTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-test/src/main/java/org/janusgraph/testutil/FeatureFlag.java, janusgraph-test/src/main/java/org/janusgraph/testutil/FeatureRequirementCondition.java, janusgraph-test/src/main/java/org/janusgraph/testutil/JanusGraphFeature.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/StorageFeaturesTest.java, pom.xml
=> Add feature flags to execute tests

.github/ISSUE_TEMPLATE.md, RELEASING.md, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/core/RelationType.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/AttributeSerializer.java, janusgraph-examples/example-berkeleyje/README.md, janusgraph-examples/example-cassandra/README.md, janusgraph-examples/example-common/README.md, janusgraph-examples/example-cql/README.md, janusgraph-examples/example-hbase/README.md, janusgraph-examples/example-remotegraph/README.md
=> Fix broken links to docs [doc only]

janusgraph-cql/pom.xml, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexJobs.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/scan/AbstractHadoopScanRunner.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/scan/CQLHadoopScanRunner.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/CQLIndexManagementIT.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/CQLInputFormatIT.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/CQLScanJobIT.java, janusgraph-hadoop-parent/pom.xml
=> Support hadoop index management for cql

janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/KeyColumnValueStoreTest.java
=> Fix deletion a non-existing key in berkeleydb

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
=> Fix lucene tokenize if single token #1405

janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/GhostVertexRemover.java, janusgraph-test/src/main/java/org/janusgraph/olap/OLAPTest.java
=> Fix GhostVertexRemover

janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java
=> Make berkeleyje return real iterator

janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java
=> Improve reindex for mixed indexes

.travis.yml, CONTRIBUTING.md, RELEASING.md, docs/basics/janusgraph-cfg.md, janusgraph-core/src/main/java/org/janusgraph/util/system/ConfigurationPrinter.java
=> Update contributing and release as follow up for mkdocs switch

janusgraph-core/src/main/java/org/janusgraph/core/Multiplicity.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/PropertyKeyMaker.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/SchemaInspector.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphDefaultSchemaMaker.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/StandardPropertyKeyMaker.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/StandardRelationTypeMaker.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/AbstractVertex.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphDefaultSchemaMakerTest.java
=> Use cardinality from a gremlin query to auto create a propertyKey

janusgraph-dist/src/assembly/cfilter/conf/janusgraph-berkeleyje-es.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-berkeleyje-lucene.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-berkeleyje-solr.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-berkeleyje.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra-embedded-es.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra-embedded-solr.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra-embedded.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra-es.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra-solr.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-es.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-solr.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-hbase-es.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-hbase-solr.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-hbase.properties
Closes #662
Signed-off-by: Boxuan Li <liboxuan@connect.hku.hk>
-----
=> Update properties files to add `gremlin.graph` setting [doc only]

janusgraph-core/pom.xml, pom.xml
=> Fix conflicting versions of high-scale-lib

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/flaky-test.md, .github/ISSUE_TEMPLATE/question.md
=> Add issue templates to speed up development process

janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java
This resolves #1763 
Removed unnecessary stack trace
-----
=> issue#1763 removed unneeded stack trace

NOTICE.txt, janusgraph-all/pom.xml, janusgraph-es/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/AbstractGremlinServerIntegrationTest.java, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, pom.xml
I did removed some dependences 
-----
=> Dependences cleanup

janusgraph-all/pom.xml
=> Removed duplicated entry in pom for janusgraph-cql

janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/AttributeSerializer.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Cmp.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Contain.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Geo.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Geoshape.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/JtsGeoshapeHelper.java, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Text.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/JobStatus.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/Parameter.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/SchemaStatus.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/VertexLabelMaker.java, janusgraph-core/src/main/java/org/janusgraph/core/util/JanusGraphCleanup.java, janusgraph-core/src/main/java/org/janusgraph/core/util/JanusGraphId.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/ConfigElement.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/TransactionalConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilder.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KCVSUtil.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreAdapter.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/log/util/AbstractMessage.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/EdgeSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchConstants.java, janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphHttpChannelizer.java, janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphNioChannelizer.java, janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphWebSocketChannelizer.java, janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphWsAndHttpChannelizer.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/HMACAuthenticator.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/handler/HttpHMACAuthenticationHandler.java
Signed-off-by: Michal Podstawski <mpodstawski@gmail.com>
-----
=> Minor code cleanup (NPEs etc)

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchSetup.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/ESCompatUtils.java
=> Refactor in ES module

janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/BerkeleyGraphComputerProvider.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyJanusGraphComputerTest.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyMultiQueryJanusGraphProcessTest.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyProcessComputerSuite.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/BerkeleyTransactionTest.java
This PR should fix issues with TP testing with bdb backend #1854 and #1617
-----
=> Add fixes for TP tests on berkeley backend

janusgraph-inmemory/src/test/resources/log4j.properties
=> Add log4j.properties to inmemory

docs/advanced-topics/advschema.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/KeyValueStoreTest.java, janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java, janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/BerkeleyStorageSetup.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/KeyValueEntry.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStore.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreAdapter.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreManagerAdapter.java
Fix for #142 
Berkeleyje support only HOURS/DAYS granularity of TTL [WriteOptions.setTTL](https://docs.oracle.com/cd/E17277_02/html/java/com/sleepycat/je/WriteOptions.html#setTTL-int-java.util.concurrent.TimeUnit-), need to specify in doc
-----
=> Add cell ttl support to BerkeleyDB

docs/basics/schema.md, docs/changelog.md, mkdocs.yml, pom.xml
This update makes a very small breaking change (if it can be counted as a breaking change). If `Automatic Schema Maker` is enabled and we make a query where we create the property (for the first time) and cardinality is `SET` or `LIST`, then we should explicitly define it for each added value (only for the first query). This change can be seen in modified tests. I didn't find any mentioned changes to cardinalities from `3.4.1` to `3.4.4`, so I can't say what causes this change.
Even so, the breaking change is very tiny and most likely nobody will be affected (because our documentation suggests to disable `Automatic Schema Maker`), I decided to make this TinkerPop update only for `master` branch, and not for `0.4` branch.
Testcontainers update is also required due to some conflicting …
=> Update to TinkerPop 3.4.4

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
Fix for https://github.com/JanusGraph/janusgraph/issues/1925
=> * Improve the CQLIterator performance by using getPagingStateUnsafe

janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/scan/HadoopVertexScanMapper.java
Signed-off-by: Ted Wilmes <ted.wilmes@experoinc.com>
-----
=> Issue #1871: Close graph instance at end of mapper run.

pom.xml
=> Bump jackson2.version from 2.6.6 to 2.10.2

janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/IDAuthorityTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/idmanagement/ConsistentKeyIDAuthority.java
This PR reduce awaiting of ids allocation for local storage
Partially fix for #1859 
-----
=> Await id block only for distributed stores

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-test/src/test/java/org/janusgraph/blueprints/process/traversal/strategy/optimization/JanusGraphStepStrategyTest.java
=> Copy labels during optimizing Or steps

pom.xml
Changelog: https://docs.datastax.com/en/developer/java-driver/3.8/changelog/
-----
=> Bump datastax cassandra driver to 3.8.0 [full build]

docs/changelog.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphPropertiesStep.java, mkdocs.yml, pom.xml
Fixes #1953
TinkerPop tests are executed with: `mvn clean install -Dtest.skip.tp=false -DskipTests=true`
All TP tests passed.
-----
=> Update Tinkerpop to 3.4.5

janusgraph-all/pom.xml, janusgraph-core/pom.xml, janusgraph-driver/pom.xml
=> Fix missing plugins javadoc and maven plugins for driver module

README.md
This simply adds our blog post series to the README.md to describe G DATA's use case for JanusGraph.
-----
- [-] Is there an issue associated with this PR? Is it referenced in the commit message?
- [-] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [-] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt …
=> Add G DATA use case blog post [doc only]

janusgraph-backend-testutils/pom.xml, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManager.java, janusgraph-server/pom.xml, janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManagerTest.java, pom.xml
=> Pass HadoopManager through MetricInstrumentedStoreManager

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategy.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategyTest.java
=> Optimize hasId() in the same way as is()

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
=> Improve lucene tokenizer

docs/changelog.md, mkdocs.yml, pom.xml
TinkerPop 3.4.6 is released: https://groups.google.com/forum/#!topic/gremlin-users/KwAQHlIBPYY
TinkerPop tests are executed with: `mvn clean install -Dtest.skip.tp=false -DskipTests=true`
All TP tests passed.
Fixes #1980
Suppresses: #1954 
-----
=> Update Tinkerpop to 3.4.6

janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
Signed-off-by: Vladimir Bogomolov <vladimir.bogomoloff@gmail.com>
-----
Resolve Issue #1971
-----
=> Add TEXTSTRING support for lucene index

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchScroll.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchScrollTest.java
If the entire scroll is read in the constructor the scroll was not deleted in ES.
Fixes #1985
Signed-off-by: Paul Kendall <pkendall64@gmail.com>
-----
=> Fix scroll leak in scroll handling.

janusgraph-backend-testutils/src/main/java/org/janusgraph/olap/OLAPTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreAdapter.java
KeyIteratorImpl may swallow some entries when vertices does not have any relations. And VertexJobConverter will be treat that entries as ghost vertices
-----
=> Fix kvstore iterator

docs/basics/schema.md, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/StandardPropertyKeyMaker.java
=> Emphasize that property key cannot be of primitive type [doc only]

pom.xml
=> Bump netty to 4.1.45

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java
=> Support range limit -1 in gremlin query

docs/index-management/index-performance.md
=> Remove outdated note about order  [doc only]

pom.xml
=> Bump junit to 5.5.2

janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-inmemory/src/test/java/org/janusgraph/graphdb/inmemory/InMemoryOLAPTest.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
=> Fix lucene docid tokenization

janusgraph-dist/pom.xml, janusgraph-dist/src/assembly/descriptor/common.component.xml, janusgraph-dist/src/assembly/static/bin/janusgraph.sh, janusgraph-dist/src/assembly/static/conf/es/jvm.options
=> Fix issues with release build tests

janusgraph-core/src/main/java/org/janusgraph/graphdb/log/StandardLogProcessorFramework.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/log/StandardLogProcessorFrameworkTest.java
Due to the stale #1742 PR I am opening a new PR to resolve requested changes. This PR is a copy paste of #1742 with resolved requested changes.
Fixes #1281
Suppresses #1742 
-----
=> Fix created logs are not added into processorLogs

docs/changelog.md, janusgraph-es/pom.xml, pom.xml
=> Bump ElasticSearch to 7.6.1

pom.xml
=> Bump jacoco to 0.8.5

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphBaseTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
=> Fix ElasticSearch scroll result is created even on no scroll CTR

docs/index-management/index-performance.md
=> Fix wrong example in index-performance.md [doc only]

RELEASING.md, docs/basics/configuration.md, docs/basics/server.md, docs/changelog.md, docs/getting-started/installation.md, janusgraph-dist/pom.xml, janusgraph-dist/src/assembly/descriptor/archive-full.xml, janusgraph-dist/src/assembly/descriptor/common-full.component.xml, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyESAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlESAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/GremlinShellArgsIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/JanusGraphScriptIT.java, janusgraph-dist/src/test/resources/target.properties
This pr will introduce a breaking change. Distribution package naming has changed.
-----
=> Support a full and small version of release zip

docs/getting-started/basic-usage.md, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-inmemory.properties
=> Add janusgraph-inmemory.properties and introduce in basic usage [doc only]

docs/changelog.md, docs/getting-started/installation.md, janusgraph-dist/src/assembly/static/bin/janusgraph.sh, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml
=> Fix gremlin-server should run inmemory by default

janusgraph-hbase-parent/janusgraph-hbase-server/pom.xml, pom.xml
=> Use requireUpperBoundDeps to ensure packages are aligned with deps

janusgraph-backend-testutils/src/main/java/org/janusgraph/olap/OLAPTest.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraGraphComputer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraVertexMemory.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexMemoryHandler.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexProgramScanJob.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexState.java
Add support for job without combiner - just combine message into list
Detach elements before it will be written into graph for avoid serialization issue
Now ConnectedComponentTest and ShortestPathVertexProgramTest passed
TP tests for `BerkeleyJanusGraphComputerTest` passed
Only two failed but on master too
```
WhereTest$Traversals
WhereTest$Traversals.g_V_hasXageX_asXaX_out_in_hasXageX_asXbX_selectXa_bX_whereXa_outXknowsX_bX
WhereTest$Traversals.g_V_asXaX_outXcreatedX_whereXasXaX_name_isXjoshXX_inXcreatedX_name
```
Possible cause is `PathProcessorStrategy` it generate random alias for step for each vertexJob iteration. If I setup [is.testing](https://github.com/apache/tinkerpop/blob/db363b53d8d6ea5d91c9a1f8f8159b8b8511d8c4/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/tra …
=> Fix some issues with FulgoraGraphComputer

janusgraph-all/pom.xml, janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java, janusgraph-dist/pom.xml, janusgraph-driver/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml, pom.xml
=> Update testcontainers and junit 5

janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexUpdateJob.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/database/IndexSerializerTest.java
* Changed the work block size to be storage.page-size ( this makes the
pagination code cleaner ) and also make work block configurable.
* Removed QUEUE_SIZE from Scanner, it now follows storage.page-size
* ProcessQueue size would be numWorkers * workBlockSize * numDataPullers
* Add info logs for every job iteration to see the index update metrics.
* Handle the `doc-updates` count accurately matching with actual
updates.
* Fix for https://github.com/JanusGraph/janusgraph/issues/1895
* Same changes as PR ( https://github.com/JanusGraph/janusgraph/pull/1898 )
----- …
=> Index repair improvements

docs/changelog.md, docs/connecting/java.md, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml, janusgraph-dist/src/assembly/static/conf/remote-graph-binary.yaml, janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Geo.java, janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Text.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistry.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/JanusGraphP.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GraphBinaryType.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphPBinarySerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphTypeSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/RelationIdentifierGraphBinarySerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModule.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleV2d0.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphSerializerBaseIT.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializerTest.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphPGraphBinarySerializerTest.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/RelationIdentifierGraphBinarySerializerTest.java
=> Add support for graph binary

README.md
=> Add janusgraph-dev Gitter room to README [doc only]

docs/changelog.md
Simple addition to the docs which separates between currently supported and unsupported versions. Solves #2011 
-----
=> Track End-of-Life versions

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
The CQL storage adapter currently parses results retrieved from the backend into an array from which they are further evaluated by some method outside the storage adapter.
https://github.com/JanusGraph/janusgraph/blob/db8bcb1c43c1f500d71a71d7f0666c6f9a03917c/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java#L318
This structure causes a huge overhead, because all data is now stored both in the ResultSet and in the ArrayList. Instead, we can use a custom Iterator which wraps the `ResultSet`'s iterator and returns the results one-by-one when needed.
This improvement has a massive impact on the performance of all range reads on CQL backends:
For both implementations, counting the neighbors of a vertex serves as a query resulting in a large range read. For …
=> Remove redundant data structure in CQL adapter

docs/index-management/index-performance.md
Resolves #1935
I've added a section to the documentation to explain the usage of vertex-centric indexes on implicit keys like IDs. Are there any ideas for further improvements?
=> Explain usage of implicit keys for vertex-centric indexes

janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/SliceQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/EntryArrayList.java
allow to avoid data copying
https://github.com/JanusGraph/janusgraph/issues/1719
=> EntryArrayList instead of StaticArrayEntryList 

pom.xml
Changelog: https://docs.datastax.com/en/developer/java-driver/3.9/changelog/
-----
=> Bump datastax cassandra driver to 3.9.0 [full build]

docs/changelog.md, janusgraph-es/pom.xml, pom.xml
=> Bump ElasticSearch to 7.6.2

README.md
They were acquired by Netskope and Netskope is not using JanusGraph.
Fixes #2113
cc @rcanzanese
-----
=> Remove user Sift Security [doc only]

janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/time/TimestampProviders.java
=> Fix TimestampProviders precision

janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java, janusgraph-dist/src/assembly/static/bin/gremlin-server.sh, janusgraph-dist/src/test/expect/gremlin-server-sh.after.expect.vm, janusgraph-dist/src/test/expect/gremlin-server-sh.before.expect.vm, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyESAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlESAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/InMemoryAssemblyIT.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
=> Add testing for gremlin-server.sh

.travis.yml, janusgraph-server/conf/janusgraph-server-integration.properties, janusgraph-server/pom.xml, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphChannelizerTest.java
=> Reactivate server tests

README.md
Please let me know if this should be based on `master` instead since this only affects the README, and the release branches aren't the default views on the GitHub repo landing page, nor are these changes pushed to https://docs.janusgraph.org .
-----
- [/] Is there an issue associated with this PR? Is it referenced in the commit message?
- [/] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [/] Have you written and/or updated unit tests to verify your changes?
- [/] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …
=> Added "Graph Explorer" for visualization [skip ci]

docs/basics/multi-node.md, docs/connecting/dotnet.md, docs/connecting/java.md, docs/connecting/python.md, janusgraph-dist/src/assembly/static/conf/remote-graph.properties, janusgraph-examples/example-remotegraph/src/main/java/org/janusgraph/example/RemoteGraphApp.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphChannelizerTest.java
=> Replace EmptyGraph with AnonymousTraversalSource if possible

docs/advanced-topics/bulk-loading.md, docs/basics/server.md, docs/index-backend/elasticsearch.md, docs/index-backend/solr.md, docs/index.md, docs/storage-backend/cassandra.md, docs/storage-backend/hbase.md, janusgraph-examples/example-cql/README.md
=> Fix broken links [doc only]

janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/JanusGraphVertexDeserializer.java, janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/hadoop/HBaseSnapshotInputFormatIT.java
Refactored properties decoding step to apply it for both edge properties and meta-properties.
Fixes #1996 
Signed-off-by: Evgeniy.Ignatiev <yevgeniy.ignatyev@gmail.com>
-----
=> JANUSGRAPH-1996 Decode meta-properties in Hadoop vertex deserializer

docs/basics/janusgraph-cfg.md, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/util/ConnectionKeepAliveConfigCallback.java
-----
Use custom Keep-Alive strategy for ES rest client.
Fixes #2167
=> Use custom keep alive strategy for ES client

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexOptimizerStrategy.java
=> Include step labels in optimized queries

janusgraph-server/pom.xml, pom.xml
=> Bump guava 29.0-jre [full build]

NOTICE.txt, pom.xml
=> Bump junit and testcontainers and drop some packages

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
The test case builds a mixed index using TEXT mapping, but uses
equality condition in query (which does not use this mixed
index). This makes one assertion does not work as expected, and
as a consequence, passes the test by chance. This commit fixes the
mixed index usage and the assertion to uncover the real problem.
Related to #2176
**Note that this does not fix the problem stated in #2176, but fix the
flaky test itself to uncover the problem.**
-----
Please ensure that once the PR is …
=> Fix testNestedWrites testcase in JanusGraphIndexTest

janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayBuffer.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayEntry.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/BufferUtilTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/StaticArrayBufferTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/StaticArrayEntryTest.java
=> Refactor toString on StaticArrayBuffer

docs/advanced-topics/monitoring.md, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml, janusgraph-hbase-parent/common/test/conf/hadoop-metrics.properties, janusgraph-server/src/test/resources/janusgraph-server-with-serializers.yaml, janusgraph-server/src/test/resources/janusgraph-server-without-serializers.yaml
Signed-off-by: Paul Sin <jiyoungsin97@gmail.com>
-----
- [2230] Is there an issue associated with this PR? Is it referenced in the commit message?
- [YES] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [YES] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [YES] Is your initial contribution a single, squashed commit?
Please ensure that once the PR is submitted, you check Travis CI for build issues and …
=> fixed 2230 [docs only]

docs/advanced-topics/data-model.md
=> Fix wrong link in data-model doc [doc only]

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphVertexProperty.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheEdge.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheVertexProperty.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/StandardEdge.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/StandardVertexProperty.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
This commit includes fixes for three bugs:
1) Caused by the optimization in StandardJanusGraphTx::addProperty, which saves a database
read (and delete) operation for vertex property upsert. If a vertex property (or the vertex
as a whole) is removed after the property is modified in the same transaction, then the old
value in database will not be deleted after the transaction commits. Reported by #1981.
2) Caused by CacheVertexProperty::remove method which does nothing if it finds the given
vertex property is already in the deletedRelations map. If the user deletes a vertex property
after they update a nested property of that vertex property in the same transaction, then
the old value will be removed from database but the new value will be saved into database
after the transaction commits. …
=> Bug fixes: relations cannot be removed after update

janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/StaticArrayEntryTest.java
=> Fix StaticArrayEntryTest.testToStringWithNoValue hex long leading zero flaky test

.github/workflows/ci-docs.yml
=> Fix changes on master branch [doc only]

.travis.yml, docs.Dockerfile, docs/changelog.md, mkdocs.yml, requirements.txt
=> Remove doc build from travis and update dockerfiles [doc only]

docs/changelog.md, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/DeprecatedJanusGraphPSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistry.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryV1d0.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModule.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleV2d0.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryTest.java
Follow up for #2061 to reduce breaking changes between version 0.5 and 0.6.
-----
=> Add serializiation fallback for older janusgraph drivers

README.md
=> Add eBay to production users

.github/workflows/ci-release.yml
=> Improve tp-tests running behavior [tp-tests]

docs/changelog.md, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java, janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml, mkdocs.yml, pom.xml
All TP tests passed with `mvn clean install -Dtest.skip.tp=false -DskipTests=true`
-----
=> Update TinkerPop to 3.4.9 [tp-tests]

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
Changes in this PR will be ignored in `master` branch because this *potential* bug is fixed in `master` branch.
In the issue I described why it is hard to confirm and test this bug. This PR either fixes a *potential* bug or does nothing (lets say just refactors the code).
Fixes #2254
-----
=> Use available page size for CQL result set instead of forced page size [full build]

janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiIterator.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/util/MultiIteratorTest.java
=> Refactor MultiIterator to reduce iteration cycles

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es.yml, .travis.yml, CONTRIBUTING.md, TESTING.md, janusgraph-all/pom.xml, janusgraph-all/src/test/java/org/janusgraph/core/EnsureCacheTest.java, janusgraph-all/src/test/resources/log4j.properties, janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyGraphTest.java, janusgraph-cql/pom.xml, janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLDistributedStoreManagerTest.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java, janusgraph-driver/pom.xml, janusgraph-es/pom.xml
Part of #2260 
ToDo:
* Move solr tests to github actions
* Create ticket for berkeleyje and cql tests
-----
=> Move most test to GitHub Actions

.codecov.yml
=> Activate codecov in PRs

README.md
=> Update Readme.md with new visualization tool [doc only]

.codecov.yml
=> Codecov should notify after 30 reports

janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/BufferPage.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/BufferPageUtils.java, janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/BufferPageTest.java
to allow for Entry keys of arbitrary length, while not incurring unnecessary overhead (as 99% of keys are typically quite short)
-----
=> issue #2273 - implement variable length "valuePosition" in page storage

README.md
=> Compose no longer supports JanusGraph

README.md
=> Update mailing lists to LF AI & Data

README.md
=> Add JanusGraph LinkedIn link

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/QueryInfo.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java
Rewrite the method to reduce NPath complexity
This was part of https://github.com/JanusGraph/janusgraph/pull/2289 to satisfy Codacy.
-----
=> Refactor JanusGraphStep::buildGlobalGraphCentricQuery

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/BerkeleyElasticsearchTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchJanusGraphIndexTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/BerkeleySolrTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/CQLSolrTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/JanusGraphSolrContainer.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java
=> Add test for multiple index backends

janusgraph-dist/pom.xml, janusgraph-driver/pom.xml, pom.xml
* Remove shading
* Remove bunch of maven plugins
* Remove bunch of unsed dependencies
* Bump maven version requirement
-----
=> Cleanup maven

docs/changelog.md, janusgraph-es/pom.xml
=> Update ElasticSearch tested compatibility to 7.10.2

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-server/pom.xml, janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphServer.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/server/utils/GremlinSettingsUtils.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphServerTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/utils/GremlinSettingsUtilsTest.java, janusgraph-server/src/test/resources/conf/janusgraph-inmemory.properties, janusgraph-server/src/test/resources/invalid-config.yaml, janusgraph-server/src/test/resources/janusgraph-server-with-serializers.yaml, janusgraph-server/src/test/resources/janusgraph-server-without-serializers.yaml, janusgraph-server/src/test/resources/org/janusgraph/graphdb/tinkerpop/gremlin-server-integration.yaml
Part of #1853, #2119
* Rework JanusGraphServer
* Add tests for JanusGraphServer
* Some cleanup on server section
* Rename JanusGraphSettingsUtils to GremlinSettingsUtils
-----
=> Refactor JanusGraphServer in preperation for a GRPC server

docs/changelog.md, mkdocs.yml, pom.xml
=> Update TinkerPop to 3.4.10 [tp-tests]

janusgraph-dist/pom.xml, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyESAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlESAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/GraphOfTheGodsCompatIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/GremlinShellArgsIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/InMemoryAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/JanusGraphAssemblyBaseIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/JanusGraphScriptIT.java
* Split up AbstractJanusGraphAssemblyIT into a generic class for all release tests and suite for default backend tests
* activate single vertex tests
* centralized naming in pom.xml for zip names
-----
=> Refactor dist tests

janusgraph-server/pom.xml
=> Add missing test dependency on janusgraph-inmemory

TESTING.md, docs/changelog.md, janusgraph-cql/pom.xml, janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java, janusgraph-cql/src/test/resources/docker/docker-compose.yml, pom.xml
=> Bump cassandra

docs/schema/index-management/index-performance.md
1. Explain where composite indexes and vertex-centric indexes are stored
2. Introduce the usage of property index which is missing in the doc
-----
=> [Docs] Enhance indexing documentation

docs/configs/janusgraph-cfg.md, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java
Addresses: Issue 2445
Signed-off-by: Ted Wilmes <ted.wilmes@experoinc.com>
-----
=> Issue 2445: Expose ES rest client connect and socket timeout config options

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/AddedRelationsContainer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/SimpleAddedRelations.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/indexcache/ConcurrentIndexCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/indexcache/IndexCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/indexcache/SimpleIndexCache.java
=> Release memory when releasing transaction

janusgraph-hbase-parent/janusgraph-hbase-server/pom.xml
See https://issues.apache.org/jira/browse/JCR-4626 and https://stackoverflow.com/questions/51403167/repository-version-policy-ignore-missing-poms for the same problem.
-----
=> Fix CI build failure by specifying javax.el version

janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
Follow-up of #2413
Related to #2412
-----
=> Avoid explicit memory clean up when releasing transaction

docs/operations/monitoring.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/IndexMetricTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/MetricInstrumentedIndexProvider.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StorageRunnable.java, janusgraph-lucene/src/test/java/org/janusgraph/graphdb/BerkeleyLuceneIndexMetricTest.java
Currently index provider does not have metrics, so this PR will add them
-----
=> Add metric to index provider

janusgraph-core/src/main/java/org/janusgraph/diskstorage/common/LocalStoreManager.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/KeySelector.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/validator/CompatibilityValidator.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/placement/PartitionIDRange.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/IntegerSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/ShortSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/ElementLifeCycle.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/management/ConfigurationManagementGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/ConditionUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BaseVertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/StandardRelationTypeMaker.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/TypeDefinitionMap.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/IndexHelper.java, janusgraph-driver/src/main/java/org/janusgraph/util/encoding/LongEncoding.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/HMACAuthenticator.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/JanusGraphAbstractAuthenticator.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
Avoid string concatenation in runtime
-----
=> Fix precondition checks

janusgraph-core/src/main/java/org/janusgraph/diskstorage/BackendTransaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/AbstractConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/TransactionalConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/EdgeSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementLogger.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/ElementCategory.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaElementDefinition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/StandardVertex.java, janusgraph-core/src/main/java/org/janusgraph/util/datastructures/ArraysUtil.java, janusgraph-core/src/main/java/org/janusgraph/util/stats/NumberUtil.java
Inspired by https://github.com/JanusGraph/janusgraph/discussions/2487 where the stack trace only gives exception type, but no error message.
-----
=> Add error message to Preconditions checks

docs/schema/index-management/index-performance.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
Related to https://lists.lfaidata.foundation/g/janusgraph-users/message/5611
-----
=> Add Management API to retrieve indexOnly constraint

janusgraph-core/src/main/java/org/janusgraph/graphdb/idmanagement/UniqueInstanceIdRetriever.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/UniqueInstanceIdRetrieverConcurrencyTest.java
=> Fix race condition of UniqueInstanceIdRetriever

docs/configs/janusgraph-cfg.md, docs/index-backend/elasticsearch.md, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
=> [Docs] Improve doc for Elasticsearch authentication

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java
- Fix to avoid index corruption after reindexing RelationTypeIndex with direction IN or BOTH
- While reindexing RelationTypeIndex, edges are created according to the position of relation arity
Steps to reproduce to the self-link issue:
1) Create an Edge label (Assume name is 'link')
2) Create  an property key (Assume name is 'assockind
3) Build an 'Edge Index' by label 'link' and property key 'assockind' with Direction 'IN' or 'BOTH'
4) Create two vertices(let us call it A, B) and add a edge between A and B with label 'link' and some random value (Example : 1) for the property key 'assockind'
5) Query for all the IN edges of vertex A. Make sure the query uses the edge index. This will give no result as there is no IN edge for vertex A
g.V().has('name' , …
=> Graph Reindexing Issue Fix

docs/changelog.md, janusgraph-cql/pom.xml, pom.xml
=> Upgrade DataStax cassandra driver to 4.11.0

docs/changelog.md, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java, pom.xml
=> Update ElasticSearch to 7.12.0

janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/EdgeLabelDefinition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/PropertyKeyDefinition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/RelationTypeDefinition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaContainer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaElementDefinition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaProvider.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/VertexLabelDefinition.java
=> Deprecated org.janusgraph.graphdb.schema

janusgraph-grpc/README.md, janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java, janusgraph-grpc/src/main/proto/janusgraph/schema/v1/schema_manager.proto, janusgraph-grpc/src/main/proto/janusgraph/types/v1/schema_types.proto, janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerImpl.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerProvider.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/util/GrpcUtils.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphGrpcServerBaseTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClientTest.java
Part of #1853
* Support get edgeLabel by name
* Add readme with a current state
* Move grpc util into a extra class
* Small breaking in protos
-----
=> Add GetEdgeLabelByName

janusgraph-cql/src/test/resources/cql-read.properties
=> Fixes sparkDriver port binding issue

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-java-11.yml, docs/changelog.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-dist/pom.xml, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlESAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/GremlinShellArgsIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/TestCategory.java, pom.xml
Part of #1361
Duplicate a bunch of tests for java 11. It just a start.
-----
=> Add exprimental support for java 11

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
=> Fix profiler timing for fullscan

pom.xml
Due to high severity risks in older versions: https://github.com/advisories/GHSA-p66x-2cv9-qq3v and https://github.com/advisories/GHSA-6phf-73q6-gh87
-----
=> Bump commons-beanutils from 1.8.3 to 1.9.4

docs/operations/cache.md
Related to https://lists.lfaidata.foundation/g/janusgraph-users/topic/82438772
-----
=> [docs] Explain cache mechanism in more detail

janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
=> Remove duplicate addProperty calls in StandardJanusGraphTx:: makeSchemaVertex

docs/changelog.md
This is a follow-up of https://github.com/JanusGraph/janusgraph/pull/2619
-----
=> changelog: Update tinkerpop compatibility matrix

janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphServer.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphSettings.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/server/util/JanusGraphSettingsUtils.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphServerTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphSettingsTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/util/JanusGraphSettingsUtilsTest.java
Follow up of upgrading to tp 3.5
-----
=> Cleanup JanusGraphSettings

pom.xml
=> Update spatial4j to version 0.8

docs/changelog.md, janusgraph-solr/pom.xml, pom.xml
=> Update solr to 8.6.3

docs/schema/index.md
=> [Docs] Explain data type inference in auto schema maker

docs/changelog.md, pom.xml
Changelog: https://docs.datastax.com/en/developer/java-driver/4.12/changelog/
-----
=> Bump DataStax Cassandra Driver to 4.12.0

docs/changelog.md, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java, pom.xml
=> Bump Elasticsearch to 7.13.2

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/HasStepFolder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
Related to: https://github.com/JanusGraph/janusgraph/pull/2660#discussion_r650742639
-----
=> Optimize hasContainers addition by ensuring correct size

RELEASING.md, docs/changelog.md, janusgraph-all/pom.xml, janusgraph-backend-testutils/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-bigtable/pom.xml, janusgraph-core/pom.xml, janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-driver/pom.xml, janusgraph-es/pom.xml, janusgraph-examples/example-berkeleyje/pom.xml, janusgraph-examples/example-common/pom.xml, janusgraph-examples/example-cql/pom.xml, janusgraph-examples/example-hbase/pom.xml, janusgraph-examples/example-remotegraph/pom.xml, janusgraph-examples/example-tinkergraph/pom.xml, janusgraph-examples/pom.xml, janusgraph-grpc/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-hbase/pom.xml, janusgraph-inmemory/pom.xml, janusgraph-lucene/pom.xml, janusgraph-server/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, pom.xml
=> JanusGraph release v0.6.0 [cql-tests] [tp-tests]

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/AbstractIndexSelectionStrategy.java
=> Reduce redundant global centric query build

docs/changelog.md, janusgraph-solr/pom.xml, pom.xml
Signed-off-by: Oleksandr Porunov <alex@mapped.com>
-----
=> Update Solr to 8.9.0

janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/JanusGraphVertexDeserializer.java, janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java, janusgraph-hbase/src/test/java/org/janusgraph/hadoop/HBaseSnapshotInputFormatIT.java
=> Fix deserializing multiple self-loop edges

docs/configs/janusgraph-cfg.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/GraphDatabaseConfigurationInstanceIdTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
=> Make thread pool size configurable for parallel backend queries

docs/configs/janusgraph-cfg.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
=> Change CQL connections configurations to be MASKABLE instead of FIXED

janusgraph-backend-testutils/src/main/java/org/janusgraph/core/AbstractConfiguredGraphFactoryTest.java, janusgraph-core/src/main/java/org/janusgraph/core/ConfiguredGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/management/ConfigurationManagementGraph.java
=> Do not retrieve other configuration properties when retrieving graph names only

SECURITY.md
=> Add security vulnerabilities report documentation

.github/FUNDING.yml
=> Add funding option

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
This tests that once a new property is added to an existing mixed index
in one graph instance, other graph instances can receive the broadcast message
and expire the stale schema cache.
Continuation of #2699
-----
=> Test graph interactions in shouldUpdateIndexFieldsAfterIndexModification

README.md
=> Add Codacy code quality badge

docs/advanced-topics/executor-service.md, docs/configs/janusgraph-cfg.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/GraphDatabaseConfigurationInstanceExecutorServiceTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/GraphDatabaseConfigurationInstanceIdTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/Configuration.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/ExecutorServiceBuilder.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/ExecutorServiceConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java, janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/InmemoryGraphDatabaseConfigurationInstanceExecutorServiceTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/CustomTestExecutorService.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/ExecutorServiceBuilderTest.java, mkdocs.yml
=> Add configuration options for ExecutorService

docs/changelog.md, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphTraversalUtil.java, mkdocs.yml, pom.xml
=> Update TinkerPop to 3.5.1 [cql-tests] [tp-tests]

janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/JanusGraphSolrContainer.java, pom.xml
=> Update Testcontainers to 1.16.0

README.md
Adding Credit Agricole CIB to the list of production users.
=> Add Credit Agricole to list of production users.

janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/BackendTest.java
=> Name Backend Threads

docs/changelog.md, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java, pom.xml
=> Bump Elasticsearch to 7.14.0

docs/changelog.md, pom.xml
Changelog: https://docs.datastax.com/en/developer/java-driver/4.13/changelog/
-----
=> Bump DataStax Cassandra Driver to 4.13.0

janusgraph-lucene/pom.xml
Fixes the issue described here: https://lists.lfaidata.foundation/g/janusgraph-users/topic/janusgraph_0_6_0/84942966
-----
=> Add lucene codecs for older Lucene versions for compatibility

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java
This is a wild guess fix. Review is definitely needed.
For additional checks, I enabled multi query on almost all tests and started additional TP and CQL tests: https://github.com/porunov/janusgraph/runs/3364841140 ([branch](https://github.com/porunov/janusgraph/tree/test/test-multiquery-fix))
I also started the same tests as in the previous PR but without this fix (it will help us to compare which failing tests we should or should not care about):
https://github.com/porunov/janusgraph/runs/3365174113 ([branch](https://github.com/porunov/janusgraph/tree/test/test-multiquery-without-fix))
Most likely, some tests will fail in case they are checking  explicitly the behavior of disabled multi queries but tests which have no such checking logic should pass. Will see after CI finishes.
Fixes …
=> Fix adjacent vertices removal with enabled multi query after where step

janusgraph-hbase/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java, janusgraph-hbase/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerConfigTest.java
Signed-off-by: jigs1993 <jigar.9408266552@gmail.com>
discussion thread: https://lists.lfaidata.foundation/g/janusgraph-users/message/6065
ISSUE: https://github.com/JanusGraph/janusgraph/issues/2746
-----
=> honoring skip-schema-check for hbase

janusgraph-cql/pom.xml, pom.xml
=> Upgrade slf4j and logback

janusgraph-benchmark/src/main/java/org/janusgraph/GraphCentricQueryBenchmark.java, janusgraph-test/pom.xml
=> Move GraphCentricQueryBenchmark to janusgraph-benchmark module

janusgraph-dist/src/assembly/static/bin/gremlin-server.bat, janusgraph-dist/src/assembly/static/bin/gremlin.bat
=> Fix deprecated winutils.exe link

janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh, janusgraph-dist/src/assembly/static/conf/jvm-11.options, janusgraph-dist/src/assembly/static/conf/jvm-8.options, janusgraph-dist/src/test/expect/janusgraph-server-sh.after.expect.vm, janusgraph-dist/src/test/expect/janusgraph-server-sh.before.expect.vm, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/JanusGraphAssemblyBaseIT.java
=> Add config printer to janusgraph-server.sh

docs/storage-backend/cassandra.md
Add Astra to Cassandra Backends docs page: https://docs.janusgraph.org/storage-backend/cassandra/
Fixes #2879  
-----
=> Add Astra to Cassandra Backends docs page (#2879)

docs/schema/index-management/index-reindexing.md, docs/schema/index-management/index-removal.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-benchmark/src/main/java/org/janusgraph/MgmtOlapJobBenchmark.java, janusgraph-benchmark/src/main/resources/log4j.properties, janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
ManagementSystem uses an local executor service to run reindex and index removal
processes, available via ManagementSystem::updateIndex method. Unfortunately, it
only uses one thread which is inefficient. This commit changes the default concurrency
level from one to the number of available processors, which is fetched in runtime.
This commit also adds a new API for updateIndex which allows users to configure the
concurrency level, i.e. number of threads to run the job concurrently.
This commit comes along with a benchmark program. Benchmarking result on a 6-core
MacBook Pro (2019) is as follows:
```
Benchmark(multi-threaded)           (size)  Mode  Cnt    Score    Error  Units
MgmtOlapJobBenchmark.runReindex       10000  avgt    3  174.800 ± 74.395  ms/op …
```
=> Add concurrency level config in ManagementSystem::updateIndex

janusgraph-test/src/test/java/org/janusgraph/diskstorage/common/LocalStoreManagerTest.java
-----
- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
=> Unix style directory path usage in tests makes build fail on Windows #2887

janusgraph-core/pom.xml, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/cache/StandardSchemaCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraVertexMemory.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/vertexcache/GuavaVertexCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/ConcurrentLRUCache.java, pom.xml
=> #2900 Replace high-scale-lib with jctools-core to fix Eclipse errors

docs/changelog.md, docs/interactions/search-predicates.md, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinaryConstants.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/BoxSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/CircleSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/GeometryCollectionSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/GeoshapeTypeSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/LineSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/MultiLineSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/MultiPointSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/MultiPolygonSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/PointCollectionSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/PointSerializer.java, janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/PolygonSerializer.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializerTest.java
This makes it much easier to support GraphBinary outside of Java. It also reduces the payload size by a factor of 3 to 4 (taken from the examples used in the tests):
| Geoshape type      | Payload size (B) with previous serialization | Payload size (in B) with new serialization | Relation (new / old) |
|--------------------|----------------------------------------------|--------------------------------------------|----------------------|
| Point              | 73                                           | 22                                         | 30.1%                |
| Circle             | 105                                          | 30                                         | 28.6%                |
| Polygon            | 373                                          | 90 …
=> Implement our own GraphBinary Geoshape serialization

janusgraph-test/src/test/java/org/janusgraph/diskstorage/cache/ExpirationCacheTest.java
=> Mark cache expiration test as flaky

docs/changelog.md, docs/index-backend/direct-index-query.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphIndexQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexTransaction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/IndexQueryBuilder.java, janusgraph-hadoop/src/test/resources/org/janusgraph/hadoop/formats/graphson/incremental-custom-cerberus-load.groovy, janusgraph-hadoop/src/test/resources/org/janusgraph/hadoop/formats/graphson/incremental-load.groovy, janusgraph-hadoop/src/test/resources/org/janusgraph/hadoop/formats/graphson/incremental-naive-cerberus-load.groovy
=> Remove deprecated no stream methods

docs/changelog.md, janusgraph-all/pom.xml, janusgraph-backend-testutils/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-bigtable/pom.xml, janusgraph-core/pom.xml, janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-driver/pom.xml, janusgraph-es/pom.xml, janusgraph-examples/example-berkeleyje/pom.xml, janusgraph-examples/example-common/pom.xml, janusgraph-examples/example-cql/pom.xml, janusgraph-examples/example-hbase/pom.xml, janusgraph-examples/example-remotegraph/pom.xml, janusgraph-examples/example-tinkergraph/pom.xml, janusgraph-examples/pom.xml, janusgraph-grpc/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-hbase/pom.xml, janusgraph-inmemory/pom.xml, janusgraph-lucene/pom.xml, janusgraph-server/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, mkdocs.yml, pom.xml
=> JanusGraph release 0.6.1 [cql-tests] [tp-tests]

docs/storage-backend/cassandra.md
Fixing [#2945](https://github.com/JanusGraph/janusgraph/issues/2945)
Signed-off-by: Kathiresan Selvaraj <kathiresan.selvaraj@datastax.com>
-----
=> Astra DB configuration doc update

.github/workflows/ci-index-solr.yml, TESTING.md, docs/changelog.md, janusgraph-dist/src/assembly/static/conf/solr/solrconfig.xml, janusgraph-solr/pom.xml, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/JanusGraphSolrContainer.java, janusgraph-solr/src/test/resources/solr/core-template/solrconfig.xml, pom.xml
=> Disable solr 7 and upgrade lucene 8.11.1

janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
-----
Improvements in janusgraph-server.sh Java version checker
https://github.com/JanusGraph/janusgraph/issues/2974
=> Improvements in janusgraph-server.sh Java version checker

README.md
=> Update cambridge intelligence links to visualization tools

.github/workflows/lint-proto.yml, janusgraph-grpc/src/main/proto/janusgraph/types/v1/schema_types.proto, janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/util/GrpcUtils.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphGrpcServerBaseTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClientTest.java
=> Add basic vertex property support for grpc

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLSessionBuilder.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java
=> Fix fallback CQL configuration options are overwritten by default CQL values

janusgraph-grpc/src/main/proto/janusgraph/types/v1/schema_types.proto, janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/util/GrpcUtils.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphGrpcServerBaseTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClientTest.java
=> Add basic edge property support for grpc

janusgraph-grpc/src/main/proto/janusgraph/types/v1/schema_types.proto, janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/util/GrpcUtils.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphGrpcServerBaseTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClientTest.java
=> Use any type instead of long value

janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/MultiSlicesQuery.java
fixes https://github.com/JanusGraph/janusgraph/issues/3029
Signed-off-by: kptfh <sergiy.karpenko@gmail.com>
-----
=> Add getter to MultiSlicesQuery

docs/changelog.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraMemory.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/PredicateCondition.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BaseVertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/AbstractTypedRelation.java, janusgraph-solr/pom.xml, mkdocs.yml, pom.xml
Fixes #2997
The code changes where necessary because of TINKERPOP-2605 which allows `null` as an argument in more places.
The changes to `FulgoraMemory` are basically the same changes that were done in TinkerPop for `TinkerMemory`:
https://github.com/apache/tinkerpop/pull/1471/files#diff-876c2aa792d2cde263913b85027dd772050f9b99bb0a2d53ad8d8be38e073f13
-----
=> Update TinkerPop to 3.5.3

janusgraph-dist/pom.xml, janusgraph-dist/src/assembly/static/bin/janusgraph.sh, pom.xml
=> fix dist build

docs/configs/janusgraph-cfg.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLProgrammaticConfigurationLoaderBuilder.java
=> Don't set CQL NETTY_{ADMIN,IO}_SIZE by default

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphStepStrategy.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
=> Fix range and ordering for has id query [cql-tests] [tp-tests]

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java
=> Fix key consistent config for user config [cql-tests] [tp-tests]

.github/workflows/ci-benchmark.yml, .github/workflows/ci-release.yml, janusgraph-benchmark/src/main/java/org/janusgraph/BenchmarkRunner.java, janusgraph-benchmark/src/main/java/org/janusgraph/JanusGraphSpeedBenchmark.java
This commit adds github-action-benchmark which
can report performance change between current
commit and previous commit.
-----
=> Report benchmark performance per Pull Request

docs/schema/index-management/index-performance.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
Also adds a test to demonstrate the difference.
-----
=> Doc: Explain indexing with partial fields present

.github/ISSUE_TEMPLATE/bug-report.md, README.md
This justs adds Discord as an alternative to Gitter. We can later remove Gitter if we think that user / contributor experience is better on Discord.
Fixes #3083
-----
=> Add pointer to Discord Server

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java
- add test
- add fix when empty vertices to prefetch
Closes #3081
-----
=> [janusgraph-core] fixes properties step in multi-query

pom.xml
Fixes #3027
I think a better fix should be in the TinkerPop repository, but this PR provides a workaround.
-----
=> Fix gremlin version in console

pom.xml
=> Bump logback-classic from 1.2.7 to 1.2.11

docs/changelog.md, janusgraph-solr/pom.xml, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/JanusGraphSolrContainer.java, pom.xml
Backport #3122, #3130, #3093, #3121, #3089, #2874, #2881
-----
=> Upgrade TinkerPop to 3.5.4 and bump security related dependencies

janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexTest.java, janusgraph-solr/src/test/resources/solr/core-template/schema.xml
Signed-off-by: Vladimir Bogomolov <vladimir.bogomoloff@gmail.com>
-----
Resolve Issue #328
-----
=> Add TEXTSTRING support to solr index

docs/changelog.md, docs/interactions/connecting/java.md, docs/operations/dynamic-graphs.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIoTest.java, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-hbase-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-hbase.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml, janusgraph-dist/src/assembly/static/conf/remote-objects.yaml, janusgraph-dist/src/assembly/static/conf/remote.yaml, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java, janusgraph-driver/src/test/java/org/janusgraph/core/JanusGraphContainer.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryTest.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphBinaryModuleIT.java, janusgraph-examples/example-remotegraph/conf/remote-objects.yaml, janusgraph-server/src/main/java/org/janusgraph/graphdb/server/util/JanusGraphSettingsUtils.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphServerTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphSettingsTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/util/JanusGraphSettingsUtilsTest.java, janusgraph-server/src/test/resources/janusgraph-server-integration.yaml, janusgraph-server/src/test/resources/janusgraph-server-with-grpc.yaml, janusgraph-server/src/test/resources/janusgraph-server-with-serializers.yaml
=> Remove GryoMessageSerializerV3d0

janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLMutateManyFunctionBuilder.java, pom.xml
=> Update dropwizard.metrics to 4.2.12

pom.xml
=> Update snakeyaml 1.32

janusgraph-dist/pom.xml, pom.xml
=> Update velocity to 2.3

janusgraph-test/src/test/java/org/janusgraph/graphdb/database/IndexSerializerTest.java
=> Fix test error with mockito

TESTING.md, docs/changelog.md, janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-hbase/docker/Dockerfile, janusgraph-hbase/docker/entrypoint.sh, janusgraph-hbase/docker/hbase-site.xml, janusgraph-hbase/pom.xml, janusgraph-hbase/src/test/java/org/janusgraph/HBaseContainer.java, janusgraph-hbase/src/test/resources/log4j2-test.xml, janusgraph-solr/pom.xml, pom.xml
Fixes #2994
* Cleanup pom.xml
* Reduce log level of hbase tests
* Fix order in TESTING.md
* Fix zookeeper behavior in docker container
-----
=> Bump HBase 2.5 and Hadoop 2.10

docs/changelog.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/IndexMetricTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/TestMockIndexProvider.java, janusgraph-core/src/main/java/org/janusgraph/core/MixedIndexAggQuery.java, janusgraph-core/src/main/java/org/janusgraph/core/Transaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/BackendTransaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexProvider.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexTransaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/MetricInstrumentedIndexProvider.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MixedIndexAggQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/Aggregation.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphMixedIndexAggStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AbstractJanusGraphMixedIndexAggStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphMixedIndexAggStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphMixedIndexCountStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestAggResponse.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestAggResult.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestAggValue.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/SumCollector.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
=> Implement mixed index aggregations

.backportrc.json, .github/workflows/backport.yml
Part of #3247
To start a backport, we need to labels `backport` and the `backport/{branch}`.
-----
=> add backport action

.github/dependabot.yml
=> change dependabot for backport

janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-dist/src/assembly/static/bin/gremlin.bat, janusgraph-dist/src/assembly/static/bin/gremlin.sh, janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh, janusgraph-dist/src/assembly/static/conf/log4j2-console.xml, janusgraph-dist/src/assembly/static/conf/log4j2-server.xml, janusgraph-dist/src/test/log4j2-test.xml, janusgraph-hadoop/pom.xml, janusgraph-hbase/pom.xml, pom.xml
=> Cleanup log dependency

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-benchmark.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml, .github/workflows/ci-release.yml, .github/workflows/lint-proto.yml
=> build dependabot branches once

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexFilterOptimizerStrategy.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategyTest.java
=> Skip steps with step labels in AdjacentVertexFilterOptimizerStrategy

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
Changed test `testStaleIndexForceRemoveVertexFromGraphIndexByHelperMethod` to be a parameterized test which checks composite index force record removal with index vertex label constraint and without. 
Related to #1099 and #3022
-----
=> Test stale composite index force record removal works with indexOnly constraint

pom.xml
These dependencies need to be updated together, but I unfortunately don't see a way to let Dependabot update them always together. So, it seems like we have to do it manually.
-----
=> Bump test dependencies (JUnit & Mockito)

janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctOrderedIterator.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctUnorderedIterator.java
=> Do not store distinct elements when single iterator processed

docs/changelog.md
Fixes #3371
We can add it back there as soon as we have some automated tests in place: #415
-----
=> Remove Bigtable as tested compatibility

.backportrc.json, .github/dependabot.yml, .github/workflows/backport.yml
=> refactor backport

janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/RelationIdentifierGraphBinarySerializer.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphSerializerBaseIT.java
=> RelationIdentifierGraphBinarySerializer: Fix property serialization

docs/getting-started/installation.md
There are a few wording that could be confusing to newcomers. This commit fixes them and also add a warning on usage of ARM containers.
-----
=> Improve docker section in installation guide

janusgraph-benchmark/src/main/java/org/janusgraph/MgmtOlapJobBenchmark.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/SchemaAction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRemoveJob.java
See [this discussion](https://github.com/JanusGraph/janusgraph/commit/ed5b095b7b03a34242557d94da0633596a976630#commitcomment-96059129) for further details.
=> Fix broken performance test

docs/interactions/connecting/dotnet.md, mkdocs.yml
The getting started part for .NET still only uses Gremlin.Net to keep things as simple as possible. A second section then informs about how to get support for JanusGraph specific things through JanusGraph.Net.
Fixes #1276. #1276 also talks about Python but since we still don't have an official Python library, I'd like to reduce the scope of that issue to just .NET. We can later create another issue for Python once we haven an official library for that.
-----
=> Document JanusGraph.Net

.github/workflows/ci-index-es-dummy.yml
ES 8 support commit: 1d8abfee13666784cb995e8c3c1b8f7f3dc8322b
Add empty checks for doc PRs commit: 10e5ef58100459bf93f922402e939b514e178d0a
-----
=> Let ES 8 checks pass for doc PRs CTR

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
Reduces Guava usage in `StandardJanusGraph`.
Splits `prepareCommit` into multiple equivalent methods for better readability. There is duplicate code in `prepareCommit` but this PR doesn't reduce that duplicate code (only split by different methods). 
Related to #2033
-----
=> Reduce Guava usage in StandardJanusGraph.prepareCommit

janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java
This is especially important if the collection of edges is very large, which could cause heap exhaustion, preventing any indexing from being possible.
Signed-off-by: Scott Dial <geekmug@google.com>
-----
- [ x Is your initial contribution a single, squashed commit?
=> Avoid copying all properties and edges into memory for IndexRepairJob

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
For Cassandra, the QueryValidationException was wrapped in an ExecutionException causing the EXCEPTION_MAPPER to not match, but for SycllaDB, the failure is reported as a general ServerError, so we can only match on this condition by inspectng the detail message.
Signed-off-by: Scott Dial <geekmug@google.com>
-----
=> Should not retry CQL ServerErrors for large key values

docs/changelog.md, mkdocs.yml, pom.xml
=> Update TinkerPop to 3.6.2

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/SubqueryIterator.java
If the mixed index contains invalid elements, then the map will return null, which causes the stream to end, giving incomplete results. This change logs the invalid element identifier, but also filters the null elements out of the stream to allow the iterator to continue.
Fixes #3500
Signed-off-by: Scott Dial <geekmug@google.com>
-----
=> SubqueryIterator should ignore invalid elements

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/SubqueryIterator.java
Backport of #3501
Fixes #3500
-----
=> [v0.6] SubqueryIterator should ignore invalid elements

docs/changelog.md, mkdocs.yml, pom.xml
=> Update TinkerPop to 3.5.5

docs/changelog.md, janusgraph-all/pom.xml, janusgraph-backend-testutils/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-bigtable/pom.xml, janusgraph-core/pom.xml, janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-driver/pom.xml, janusgraph-es/pom.xml, janusgraph-examples/example-berkeleyje/pom.xml, janusgraph-examples/example-common/pom.xml, janusgraph-examples/example-cql/pom.xml, janusgraph-examples/example-hbase/pom.xml, janusgraph-examples/example-remotegraph/pom.xml, janusgraph-examples/example-tinkergraph/pom.xml, janusgraph-examples/pom.xml, janusgraph-grpc/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-hbase/pom.xml, janusgraph-inmemory/pom.xml, janusgraph-lucene/pom.xml, janusgraph-server/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, mkdocs.yml, pom.xml
=> JanusGraph release 0.6.3 [cql-tests] [tp-tests]

janusgraph-all/pom.xml, janusgraph-backend-testutils/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-bigtable/pom.xml, janusgraph-core/pom.xml, janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-driver/pom.xml, janusgraph-es/pom.xml, janusgraph-examples/example-berkeleyje/pom.xml, janusgraph-examples/example-common/pom.xml, janusgraph-examples/example-cql/pom.xml, janusgraph-examples/example-hbase/pom.xml, janusgraph-examples/example-remotegraph/pom.xml, janusgraph-examples/example-tinkergraph/pom.xml, janusgraph-examples/pom.xml, janusgraph-grpc/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-hbase/pom.xml, janusgraph-inmemory/pom.xml, janusgraph-lucene/pom.xml, janusgraph-server/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, mkdocs.yml, pom.xml
=> Set version to 0.6.4-SNAPSHOT CTR

docs/changelog.md
=> Update 0.6.3 release date and TinkerPop version CTR

docs/advanced-topics/transaction-log.md, docs/configs/janusgraph-cfg.md, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
Partially related to #3128
-----
=> Doc: Explain custom User Transaction Log implementation

docs/changelog.md, docs/index-backend/direct-index-query.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexProvider.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/IndexQueryBuilder.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
=> Apply limit and offset to IndexProvider.totals method

README.md
=> Doc: fix maven search link to Sonatype central CTR

docs/advanced-topics/partitioning.md
=> Partitioning: Discourage usage of vertex cut feature

janusgraph-core/pom.xml, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphEdgeVertexStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/FetchQueryBuildFunction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcher.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/PropertiesStepBatchFetcher.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/VertexStepBatchFetcher.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java
Before this commit the root cause exception could be lost and the NPE exception would be thrown instead. This commit changes logic to throw the root cause exception instead. Also, in case of interrupted exception it now attaches the root cause exception to the new thrown exception. This commit also refactors preFetch optimization logic to decrease duplicate code of preFetch logic in `JanusGraphPropertiesStep` and `JanusGraphVertexStep`.
Without this fix the log will look like below (which hides the root cause of the issue and throws NPE):
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.multiQueryResults" is null
at org.janusgraph.graphdb.tinkerpop.optimize.step.JanusGraphVertexStep.flatMap(JanusGraphVertexStep.java:139)
at …
```
=> Fix potential lost exception during multi-query properties or vertex steps

docs/interactions/connecting/java.md
=> Fix typo in java.md

janusgraph-core/pom.xml, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphEdgeVertexStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/FetchQueryBuildFunction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcher.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/PropertiesStepBatchFetcher.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/VertexStepBatchFetcher.java, janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java
Backports commit https://github.com/JanusGraph/janusgraph/commit/a55958c2d3246f00452103af6980ac77dbb8069e
-----
=> Backport #3711

pom.xml
Continuation of https://github.com/JanusGraph/janusgraph/commit/1b3e699c7a420467f2e8c747be3f463167072567
`[tp-tests]` is included in the commit but some TP tests might timeout due to #3747 . In such case those tests should be ignored.
-----
=> Update org.jacoco.ant to 0.8.10 [cql-tests] [tp-tests]

docs/changelog.md
This adds the changelog for 0.6.4 from `v0.6` also to `master`.
=> Add 0.6.4 Changelog from v0.6 branch

docs/changelog.md, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraph.java, mkdocs.yml, pom.xml
=> Bump TinkerPop to 3.6.4 [cql-tests] [tp-tests]

.github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml, BUILDING.md, README.md, docs/operations/container.md, janusgraph-dist/README.md, janusgraph-dist/docker/.dockerignore, janusgraph-dist/docker/Dockerfile, janusgraph-dist/docker/build-and-push-image.sh, janusgraph-dist/docker/conf/janusgraph-berkeleyje-es-server.properties, janusgraph-dist/docker/conf/janusgraph-berkeleyje-lucene-server.properties, janusgraph-dist/docker/conf/janusgraph-berkeleyje-server.properties, janusgraph-dist/docker/conf/janusgraph-cql-es-server.properties, janusgraph-dist/docker/conf/janusgraph-cql-server.properties, janusgraph-dist/docker/conf/janusgraph-inmemory-server.properties, janusgraph-dist/docker/docker-entrypoint.sh, janusgraph-dist/docker/examples/docker-compose-cql-es.yml, janusgraph-dist/docker/examples/docker-compose-mount.yml, janusgraph-dist/docker/examples/docker-compose.yml, janusgraph-dist/docker/load-initdb.sh, janusgraph-dist/docker/scripts/remote-connect.groovy, janusgraph-dist/docker/test-image.sh, janusgraph-dist/pom.xml, mkdocs.yml
=> Move Janusgraph docker into main repo

pom.xml
=> Backport Jackson 2.15.2 update #3804

.github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml
=> Update ci-publish Java to 8.0.372+7

janusgraph-backend-testutils/src/main/java/org/janusgraph/core/AbstractConfiguredGraphFactoryTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/management/ConfigurationManagementGraph.java
=> Make a copy of user-provided Configuration when calling ConfiguredGraphFactory#updateConfiguration

janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, mkdocs.yml
1. Fix a missing parameter in log
2. Add stale index doc to navigation
-----
=> Fix doc and logs

pom.xml
=> Update Guava to 32.1.1-jre and protobuf to 3.23.4 [cql-tests] [tp-tests]

docs/changelog.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/olap/OLAPTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraGraphComputer.java, janusgraph-server/pom.xml, pom.xml
=> [v0.6] Upgrade TinkerPop version to 3.5.7 [cql-tests][tp-tests]

docs/changelog.md, janusgraph-all/pom.xml, janusgraph-backend-testutils/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-bigtable/pom.xml, janusgraph-core/pom.xml, janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-driver/pom.xml, janusgraph-es/pom.xml, janusgraph-examples/example-berkeleyje/pom.xml, janusgraph-examples/example-common/pom.xml, janusgraph-examples/example-cql/pom.xml, janusgraph-examples/example-hbase/pom.xml, janusgraph-examples/example-remotegraph/pom.xml, janusgraph-examples/example-tinkergraph/pom.xml, janusgraph-examples/pom.xml, janusgraph-grpc/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-hbase/pom.xml, janusgraph-inmemory/pom.xml, janusgraph-lucene/pom.xml, janusgraph-server/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, mkdocs.yml, pom.xml
=> JanusGraph release 0.6.4 [cql-tests][tp-tests]

docs/changelog.md
1. Move breaking changes to the top.
2. Removed `Breaking change for Geoshape GraphBinary serialization` section. This section is for users who are using GraphBinary and Geoshape types. The other section, `String vertex ID support`, has a breaking change for all users who are using GraphBinary. Therefore, the Geoshape GraphBinary breaking change could be removed.
3. Fixed a few wording and style.
-----
=> Reorder and polish change log for 1.0.0 release

.github/workflows/docker-release-tags.yml
=> fix docker-release-tags action

janusgraph-all/pom.xml, janusgraph-backend-testutils/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-bigtable/pom.xml, janusgraph-core/pom.xml, janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-driver/pom.xml, janusgraph-es/pom.xml, janusgraph-examples/example-berkeleyje/pom.xml, janusgraph-examples/example-common/pom.xml, janusgraph-examples/example-cql/pom.xml, janusgraph-examples/example-hbase/pom.xml, janusgraph-examples/example-remotegraph/pom.xml, janusgraph-examples/example-tinkergraph/pom.xml, janusgraph-examples/pom.xml, janusgraph-grpc/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-hbase/pom.xml, janusgraph-inmemory/pom.xml, janusgraph-lucene/pom.xml, janusgraph-server/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, mkdocs.yml, pom.xml
=> Set version to 0.6.5-SNAPSHOT

pom.xml
Guava update requires full test suit to run.
-----
=> Update Guava to 32.1.3-jre [cql-tests][tp-tests]

.github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml, .github/workflows/ci-release.yml
Ensures deterministic releases from running the same CI (same Java version will be used).
-----
=> Use fixed Java versions for releases

.github/dependabot.yml, RELEASING.md
=> Change dependabot default backport label to v1.0 CTR

docs/changelog.md
=> Move 0.6 branch to EOL

.github/workflows/ci-docs.yml, docs/theme/structor-menu.js.gotmpl
=> revert menu.js and update ci-docs

docs/operations/deployment.md
=> [Doc] Introduce Gremlin parser in embedded JanusGraph mode

mkdocs.yml
=> fix structur failure

.github/workflows/ci-docs.yml
=> fix ci-docs with typo repository-name

docs/operations/deployment.md
- [[Doc] Introduce Gremlin parser in embedded JanusGraph mode](https://github.com/JanusGraph/janusgraph/pull/4099)
=> [v1.0] [Doc] Introduce Gremlin parser in embedded JanusGraph mode

cassandra-hadoop-util/pom.xml, janusgraph-hadoop/pom.xml, pom.xml
=> Update Zookeeper to fix cve [cql-tests][tp-tests]

pom.xml
- [Merge pull request #4345 from JanusGraph/dependabot/maven/org.apache.commons-commons-configuration2-2.10.1](https://github.com/JanusGraph/janusgraph/pull/4345)
=> [v1.0] Merge pull request #4345 from JanusGraph/dependabot/maven/org.apache.commons-commons-configuration2-2.10.1

.github/workflows/ci-publish-official.yml, pom.xml
=> add sbom to release process

mkdocs.yml
=> mkdocs.yml: Update TinkerPop version [CTR]

janusgraph-berkeleyje/src/test/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyVariableLengthKCVSTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreAdapter.java
Issue associated: https://github.com/JanusGraph/janusgraph/issues/4401
For unit testing, try commenting out the 1 line fix in OrderedKeyValueStoreAdapter and run the test to see the error. Uncomment the 1 line fix and run test to see expected correct behavior.
- [Y ] Have you written and/or updated unit tests to verify your changes?
- [N/A ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ N/A] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ N/A] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?
- …
=> Fixing Issue #4401

.gitignore, janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryDropBenchmark.java
Fixes #4434
Passed benchmark tests of this PR: https://github.com/porunov/janusgraph/actions/runs/8959195234/job/24604366986
-----
=> Drop benchmark graph data after CQLMultiQueryDropBenchmark

pom.xml
- [---](https://github.com/JanusGraph/janusgraph/pull/4475)
=> [v1.0] ---

janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/backpressure/QueryBackPressureTest.java
Often times I see `tests(core, 8)` job is stuck on `QueryBackPressureTest` (like [here](https://github.com/JanusGraph/janusgraph/actions/runs/9839915146/job/27163312023?pr=4536)). It's not obvious why, but the test may stuck for 6 hours which then is killed by GitHub Actions:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.janusgraph.diskstorage.util.CompletableFutureUtilTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.083 s -- in org.janusgraph.diskstorage.util.CompletableFutureUtilTest
[INFO] Running org.janusgraph.diskstorage.util.backpressure.QueryBackPressureTest
Error: The operation was canceled.
```
Thus, this PR adds timeout for the …
=> Improve flaky test QueryBackPressureTest to throw an exception faster on unexpected behavior

janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/backpressure/QueryBackPressureTest.java
- [Improve flaky test QueryBackPressureTest to throw an exception faster on unexpected behaviour](https://github.com/JanusGraph/janusgraph/pull/4539)
=> [v1.0] Improve flaky test QueryBackPressureTest to throw an exception faster on unexpected behaviour

docs/changelog.md
-----
Update changelog to contain update instructions for changes to in-memory backend introduced with `0.5.0`.
Fixes #4532 
- [x ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
=> Document changes for inmemory backend with Janusgraph 0.5.0 upgrade

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphFeatures.java
In a service running JanusGraph embedded, I observed a number of sizeable allocations coming from [JanusGraphVertexFeatures#getCardinality](https://github.com/JanusGraph/janusgraph/blob/2c71b378339a3ab49b961eef29b5a042d018f513/janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphFeatures.java#L161-L169).
From a profile (included below), it looks like a `StandardJanusGraphTx` transaction is created when [checking a vertex property's cardinality](https://github.com/JanusGraph/janusgraph/blob/2c71b378339a3ab49b961eef29b5a042d018f513/janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphFeatures.java#L162). The transaction itself [allocates a `CaffeineVertexCache`](https://github.com/JanusGraph/janusgraph/blob/2c71b378339a3ab49b961eef29b5a042d018f513/janu …
=> Disable vertex cache for cardinality checks

docs/changelog.md, mkdocs.yml, pom.xml
=> Update TinkerPop to 3.7.3 [tp-tests][cql-tests]

docs/schema/schema-init-strategies.md
=> Fix doc formatting for schema-init-strategies CTR

docs/schema/schema-init-strategies.md
=> Fix doc formatting: JSON schema initialization flow CTR

docs/changelog.md, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java, pom.xml
=> Update ElasticSearch to 8.15.3

docs/changelog.md, mkdocs.yml, pom.xml
Backporting TinkerPop update to v1.0
-----
=> [Backport] Update TinkerPop to 3.7.3 [tp-tests][cql-tests]

docs/changelog.md, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java, pom.xml
=> Backport ElasticSearch 8.15.3 update to v1.0

docs/changelog.md, pom.xml
=> Updarte ScyllaDB testing version to 6.2.0

.github/dependabot.yml
=> Update backport labels from v1.0 to v1.1 CTR

README.md
=> Add Mapped to JanusGraph Production Users
