JanusGraph/janusgraph

CONTRIBUTING.md
Now that we have a canonical copy of the process for how to sign a JanusGraph
project-wide CLA, we can remove the same content from this repo, since this
applies to all JanusGraph repos uniformly.
=> Link to common CLA content; remove local copy.

CONTRIBUTING.md
This will help folks easily address issues that @janusgraph-bot may find with
their commits such that they comply with the CLA and DCO requirements.
Thanks to @jerryjch for the proper syntax for updating author of a commit.
=> Add instructions for fixing DCO and email.

.travis.yml
Coverity includes Travis CI integration; this config is following the
instructions at the following page with minor modifications:
https://scan.coverity.com/projects/janusgraph-janusgraph/builds/new?tab=travis_ci
=> Add Coverity config for static code analysis.

.travis.yml
The last line of the output of a recently-failed Travis job:
https://travis-ci.org/JanusGraph/janusgraph/jobs/195761554
tells us that our build is being terminated due to no output for 10 minutes.
The output also tells us to look at the following documentation:
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
which suggests that using `travis_wait` command for silent long-running commands
will print out a line of output every minute for 20 minutes, such that Travis
does not automatically end the build if there's no output for 10 minutes.
If we need more time, per the docs, we can extend it by adding a number to the
command, e.g.,
```
travis_wait 30 mvn clean package [...]
```
-----
@hsaputra – the only way to test this is to submit a PR …
=> Avoid timeouts due to no output with `travis_wait`

.travis.yml
Factored out the build and test steps to be able to easily parameterize them
using environment variables in both Linux and OS X.
Starting by testing just the `janusgraph-solr` and `janusgraph-test` modules.
=> Automatically run tests on Travis CI

.travis.yml
This change enables Travis CI to test all modules, even those we know to be
failing, but annotations the expected failures explicitly, such that their
failures will not fail the overall build.
As a result, we will be able to track improvements to the tests to allows us to
remove them from the `allowed_failures` list in the future, once fixes have been
made.
@sjudeng – you may find this of interest; maybe you can rebase some of your fixes to tests on `master` once this PR is merged, and see how the tests do on Travis CI?
=> Enable testing of all modules on Travis CI

README.md
[skip ci]
Looks like the simpler URL only works for the archives, but to subscribe, we need a different URL.
=> Fix link to subscribe to mailing lists.

janusgraph-cassandra/pom.xml, janusgraph-es/pom.xml, janusgraph-es/src/test/resources/log4j.properties, janusgraph-hadoop-parent/pom.xml, janusgraph-hbase-parent/pom.xml, janusgraph-lucene/src/test/resources/log4j.properties, janusgraph-solr/pom.xml, janusgraph-solr/src/test/resources/log4j.properties, pom.xml
Log4j should be used for testing but Logback is being used in some modules (janusgraph-es, janusgraph-hadoop, janusgraph-hbase and janusgraph-solr). In these cases the log4j.properties test resources are ignored and console logging is too verbose. In a standard test run (`mvn verify`) console logging exceeds 75M. With the fixes in this PR the logging output for the same run is about 3M.
Note the solution was already present in janusgraph-cassandra (see logging comment in [janusgraph-cassandra/pom.xml](https://github.com/JanusGraph/janusgraph/blob/fc48e9e680273ee62292126f55585b4f1a6d8294/janusgraph-cassandra/pom.xml#L44-L62)) and this PR just propagates that into the offending modules. More minor updates were to clean up some of the test log4j.properties files and ensure that these were …
=> Ensure Log4j is used for testing

janusgraph-hadoop-parent/janusgraph-hadoop-2/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseBinaryInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseBinaryRecordReader.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/HBaseInputFormatIT.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/hbase-read.properties, janusgraph-hadoop-parent/pom.xml
Includes refactoring of CassandraInputFormatIT to pull out common tests. Fixes issue in HBaseBinaryInputFormat and HBaseBinaryRecordReader that caused the following error:
```
06:47:57.278 [Executor task launch worker-0] ERROR org.apache.spark.executor.Executor - Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.ClassCastException: org.apache.hadoop.hbase.mapreduce.TableInputFormatBase$1 cannot be cast to org.apache.hadoop.hbase.mapreduce.TableRecordReader
at com.thinkaurelius.titan.hadoop.formats.hbase.HBaseBinaryInputFormat.createRecordReader(HBaseBinaryInputFormat.java:47) ~[titan-hadoop-core-1.1.0-SNAPSHOT.jar:na]
at com.thinkaurelius.titan.hadoop.formats.util.GiraphInputFormat.createRecordReader(GiraphInputFormat.java:53) ~[titan-hadoop-core-1.1.0-SNAPSHOT.jar:na]
at …
```
=> Add tests and resolve issue running SparkGraphComputer on HBase

janusgraph-cassandra/src/test/java/org/janusgraph/CassandraStorageSetup.java
Regex to detect if Cassandra keyspace name contains non-alphanumeric-underscore characters is incorrect. This causes test failures in `janusgraph-solr` tests with the following error.
```
InvalidRequestException(why:Keyspace name must not be empty, more than 48 characters long, or contain non-alphanumeric-underscore characters (got "org.janusgraph.diskstorage.solr.ThriftSolrTest"))
```
This wasn't a problem previously because `com.thinkaurelius.titan`-based keyspace names had lengths longer than max length of 48, so they'd be updated based on that constraint, but `org.janusgraph`-based names can have lengths less than 48.
=> Incorrect Cassandra keyspace regex for non-alphanumeric-underscore characters

janusgraph-all/pom.xml, janusgraph-all/src/main/java/org/janusgraph/graphdb/tinkerpop/plugin/JanusGraphGremlinPlugin.java, janusgraph-core/pom.xml, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/JanusGraphSchemaVertex.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml, janusgraph-test/pom.xml, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphConcurrentTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphEventualGraphTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphPartitionGraphTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphPerformanceMemoryTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-test/src/main/java/org/janusgraph/olap/OLAPTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/serializer/SerializerGraphConfiguration.java, pom.xml
This CL should change nothing, I've set up JanusGraph in eclipse and made some changes to make things saner.  For reference I'm using M2E to configure the project, no special settings.
* Switch to org.codehaus.gmavenplus version 1.5 for all gmaven plugins, there used to be a mix of gmaven and gmavenplus.  The latest version works nicely with M2E.
* Remove the janusgraph-hadoop project from the dependencies section of janusgraph-all/pom.xml as it's not a java project.
* Do explicit casts wherever eclipse was generating errors.
* A -Xlint:unchecked to compiler options so we get more warnings for this kind of thing.
Eclipse builds still aren't clean, theres errors from with the assembly plugin and something to do with packing output locations I haven't been able to track down yet.
=> Cleanup some dependencies and implicit casts to make things cleaner in eclipse 

docs/development.txt, docs/index.txt
Here is a first cut at developer process docs.  The release policy section is pretty sparse but I think we can expand this when we go through our first release process.  I imagine we'll also add explicit release steps and directions at that point also.  I'm not wed to any of these particular policies but I think they're a good start.  Specifically I'm curious if folks think we should allow CTR in limited cases like I've defined here.
=> Issue 95: Adding first version of development process documentation.

pom.xml
https://github.com/JanusGraph/janusgraph/issues/132
Run `mvn project-info-reports:dependencies` to generate the reports. Takes around 4 minutes with `dependency.locations.enabled=false`. Results are found under `*/target/site/dependencies.html`.
I tracked down several of the undetermined ones:
* dom4j - BSD
https://github.com/dom4j/dom4j/blob/dom4j_1_6_1/LICENSE.txt
* com.thoughtworks.paranamer:paranamer:2.6 - BSD
https://github.com/paul-hammant/paranamer/blob/paranamer-parent-2.6/LICENSE.txt
* asm - BSD
http://websvn.ow2.org/filedetails.php?repname=asm&path=%2Ftags%2FASM_3_1%2Fasm%2FLICENSE.txt
* commons-net:commons-net:1.4.1 - Apache
https://github.com/apache/commons-net/blob/NET_1_4_1/LICENSE.txt
* javax.validation:validation-api:1.0.0.GA - Apache …
=> Add repositories to enable dependency reports

janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyGraphTest.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyOperationCountingTest.java, janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/AbstractCassandraStoreManager.java, janusgraph-cassandra/src/test/java/org/janusgraph/graphdb/CassandraGraphTest.java, janusgraph-cassandra/src/test/java/org/janusgraph/graphdb/thrift/ThriftGraphCacheTest.java, janusgraph-cassandra/src/test/java/org/janusgraph/graphdb/thrift/ThriftOperationCountingTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/StandardStoreFeatures.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/StoreFeatures.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/inmemory/InMemoryStoreManager.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/graphdb/hbase/HBaseGraphTest.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/graphdb/hbase/HBaseOperationCountingTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/LockKeyColumnValueStoreTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/log/LogTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphConcurrentTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/inmemory/InMemoryGraphTest.java
These changes are a rework of something I tried to do two years ago but did not make it in Titan before the end of 2015. Contains an extremely minor refactoring of tests so that the DynamoDB Storage Backend can change some parameters. Also promotes optimisticLocking to a StoreFeature, as that is where it belongs.
=> Make optimisticLocking a StoreFeature. Silence noisy kcvslog test.

AUTHORS.txt, CONTRIBUTORS.txt, janusgraph-cassandra/src/test/java/org/janusgraph/graphdb/CassandraGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/JanusGraphConstants.java, janusgraph-core/src/main/resources/org/janusgraph/graphdb/configuration/janusgraph.internal.properties, pom.xml
Implemented backward compatibility with titan and its previous versions compatible with JanusGraph's storage format.
Addresses issue #73.
=> Backward compatibility with Titan

docs/build-and-copy-docs.sh
This script assumes the existence of two checked out Git repos:
JanusGraph/janusgraph and JanusGraph/docs.janusgraph.org
It will build the docs in the first repo and copy them to the second repo, such
that a PR can be created in the second repo and pushed for review. Once the
PR in docs.janusgraph.org is submitted, it is published to
http://docs.janusgraph.org within minutes by GitHub since that domain is hosted
by GitHub directly from the repo.
=> Add script to build and copy docs for publishing

janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyJanusGraphProcessTest.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyProcessStandardSuite.java
This PR resolves #171 by using a custom `ProcessStandardSuite` implementation to skip the `TraversalInterruptionTest` in that module.
All remaining tests are passing with this update.
```
$ mvn clean install -DskipTests=true -Dtest.skip.tp=false -pl janusgraph-berkeleyje
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:18:13.432s
[INFO] Finished at: Sat Apr 01 00:57:43 UTC 2017
[INFO] Final Memory: 26M/510M
[INFO] ------------------------------------------------------------------------
$ mvn clean install -pl janusgraph-berkeleyje
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS …
```
=> Issue 171: Exclude TraversalInterruptionTest in BerkeleyJanusGraphProcessTest

docs/advanced.txt, docs/monitoring.txt, janusgraph-core/pom.xml
Excludes LGPL from Remote Tea Runtime for ONC/RPC Protocol discussed in #132. The dependency tree is:
* org.janusgraph:janusgraph-core:jar:0.1.0-SNAPSHOT
* com.codahale.metrics:metrics-ganglia:jar:3.0.1
* info.ganglia.gmetric4j:gmetric4j:jar:1.0.3
* org.acplt:oncrpc:jar:1.0.7
Apache TinkerPop has a similar [exclusion](https://github.com/apache/tinkerpop/blob/3.2.3/pom.xml#L602-L606).
* Verified `oncrpc.jar` is no longer included on `mvn dependency:tree`
* Built distribution zip and verified it does not contain `oncrpc.jar` (it did not before this change either)
* Built and verified the monitoring documentation is now included and updated
* Verified that including `janusgraph-core` as a dependency in a project does not pull in `oncrpc.jar`
=> Issue 132: Exclude LGPL Remote Tea Runtime for ONC/RPC protocol

docs/versions.txt
Partially addresses issue #102 (for HBase only) as part of the upcoming 0.1.0
release.
=> Update version compatibility table for 0.1.0 release

.travis.yml
Resolves #182 by removing the branch safelist from .travis.yml so that all branches are tested under Travis. If at a later time some branches do need to be excluded this could be revisited, possibly [using regular expressions](https://docs.travis-ci.com/user/customizing-the-build#Using-regular-expressions) instead of specific branch names.
=> Issue 182: Enable Travis CI on all branches

README.md
Add directions for subscribing and unsubscribing using an arbitrary email
address, not just those associated with a Google account (whether Gmail or
corporate email).
=> Add instructions for non-Google account holders

AUTHORS.txt, NOTICE.txt
AUTHORS.txt
* For clarity, add Aurelius explicitly, even though DataStax acquisition implies
that DataStax owns Aurelius IP
* Add IBM to the list of authors since we've had contributions from several
IBM folks already
NOTICE.txt
* Update the copyright statement to include all JanusGraph copyright holders /
authors
* Include reference to JanusGraph contributors
* Remove link to thinkaurelius.com as it redirects to DataStax and is thus not
useful to learn about Aurelius; instead, mention that it was acquired by
DataStax
This addresses issue #203
[skip ci]
=> Clarifications to AUTHORS.txt and NOTICE.txt

docs/solr.txt, janusgraph-solr/pom.xml
=> Issue 133: Mark JTS as optional dependency in janusgraph-solr

janusgraph-hadoop-parent/janusgraph-hadoop/pom.xml
Signed-off-by: Chin Huang <chhuang@us.ibm.com>
The current packaging=pom for janusgraph-hadoop is causing an
Eclipse dependency error for the janusgraph-all project. I removed
the packaging line from pom.xml so the default type of jar is used.
It results in that the Eclipse Import will create a java project for
janusgraph-hadoop.
=> Update Maven packaging to fix Eclipse dependency issue

CHANGELOG.asc, docs/changelog.txt, janusgraph-all/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-cassandra/pom.xml, janusgraph-core/pom.xml, janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-es/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-2/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop/pom.xml, janusgraph-hadoop-parent/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-098/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml, janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml, janusgraph-hbase-parent/janusgraph-hbase/pom.xml, janusgraph-hbase-parent/pom.xml, janusgraph-lucene/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, pom.xml
* Release date set in change logs
* mvn release:prepare run which bumped version 0.1.0, committed, tagged, and then bumped to the new dev version 0.1.1-SNAPSHOT and committed
=> 0.1 release prep

janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/thrift/thriftpool/CTConnectionFactory.java, janusgraph-cassandra/src/test/java/org/janusgraph/graphdb/thrift/ThriftConnectionTest.java
When a network failure happened, such as Broken Pipe exceptions or any other network related issue, ThriftPool wouldn't recognize it because was just checking its internal state (isOpen) instead of trying to use the connection itself.
Updated to make a simple check, `describe_version()`, just to make sure the connection (Client/Server socket connection) is valid before returning it as a valid object.
The footprint is very small, won't affect performance at all.
Fixes issue #60.
=> Fixed reconnection issue for CassandraThrift

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementLogger.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
Previously, we were seeing new index creations on the same graph act as
if they were equal to previous triggers. Thus, the previous but
not finished updateStatusTriggers were being removed from the SET and
getting stuck in INSTALLED. In this change, we have done two things:
1. Change the datastructure housing the updateStatusTriggers from a Set
to a List.
2. Remove the code that removes any updateStatusTriggers from the data
structure.
These changes ensure all index creations on a given graph fulfill their
INSTALLing.
Issues: #195
=> UpdateTriggerStatus from Set -> List

janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheVertexProperty.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphVertexStep.java, pom.xml
Resolves #173. Tested default and TinkerPop tests in two groups covering all modules except hbase-098.
`mvn verify -Dtest.skip.tp=false -pl janusgraph-test,janusgraph-berkeleyje,janusgraph-cassandra`
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19:16:02.759s
[INFO] Finished at: Wed Apr 12 23:05:13 UTC 2017
[INFO] Final Memory: 34M/873M
[INFO] ------------------------------------------------------------------------
```
`mvn verify -Dtest.skip.tp=false -rf :janusgraph-hbase-10`
```
INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] …
```
=> Issue 173: Update to TinkerPop 3.2.4

docs/basics.txt
JanusGraph Server is an extension of Apache TinkerPop from where this usage originates.  The term was corrected in unreleased TinkerPop 3.3.0  https://issues.apache.org/jira/browse/TINKERPOP-1369
=> Replace term 'REST' with 'HTTP' for correctness

janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyGraphTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
When I externalized noVertices in the vertexCentricQuery test, I forgot to change two occurrences of variables that are proportional to noVertices.
First occurrence: [242](https://github.com/awslabs/dynamodb-titan-storage-backend/blob/1.0.0/src/test/java/com/amazon/titan/graphdb/dynamodb/SingleDynamoDBGraphTest.java#L194) vs 1667
Second occurrence: [242](https://github.com/awslabs/dynamodb-titan-storage-backend/blob/1.0.0/src/test/java/com/amazon/titan/graphdb/dynamodb/SingleDynamoDBGraphTest.java#L307) vs 1667
I verified that these quantities appear to be proportional by adding the relevant test to the BDB backend.
=> Number of friend edges in vertexCentricQuery depends on noVertices

docs/basics.txt, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/AbstractIndexStatusReport.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/AbstractIndexStatusWatcher.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/GraphIndexStatusReport.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/GraphIndexStatusWatcher.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/RelationIndexStatusReport.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/RelationIndexStatusWatcher.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrRunner.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
This fixes the following bug for example:
If a user wants to update an index by adding a propertyKey to it, then
the existing propertyKeys will have status ENABLED, but the
IndexStatusWatcher will be looking for REGISTERED only, so the index update
is never completed.
Issues: #196
=> Add ability to await on multiple statuses

CONTRIBUTORS.txt
As per this request:
https://github.com/JanusGraph/janusgraph/pull/193#issuecomment-298262171.
=> Add my name and email to CONTRIBUTORS.txt

janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml
Fixes #245 by removing the ssl property. With this update Gremlin Server starts up properly. But note TinkerPop 3.2.4 [gremlin-server.yaml](https://github.com/apache/tinkerpop/blob/3.2.4/gremlin-server/conf/gremlin-server.yaml) does have this element defined so this might not be the correct solution.
=> Remove ssl.enabled=false element from gremlin server yaml

docs/basics.txt, janusgraph-core/src/main/java/org/janusgraph/core/schema/DefaultSchemaMaker.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/SchemaInspector.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphDefaultSchemaMaker.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/AbstractVertex.java, janusgraph-test/pom.xml, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphDefaultSchemaMakerTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTxTest.java
The previous implementation only provided property key names to
DefaultSchemaMaker instances, which limits users' ability to customize
behavior. This changeset also passes the property key value down to the
DefaultSchemaMaker, allowing more fine-grained analysis and potentially
better decisions around default types. A base implementation has been
added to the JanusGraphDefaultSchemaMaker.
Signed-off-by: Keith Lohnes <krlohnes@us.ibm.com>
=> Add signatures for value-based type defaults

docs/searchpredicates.txt, docs/textsearch.txt, janusgraph-core/pom.xml, janusgraph-core/src/main/java/org/janusgraph/core/attribute/Text.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchIndexTest.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneIndexTest.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/attribute/TextTest.java
This adds fuzzy predicate (similarity based on Levenshtein edit distance) for all mixed indexes backend.
For the method evaluateRaw of the predicate, I use the same degree of similarity as ES : 
- 0 for strings of one or two characters
- 1 for strings of three, four or five characters
- 2 for strings of more than five characters
Issues : https://github.com/JanusGraph/janusgraph/issues/221
=> Add fuzzy predicate on all mixed indexes backend

.travis.yml, janusgraph-berkeleyje/src/test/resources/log4j.properties, janusgraph-cassandra/src/test/resources/log4j.properties, janusgraph-es/pom.xml, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchSetup.java, janusgraph-es/src/test/resources/log4j.properties, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/assembly/shared-resources/log4j.properties, janusgraph-hbase-parent/common/test/resources/log4j.properties, janusgraph-lucene/src/test/resources/log4j.properties, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/resources/log4j.properties
This PR makes a number of updates to improve test stability under Travis. All modules with the exception of hbase-098 now pass consistently and are required for a successful build. This should resolve #74 and may help mitigate the need for #5 and #18.
Testing consisted of monitoring 100 builds over the last week (see https://travis-ci.org/sjudeng/janusgraph/builds, builds <span>#</span>49-current). There were two unexpected build failures during that time. Other failures were the result of various build matrix experiments.
In the event of an isolated build failure committers can log in to Travis and restart the specific failed job. Based on the above testing this is estimated to be limited to 2% of builds. Should some module(s) begin failing more consistently we can mark them as optional …
=> Require additional modules for successful Travis build

README.md
Thanks to @sharpau for confirmation that Seeq has deployed JanusGraph and permission to use the name here.
See also https://github.com/JanusGraph/janusgraph.org/pull/11 for the website update.
=> Add Seeq to the list of JanusGraph users.

docs/elasticsearch.txt, docs/solr.txt, docs/textsearch.txt, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexFeatures.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/ParameterType.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchConfigTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchIndexTest.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneIndexTest.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexTest.java, janusgraph-solr/src/test/resources/solr/core-template/schema.xml, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
Issue : https://github.com/JanusGraph/janusgraph/issues/222
=> Allows to use custom analysers in ES or Solr

.travis.yml
* Remove `travis_wait` because Coverity cannot find it:
https://travis-ci.org/JanusGraph/janusgraph/jobs/236948159#L925
* Update version number to 0.2.0-SNAPSHOT for consistency with `pom.xml`
[skip ci] as we don't need to waste Travis cycles on this in the `master` branch
since this should only affect the `coverity_scan` branch, once we merge into it.
=> Change Coverity config to fix the analysis build

.travis.yml
Cassandra Thrift test groups have been regularly timing out under Travis. This PR adds another test group set and also moves all Thrift test groups to optional in the Travis build matrix. Justification is that tests for the astyanax and embedded clients are still required.
Related issue is #74.
=> Further split Cassandra Thrift tests and make optional in Travis

janusgraph-test/src/main/java/org/janusgraph/blueprints/AbstractJanusGraphComputerProvider.java
I now use the default block size here. I think we need to opt-out of some tests still
=> Use larger id block size and avoid deprecated methods.

janusgraph-cql/pom.xml, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLColValGetter.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLResultSetKeyIterator.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLResultSetKeyIteratorTest.java
Now that the CQL backend is merged, please find the requested PR migrating from the "javaslang" library to the renamed (and upgraded) "vavr" library.
=> Migrate from javaslang to vavr for CQL backend

docs/elasticsearch.txt, docs/searchpredicates.txt, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
I also fix some indentation issue.
https://github.com/JanusGraph/janusgraph/issues/293
=> This feature allows to index points, circles and boxes in PREFIX_TREE mapping for ES.

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/TransportElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestIndexMappings.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchConfigTest.java, janusgraph-es/src/test/resources/mapping.json, janusgraph-es/src/test/resources/template.json
This adds the possibility to use external mapping in order to use custom ES mapping.
If you set USE_EXTERNAL_MAPPINGS to true, JanusGraph will check if the mapping is good instead of push it.
Whitout this adds, even if I push a mapping JanusGraph will update it during register phase. 
This feature will allows to manage mapping directly in Kibana and not with ES_CREATE_EXTRAS_NS properties or to set for example a property with are declare in JanusGraph as String to IP, or use copy-to ES feature.
Issue : https://github.com/JanusGraph/janusgraph/issues/222
=> Can use external ES mapping instead of push mapping

docs/intro.txt, janusgraph-core/src/main/java/org/janusgraph/example/GraphOfTheGodsFactory.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
This changeset updates the getting-started documentation to indicate that a user must use the `loadWithoutMixedIndex` method when using a JanusGraph configuration without an indexing backend.  It also updates the "load" method to throw an exception when it's told to use mixed indexes, but an indexing backend isn't configured.
Issue: #298
=> Documentation and error message enhancements for GraphOfTheGodsFactory with no index backend configured

README.md
Also switch to using img.shields.io for the Maven badge for consistency with
most of our other badges.
Use HTTPS for all badges and links to Maven and Javadoc.
=> Add Javadoc badge with link to javadoc.io [skip ci]

.gitignore, AUTHORS.txt, BUILDING.md, README.md, janusgraph-dist/janusgraph-dist-hadoop-2/Dockerfile, janusgraph-dist/janusgraph-dist-hadoop-2/docker-compose.yml, janusgraph-dist/janusgraph-dist-hadoop-2/es/elasticsearch.yml, janusgraph-dist/janusgraph-dist-hadoop-2/es/wait-for-es.sh, janusgraph-dist/pom.xml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/janusgraph-berkeleyje-es-server.properties, pom.xml
=> Dockerize gremlin-server.sh with JanusGraph

.travis.yml
This fixes a typo to ensure tests don't run, and also updates to skip the install stage, in the `coverity_scan` branch under Travis. Hopefully this helps get the Travis build passing on the branch (https://travis-ci.org/JanusGraph/janusgraph/builds/238948501).
=> Skip build and tests on coverity_scan branch

.travis.yml
This restores metadata tags removed in #300. These tags are needed in Coverity dashboard (see [this comment](https://github.com/JanusGraph/janusgraph/pull/300#discussion_r121276345)).
=> Restore coverity_scan metadata tags in Travis config

README.md
The first build was submitted manually, because it does not (yet) work via
Travis CI; the scan results can be seen at
https://scan.coverity.com/projects/janusgraph-janusgraph
Making further progress on issue https://github.com/JanusGraph/janusgraph/issues/9; now we need to start addressing the issues Coverity found, perhaps in decreasing order of severity.
If you don't have access to the Coverity dashboard and would like it, please contact me or apply via Coverity dashboard (and let me know). You can login to Coverity with your GitHub account.
=> Added a badge for Coverity Scan [skip ci]

CONTRIBUTING.md
=> Added note about adding [skip ci] to documentation changes. [skip ci]

janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphTransaction.java, janusgraph-core/src/main/java/org/janusgraph/core/util/JanusGraphId.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/idmanagement/IDManager.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsTransaction.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/VertexIDAssignerTest.java
fixes #147, another bug fix that didn't make it into Titan by the end of 2015
=> Enable setting custom vertex ids in TP3 interface #147 

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/StandardSerializer.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/serializer/SerializerTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/serializer/attributes/THashMapSerializer.java
This it to fix Issue #306 which prevents the JanusGraph from starting from an existing TitanGraph if that graph had had a custom serializer registered.
The custom serializers are added `StandardSerializer.registerClass()`. At that point we’ll not have used the default HashMap serializer yet. So if we spot an attempt to add a custom one in this method then de-register the default one and then register the custom serializer as normal.
For the unit test I extended the SerializableSerializer class to add an extra property into the HashMap when its deserialized, then check for this property which would only be present if the custom serialiser had been used.
=> AttributeSerializer conflict on HashMap data type for migrated Titan

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
Add a configuration flag to the Cassandra CQL backend to disable system operations from issuing global queries. If set, this flag will result in all system queries using the local consistency, LOCAL_QUORUM.
Addresses issue: https://github.com/JanusGraph/janusgraph/issues/347
Reviewers: dbolcion, vigneshg, suganyar
Reviewed By: vigneshg
Subscribers: dbolcion, jenkins
Differential Revision: https://code.uberinternal.com/D948839
Signed-off-by: Alain Rodriguez <alain@uber.com>
=> Support disabling QUORUM calls for system queries

TESTING.md, janusgraph-cassandra/pom.xml, janusgraph-cassandra/src/test/java/org/janusgraph/CassandraStorageSetup.java, janusgraph-cassandra/src/test/java/org/janusgraph/diskstorage/cassandra/thrift/ThriftDistributedStoreManagerTest.java, janusgraph-cql/pom.xml, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLDistributedStoreManagerTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLSSLStoreTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CassandraStorageSetup.java, pom.xml
Related issue is #53. A new Maven profile, disabled by default, allows running Thrift and CQL tests using the ScyllaDB storage backend. This PR just adds support for running the tests but does not resolve the associated test failures/errors (see #53 for more information).
=> Support testing Thrift and CQL with ScyllaDB

janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexMemoryHandler.java
An assertion in the wrong spot causes failure of `GraphComputerTest.shouldSucceedWithProperTraverserRequirements`.
=> Fix assertion error with list cardinality

README.md
Courtesy to use the company name courtesy of @tunaygur.
Also, note that we don't yet have permission to feature Uber's logo on http://janusgraph.org so there's no corresponding PR on that repo to add it.
=> Add Uber as a production JanusGraph user [skip ci]

docs/basics.txt
`useMapperFromGraph` is deprecated and replaced by `ioRegistries`.  It isn't used in any other configuration file so let's update the docs to reflect that.
=> Replace deprecated useMapperFromGraph in docs with ... [skip ci]

janusgraph-core/src/main/java/org/janusgraph/diskstorage/EntryMetaData.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
These are the cleanup tasks we discovered during the HBase TTL implementation.
=> Clean up EntryMetaData enum and interned its state

janusgraph-dist/src/assembly/static/bin/gremlin.sh, janusgraph-dist/src/pkg/static/pkgcommon/payload/usr/bin/gremlin.sh
- retained JanusGraph's classpath order for logging
- retained jamm agent
- retained HADOOP LIB path
- -e is superseded by TinkerPop
- profiling was never used
- also synced the copy in pkgcommon to use the same
=> Updated gremlin.sh to match TinkerPop 3.2.5 [skip ci]

janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/thrift/CassandraThriftKeyColumnValueStore.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryProcessor.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/system/EmptyVertex.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/AllEdgesIterator.java, janusgraph-core/src/main/java/org/janusgraph/util/datastructures/IterablesUtil.java
Since Guava 20.0, Iterators.emptyIterator() is no longer public, resulting in an IllegalAccessError when trying to use various traversal iteration steps which call it.  Per the deprecation notice in the documentation for Guava 19.0 (https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/Iterators.html#emptyIterator()), this commit replaces all occurrences of Iterators.emptyIterator() with Collections.emptyIterator().
Signed-off-by: Mike Sager <mike@mikesager.name>
=> Fix IllegalAccessError for Iterators.emptyIterator() when using Guava >= 20.0

.travis.yml, janusgraph-cql/pom.xml, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLDistributedStoreManagerTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLIDAuthorityTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLLockStoreTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLLogTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLMultiWriteStoreTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLSSLStoreTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CachingCQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CassandraStorageSetup.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphIterativeTest.java, janusgraph-cql/src/test/resources/log4j.properties
Makes the following updates to fix #383. With these updates the full (default+TinkerPop) test suite runtime for the CQL module is decreased from 15.1 hours to 3.3 hours.
* A single static cluster instance and a single static session per keyspace managed in CQLStoreManager.
* Truncate tables instead of drop keyspace in CQLStoreManager.clearStorage(). There was an issue with test failures when switching to truncation that was resolved by deleting the commitlog directory prior to starting embedded test instance in CassandraStorageSetup.
* Test parallelism was removed to resolve test failures associated with the above updates and for consistency with test executions in other modules.
* Minor updates to split Travis build matrix for CQL tests and reduce logging (also renamed logging appender …
=> Static cluster/session management in CQL backend

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CassandraStorageSetup.java
If no protocol is specified, the CQL driver no longer defaults to the highest driver
protocol version. Instead, the driver will negotiate with Cassandra and select the
highest mutually supported protocol version.
=> Issue 398 - CQL storage adapter doesn't work with default configs and bundled Cassandra

janusgraph-core/src/main/java/org/janusgraph/core/attribute/Geoshape.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModule.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIoTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/attribute/GeoshapeTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/serializer/SerializerTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryTest.java
These updates allow Geoshape points stored in legacy (pre-0.2) graphs and Kryo files to be deserialized. Also adds support for Geoshape serialization using GraphSON 2.0.
Fixes #374
=> Support deserializing points stored in legacy graphs

janusgraph-codepipelines-ci/pom.xml
Resolves this warning when building...
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar -> duplicate declaration of version 2.6.6 @ org.janusgraph:janusgraph-codepipelines-ci:[unknown-version], /tmp/janusgraph/janusgraph-codepipelines-ci/pom.xml, line 81, column 21
=> Remove duplicate dependency

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchConfigTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchMutliTypeIndexTest.java, janusgraph-es/src/test/resources/template.json
With this pull request, JanusGraph will use one Elasticsearch index by JanusGraph index instead of use one Elasticsearch index for all JanusGraph indexes.
Issue : https://github.com/JanusGraph/janusgraph/issues/335
=> Split Elasticsearch index into N indexes.

janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/astyanax/AstyanaxKeyColumnValueStore.java, janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/astyanax/AstyanaxStoreManager.java, janusgraph-cassandra/src/test/java/org/janusgraph/diskstorage/cassandra/astyanax/AstyanaxColumnPaginationTest.java
#411 
JanusGraph has a tendency to make queries to Cassandra with _very_ large
limits. For example, any query without a `.limit()` clause will fetch
all matching columns from a given row. These requests are usually
range-bound (e.g., only requesting columns that are edges, based on the
serialization logic) but are not limited.
Fetching millions of columns in a single request is not very friendly to
Cassandra; in production we've observed memory allocation spikes in
excess of 10GB in a 30s period. On my local machine, calling
graph.traversal().V(id).outE().count()
prior to this commit will cause my Cassandra instance to OOM in
approximately 10 seconds.
This patch places a hard cap on the number of columns returned (per row)
via a single request to Cassandra. If, for a given request, a row …
=> Paginate column access in AstyanaxStore

pom.xml
Fixes Issue #131 - Use jBCrypt dependency from central
=> Fixes Issue #131 - Use jBCrypt dependency from central

janusgraph-core/src/main/java/org/janusgraph/core/ReadOnlyTransactionException.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexProgramScanJob.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheVertexProperty.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
The original (pre-TinkerPop-3.2.4) implementation didn't check whether transaction was read-only and (as expected) threw UnsupportedOperationExceptions when calling CacheVertexProperty.remove() during OLAP traversals. This behavior causes numerous TinkerPop test failures starting in v3.2.4,  where TraversalVertexProgram.HALTED_TRAVERSALS are cleaned up in [TraversalVertexProgram](https://github.com/apache/tinkerpop/blob/3.2.4/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/TraversalVertexProgram.java#L294-L296). Interestingly the logic is in 3.2.3 as well so I'm not sure why tests only started failing on this in 3.2.4.
Initial updates to always silently ignore the read-only transaction errors resulted in issues as identified in #427. The update here …
=> Resolve read-only transaction errors in TinkerPop GraphComputer tests

.gitignore, analysis/coverity-scan.sh
This script will help address issue https://github.com/JanusGraph/janusgraph/issues/466 by running Coverity scans directly via our own script rather than the Travis CI plugin.
=> Added a script for running a Coverity scan.

janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexState.java, pom.xml
Fixes #475. All default and TinkerPop tests are passing.
=> Update to TinkerPop 3.2.6

docs/build-and-copy-docs.sh
Automatically detect the current version from the root `pom.xml` file (rather
tahn requiring the user to manually specify it, or defaulting to `latest`) and
create the necessary directory in the documentation dir if needed (rather than
erroring out).
This fixes issue #484.
=> Auto-detect version and create docs dir. [skip ci]

pom.xml
Fixes #275 and, in my testing, allows the use of the latest JanusGraph with databases from previous versions.
=> Update janusgraph compatible versions to include 0.1.x

janusgraph-core/src/main/java/org/janusgraph/core/attribute/Geoshape.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/serializer/SerializerTest.java
This pull request is a continuation of a discussion @sjudeng from issue #420.
While testing I noticed that the latitude and longitude values being deserialised by JanusGraph didn't match those originally written by Titan. The problem looks like there's a bug in changes made in #376 when the repositioning of the buffer. The problem appears to be in the assumption that the buffer position always starts at zero. Adding a second geo point to the buffer used in the unit test [SerializerTest#testLegacyPointSerialization](https://github.com/JanusGraph/janusgraph/blob/78bbe5aa65dc2f31e13a004fa21a213de2741cc4/janusgraph-test/src/test/java/org/janusgraph/graphdb/serializer/SerializerTest.java#L380) will cause the original implementation to fail when attempting to deserialise the second geo point. …
=> Errors deserialising Geoshape objects created by Titan

janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BaseVertexCentricQueryBuilder.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
While it is true that JanusGraph's VertexCentricQuery does not know how
to orderBy multplicity > SINGLE, this check is actually acting a red
herring.
VertexCentricIndexes are meant to either return a list of
vertexProperties or edges-- where we order and sort these returns by
either a vertex property's properties (metaproperties) or vertex's
adjacent edge's properties.
Metaproperties and edge properties are-- by construction-- inherently
single valued, i.e. we cannot store multiple values on a singular edge
property or metaproperty key.
However, you can create metaproperties and edge properties adhering to a
given JanusGraph propertyKey whose cardinality > SINGLE, i.e. equal to
LIST or SET. The current cardinality check is disallowing users to use
vertex centric indexes on these existing …
=> Remove VertexCentricQueryBuilder orderBy cardinality check

.travis.yml, analysis/Dockerfile
Fixes #466 using the the script added by @mbrukman in #467 instead of the plugin to run Coverity scans in Travis. Successfully tested by updating `COVERITY_BRANCH_NAME` in .travis.yml to point to a test branch and then pushing to same (see [build #805](https://travis-ci.org/JanusGraph/janusgraph/builds/268934336)). Travis jobs for all individual modules were skipped and the `COVERITY_ONLY` job ran the scan and uploaded results to Coverity (see [job #805.16](https://travis-ci.org/JanusGraph/janusgraph/jobs/268934352)). Some notes are below.
* As noted in #467, Coverity scan performance appears to be significantly better (e.g. 95% versus 68%) when run under Docker (specifically `centos:7`). As a result these updates include enabling Docker (`sudo: true`, `servies: docker`) and running the …
=> Use coverity-scan script in Travis

janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
Fixed enclosing transaction is closed error when multiple threads interact with graph
Fixes #422
=> Enclosing transaction is closed error fix

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> Add PR template

docs/advanced.txt, docs/migrating.txt, docs/upgrade.txt, janusgraph-cassandra/src/test/java/org/janusgraph/graphdb/CassandraGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/JanusGraphConstants.java
To fix Issue #418 added a check for the following:
1. `graph.titan-version` is set and is '1.0.0'
2. `ids.store-name` is set in LOCAL and equal to 'titan_ids'
3. `ids.store-name` is not set in GLOBAL ( as read from KCVSConfiguration )
If all the above are true then set `ids.store-name` in the overwrite modifiable configuration to be `titan_ids`. This then prevents the global configuration inheriting the default value of janusgraph_ids but only in the case where ids.store-name had not already been set.
It will now throw an exception and abort if `graph.titan-version` has been set and `ids.store-name` was not also set to the value `titan_ids` which should help preserve data integrity.
Signed-off-by: Scott McQuillan <scott.mcquillan@uk.ibm.com>
=> Failure to correctly set ids.store-name=titan_ids can corrupt a Titan Cassandra Issue #418

README.md
This use case was described recently by Ray Canzanese at a meetup in NYC:
https://twitter.com/JanusGraph/status/900459659513008128
@rcanzanese, please approve this PR to confirm that Sift Security is OK with being featured in this list. Thanks for your presentation!
=> Add Sift Security as a production user [skip ci]

janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java
Signed-off-by: Demai Ni <nidmgg@gmail.com>
=> Issue 87 - Hadoop InputFormat tests should check property values

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryV1d0.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModule.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleV1d0.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleV2d0.java, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIoTest.java
Fixes issue #420
Updated JanusGraphIoRegistry to use GraphSON 2.0 by default.
I didn't create it as JanusGraphIoRegistryV2d0 because TinkerPop 3.3 introduces a method to help determine version requirements - apache/tinkerpop#706 .
Created JanusGraphIoRegistryV1d0 to use GraphSON 1.0 for backwards compatibility.
=> Support multiple serializer versions

janusgraph-es/pom.xml
=> Set default elasticsearch.test.version to resolve build error with no ES profiles

janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/astyanax/AstyanaxStoreManager.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexFeatures.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScanner.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/EdgeSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraGraphComputer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexMemoryHandler.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/MetricsQueryExecutor.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheEdge.java, janusgraph-core/src/main/java/org/janusgraph/util/datastructures/RangeInterval.java, janusgraph-core/src/main/java/org/janusgraph/util/encoding/StringEncoding.java, janusgraph-core/src/main/java/org/janusgraph/util/system/ConfigurationLint.java, janusgraph-core/src/main/java/org/janusgraph/util/system/LoggerUtil.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLResultSetKeyIterator.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/config/job/AbstractDistCacheConfigurer.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/scan/HadoopScanRunner.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-test/src/test/java/org/janusgraph/util/LoggerUtilTest.java, janusgraph-test/src/test/java/org/janusgraph/util/StringEncodingTest.java
Also fixes some of the Fortify findings in #50 and #52 but not all the findings in those issues are fixed so the issues should remain open.
=> Resolve numerous high/medium Coverity findings

janusgraph-dist/src/assembly/static/conf/solr/schema.xml, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
Fixes #533. Also updates `SolrIndex.clearStorage()` to log an error instead of throw an exception in HTTP mode. This is so `JanusGraphFactory.drop()` still completes cleanly in this case. Cores are created externally in Solr HTTP so it's necessary/logical that they must also be deleted externally.
=> Use legacy SpatialContextFactory path in solr module for backwards compatibility

RELEASING.md
so that the sources are attached and published.
Fixes #470
This is a documentation change only since the snapshots are pushed manually, and the [current 0.2.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/janusgraph/janusgraph-core/0.2.0-SNAPSHOT/) has source attached.
=> Include janusgraph-release profile when deploying snapshots [skip ci]

janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexMutation.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/cache/KCVEntryMutation.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraGraphComputer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/ConditionUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/ElementHelper.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/config/HadoopConfiguration.java
Relates to #535. Previous attempt to resolve this finding category using `Preconditions.checkNotNull` (see b9e83bd56dc90d57d4e84c0c96fe649bf6787488) did not work. This PR updates to instead remove the `@Nullable` annotations and revert the `Preconditions.checkNotNull` calls.
=> Remove inaccurate nullable annotations to resolve Coverity findings

docs/configuredgraphfactory.txt, janusgraph-core/src/main/java/org/janusgraph/core/ConfiguredGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphManagerUtility.java
This allows us to avoid `NoClassDefFoundError` errors when users do not
require the optional gremlin-server dependency.
Issues: #565
=> Introduce JanusGraphManagerUtility#getInstance

janusgraph-dist/pom.xml, janusgraph-hadoop-parent/pom.xml
Excluding org.eclipse.jetty.orbit:javax.servlet which was causing conflicts with other servlet dependencies.
This commit resolves issue #605 605.
=> Excluding conflicting servlet dependencies

docs/bigtable.txt
After PR #592, the user does not need to add any additional binary
dependencies to their JanusGraph build. This change updates the docs to
clarify this; should have been included in the same PR.
/cc: @igorbernstein2
=> No extra binary deps needed for Bigtable [skip ci]

janusgraph-all/pom.xml
Fixes #640.
The comment which hides Solr says that the dependency is not valid because it
requires Hadoop 2 while TinkerPop 3 only works with Hadoop 1.
JanusGraph currently depends on TinkerPop 3.2.6; per the docs:
http://tinkerpop.apache.org/docs/3.2.6/upgrade/
"Hadoop1 is no longer supported. Hadoop2 is now the only supported Hadoop
version in TinkerPop."
Thus, it should be safe to uncomment this dependency.
-----
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …
=> Fixes #640: uncomment the Solr dependency.

docs/changelog.txt
This is the only file that marks XML code snippets with `m2` rather than `xml`
and is not properly highlighted in the HTML output as a result.
=> Fix syntax highlighting for XML. [skip ci]

pom.xml
Update netty version to 4.0.52 to fix a warning during connecting to the
Cassandra backend using cql. The warning is "Found Netty's native epoll
transport in the classpath, but epoll is not available. Using NIO instead.",
unable to find io/netty/channel/epoll/EpollDatagramChannel$DatagramSocketAddress.
The stable netty 4.0.52 doesn't produce the warning therefore would lead to
better performance.
Signed-off-by: chinhuang007 <chhuang@us.ibm.com>
=> Update netty version to 4.0.52

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchSetup.java
The ES RestClient does [not
support](https://github.com/elastic/elasticsearch/issues/21789#issuecomment-263243530)
a per request timeout configuration, however it does at least support a
timeout configuration option `maxRetriesInMillis` that will timeout the
overall request, including retries. It can be useful for others to
configure this timeout, especially given the fact that users can
configure their gremlin-script-execution timeout.
Issues: #688
=> Create ES ConfigOption MAX_RETRIES_IN_MILLIS

janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MultiKeySliceQuery.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
Issue: #648 
Signed-off-by: Kim Pang Lei <ckplei@gmail.com>
=> Issue 648 - avoid excessive array list resizing 

janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/vertexcache/GuavaVertexCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/AbstractVertex.java
Since the Guava cache [processes its removals
asynchronously](https://github.com/google/guava):
"""
Caches built with CacheBuilder do not perform cleanup and evict values
"automatically," or instantly after a value expires, or anything of the
sort. Instead, it performs small amounts of maintenance during write
operations, or during occasional read operations if writes are rare.
The reason for this is as follows: if we wanted to perform Cache
maintenance continuously, we would need to create a thread, and its
operations would be competing with user operations for shared locks.
Additionally, some environments restrict the creation of threads, which
would make CacheBuilder unusable in that environment.
"""
there is a chance that we reach the onRemoval code _after_ the vertex
being removed …
=> Check if vertex tx open on cache removal

.github/PULL_REQUEST_TEMPLATE.md
Also adds a horizontal line at the top of the template so that it
cleanly separates itself from the user's commit for readability (they've
been previously running into each other, which is distracting and
confusing.
Also made a few minor formatting changes in terms of whitespace
elimination, punctuation, etc.
-----
- [] Is there an issue associated with this PR? Is it referenced in the commit message?
- [] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [] Is your initial contribution a single, …
=> Add `[skip ci]` instructions for docs changes.

docs/elasticsearch.txt, janusgraph-es/pom.xml, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchSetup.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/util/BasicAuthHttpClientConfigCallback.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/util/HttpAuthTypes.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/util/RestClientAuthenticator.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/util/RestClientAuthenticatorBase.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/util/SSLConfigurationCallback.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/util/BasicAuthHttpClientConfigCallbackTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/util/SSLConfigurationCallbackTest.java
Fixes #645 and #612: multiple changes for ES REST transport settings
- refactor client set-up code to make it more testable
- extract REST client set-up logic to a separate class
- add a set of unit tests for client configuration
- add new options for enabling SSL (e.g. HTTPS) for the client (off by
default) and optionally configuring SSL trust store and its password
- implement HTTP basic authentication
- implement support for custom HTTP authenticator callback - to be used
externally for other authentication types such as AWS SigV4
NOTE: This PR is primarily for preview purposes, to get the sense if the approach selected is not out of the line. If it is acceptable in general, I will update the documentation and resubmit.
=> HTTPS, HTTP Basic auth and custom authentication support (#612, #645)

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
Make CQL PoolingOptions be configurable by adding the following new
properties under `storage.cql` :
- local-core-connection-per-host:
The number of connections initially created and kept open to each host
for local datacenter
- local-max-connection-per-host:
The maximum number of connections that can be created per host for
local datacenter
- local-max-request-per-connection:
The maximum number of requests per connection for local datacenter
- remote-core-connection-per-host:
The number of connections initially created and kept open to each host
for remote datacenter
- remote-max-connection-per-host:
The maximum number of connections that can be created per host for
remote datacenter
- remote-max-request-per-connection:
The maximum number of requests per connection for remote datacenter …
=> Add configuration props for CQL PoolingOptions

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/VertexIDAssigner.java
One of the two threadpools opened in VertexIDAssigner is never shutdown. This came up in my case when running JMH benchmarks. At the end of the benchmarks the threads would still be around after a close was issued.
-------------------------
=> Closing partitionVertexIdPool when VertexIDAssigner is closed

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/VertexIDAssigner.java
Revert JanusGraph/janusgraph#667 which broke tests; see [this build](https://travis-ci.org/JanusGraph/janusgraph/builds/314003162), specifically [this job](https://travis-ci.org/JanusGraph/janusgraph/jobs/314003169).
=> Revert PR #667 "Closing partitionVertexIdPool when VertexIDAssigner is closed"

.travis.yml
Instead of using `$COVERITY_SCAN_BRANCH` which isn't used anywhere else in this
script, be more consistent and use `$TRAVIS_BRANCH` and `$COVERITY_BRANCH_NAME`.
Context: https://github.com/JanusGraph/janusgraph/pull/761#discussion_r153380194
-----
- [] Is there an issue associated with this PR? Is it referenced in the commit message?
- [] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …
=> Use Coverity/Travis vars consistently [skip ci]

.travis.yml
Use `group: travis_latest` instead of `dist: trusty` to pick up the latest
Travis CI image changes. The new default is `group: travis_lts` which is
equivalent to the now-deprecated `dist: trusty`.
More info in this blog post:
https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images
Fixes #811.
-----
- [] If applicable, have you updated the LICENSE.txt file, …
=> Switch to Travis CI latest image versions.

docs/configuredgraphfactory.adoc
`org.JanusGraph` is incorrect; should be `org.janusgraph` instead.
Fixes #825.
-----
- [] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?
tag to the first line of your commit …
=> Fix case of JanusGraph packages in docs. [skip ci]

.travis.yml, .travis.yml.cassandra
Also updates `.travis.yml.cassandra` to use the latest Travis CI images group.
Copyright header addition relates to issue #14.
-----
- [] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this …
=> Add copyright header to Travis CI config [skip ci]

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-solr/src/test/resources/solr/core-template/schema.xml, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
Elasticsearch backend fails to add value to list property if that property doesn't already exist
Issue : 718
-----
=> Fix the issue when search backend fails to update a document.

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStep.java, janusgraph-test/src/test/java/org/janusgraph/blueprints/process/traversal/strategy/optimization/JanusGraphStepStrategyTest.java
This PR addresses Issue #723 .
foldInIds now correctly leaves other hasContainers intact so that additional predicates are enforced.
-----
=> Issue #723: hasId short-circuits following steps

.travis.yml, docs/basics.adoc, janusgraph-all/pom.xml, janusgraph-server/pom.xml, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/HMACAuthenticator.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/JanusGraphAbstractAuthenticator.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/JanusGraphSimpleAuthenticator.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/SaslAndHMACAuthenticator.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/handler/HttpHMACAuthenticationHandler.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/handler/SaslAndHMACAuthenticationHandler.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/HMACAuthenticatorTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/JanusGraphSimpleAuthenticatorTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/SaslAndHMACAuthenticatorTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/handler/HttpHMACAuthenticationHandlerTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/handler/SaslAndHMACAuthenticationHandlerTest.java, janusgraph-server/src/test/resources/log4j.properties, pom.xml
Issue: #623
This addresses a few concerns.
1) Configure a credential graph that automatically creates the appropriate JanusGraph specific indexes.
2) TinkerPop now supports (as of 3.2.6 and 3.3.0) a combined channelizer
for enabling port unification for WebSockets and HTTP. This adds the
necessary classes to enable authentication for one, the other, or both
using JanusGraph specific authentication.
3) HTTP Basic Auth is (and should be) slow. This adds an HMAC token
authentication mechanism to allow for fast authentication over HTTP.
- [ N/A] If adding new dependencies to the code, are these dependencies licensed in a way that is …
=> Add JanusGraph specific authentication.

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStep.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-test/src/test/java/org/janusgraph/blueprints/process/traversal/strategy/optimization/JanusGraphStepStrategyTest.java
Issue #252 
With @severin83's help, the HasStepFolder has been updated to fold Janus compatible global ordering operations into JanusGraphSteps.
This re-enables the pushdown of ordering operations into indexing backends.
-----
=> Issue #252: order().by(property) doesn't work with mixed index

analysis/coverity-scan.sh
Fixes #860. The Coverity build has errors processing a number of JanusGraph source files and it appears that this can impact the analysis of other files in the same module. This is problematic in janusgraph-core because it results in a loss of 55% of source files, which fails the Coverity build.
This PR reconfigures Coverity to skip the 16 offending files in janusgraph-core. Skipping these files allows the other 561 files (97%) to be analyzed. The Coverity [build errors](https://github.com/JanusGraph/janusgraph/files/1598228/coverity_errors.txt) themselves do not map to javac errors/warnings nor do they appear to be code issues that can be addressed in JanusGraph. These issues have been raised to the Coverity team (see below).
> On Mon, Jan 1, 2018..., sjudeng <***> wrote:
> 
> I was able …
=> Fix Coverity build

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-test/src/test/java/org/janusgraph/blueprints/process/traversal/strategy/optimization/JanusGraphStepStrategyTest.java
Issue #855 
Updated strategy to only fold in first id lookup into JanusGraphStep to match TinkerPop reference behavior.
@sjudeng can you double check this if you get a chance? I tracked the failing test down to us folding all the ids in which in a sense makes sense to me, but doesn't line up with the TinkerPop process suite and TinkerGraph GraphStep optimizations.
-----
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as …
=> Issue #855: hasId optimization updates broke TinkerPop g_V_hasIdX1X_hasIdX2X process test

janusgraph-core/src/main/java/org/janusgraph/core/attribute/JtsGeoshapeHelper.java, janusgraph-test/src/test/java/org/janusgraph/core/attribute/JtsGeoshapeHelperTest.java
To ensure a polygon is closed, its first point and last point should be equal.
=> Check whether a polygon is closed or not

docs/basics.adoc, docs/reindex.adoc, janusgraph-all/src/main/java/org/janusgraph/graphdb/tinkerpop/plugin/JanusGraphGremlinPlugin.java
=> Make static reference to ManagementSystem.awaitGraphIndexStatus

docs/configuredgraphfactory.adoc, janusgraph-all/src/main/java/org/janusgraph/graphdb/tinkerpop/plugin/JanusGraphGremlinPlugin.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/management/JanusGraphManager.java, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml, janusgraph-server/conf/janusgraph-server-integration.properties, janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphChannelizer.java, janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphHttpChannelizer.java, janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphNioChannelizer.java, janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphWebSocketChannelizer.java, janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphWsAndHttpChannelizer.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/AbstractGremlinServerIntegrationTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphChannelizerTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/TestClientFactory.java, janusgraph-server/src/test/resources/org/janusgraph/graphdb/tinkerpop/gremlin-server-integration.yaml
=> Bind all graphs to gremlin executor context

docs/configuredgraphfactory.adoc, janusgraph-core/src/main/java/org/janusgraph/core/ConfiguredGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/GraphCacheEvictionAction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementLogger.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/StandardSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/management/JanusGraphManager.java, janusgraph-test/src/test/java/org/janusgraph/core/ConfiguredGraphFactoryTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/management/ManagementLoggerGraphCacheEvictionTest.java
When a graph configuration is updated or removed from the
ConfigurationGraphManagement, the related graph is evicted from the
cache on all JanusGraph nodes in the cluster. This is done to prevent
users from opening graphs with old/incorrect configurations across the
cluster and finding themselves in an inconsistent state. Note that this
is only done for users updating the ConfigurationManagementGraph by
going through the ConfiguredGraphFactory APIs; this is done for two
reasons: 1. to allow more fine-tuned control for users who wish to use
the lower-levls CMG APIs and 2. to avoid a cyclical dependency between
the CMG and the JanusGraphManager.
Issues: #590
-----
In order to streamline the review of …
=> Evict graph from cache upon configuration updates

docs/monitoring.adoc
Fix parameter name per issue #962 [skip ci]
fixes #962 
-----
=> Fix parameter name per issue #962 [skip ci]

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/UUIDSerializer.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/database/serialize/attribute/UUIDSerializerTest.java
Issue #948
As far as I can tell, supporting "native sort order", as described in
the docs, simply means implementing `Comparable`, which UUID certainly
does. This adds support for using a UUID value in a Vertex Centric
Index.
Signed-off-by: Keith Lohnes <lohnesk@gmail.com>
-----
- [ X ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ X ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ X ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ X ] Is your initial contribution a single, squashed commit?
- [ X ] …
=> Add OrderPreservingSerializer on UUIDSerializer

docs/basics.adoc, janusgraph-core/src/main/java/org/janusgraph/core/Connection.java, janusgraph-core/src/main/java/org/janusgraph/core/EdgeLabel.java, janusgraph-core/src/main/java/org/janusgraph/core/VertexLabel.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/DefaultSchemaMaker.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/SchemaManager.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/StandardEdge.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardTransactionBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/TransactionConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/TypeDefinitionCategory.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/VertexLabelVertex.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/system/BaseLabel.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/system/BaseVertexLabel.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/typemaker/DisableDefaultSchemaMaker.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/EdgeLabelVertex.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/inmemory/InMemoryGraphTest.java
Fixes #880.
* Extension and usage of SchemaMaker
* Connection constrains are defined using two schema edges, one between out and in Vertex and one between the edge and out vertex. The first edge has a property with the label of the edge. 
Create a new SchemaVertex for a connection and make edges to an out-VertexLabel, an in-VertexLabel, and EdgeLabel. This alternative would allow to remove an extra step during an update, if an EdgeLabel is renamed.
----
Please ensure that once the PR is …
=> Fixes #880: Add property and connection constraints

janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/BerkeleyMultiQueryGraphProvider.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyMultiQueryJanusGraphProcessTest.java, janusgraph-cassandra/src/test/java/org/janusgraph/blueprints/thrift/ThriftMultiQueryGraphProvider.java, janusgraph-cassandra/src/test/java/org/janusgraph/blueprints/thrift/process/ThriftMultiQueryProcessTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphLocalQueryOptimizerStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphVertexStep.java, janusgraph-cql/src/test/java/org/janusgraph/blueprints/cql/CQLMultiQueryGraphProvider.java, janusgraph-cql/src/test/java/org/janusgraph/blueprints/cql/process/CQLMultiQueryProcessTest.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/blueprints/HBaseMultiQueryGraphProvider.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/blueprints/process/HBaseMultiQueryProcessTest.java, janusgraph-test/src/test/java/org/janusgraph/blueprints/InMemoryMultiQueryGraphProvider.java, janusgraph-test/src/test/java/org/janusgraph/blueprints/InMemoryMultiQueryJanusGraphProcessTest.java
Storage adapter tests were added to exercise all backends in `query.batch` mode.
The `JanusGraphLocalQueryOptimizerStrategy` was updated to disable multiquery on Janus specific steps that are nested within `RepeatStep`, `MatchStep`, and `BranchSteps`.
These steps cause difficulties with the barrier step nature of the batched query multiquery enabled steps. We should still be able to get at least some level of batched backend retrieval working with these but it will be a more involved effort. The intent of this PR is to un-break the `query.batch` option for users and to allow them to benefit from the decreased latencies in other common query patterns and to lay down a foundation for testing out further multiquery optimizations.
-----
In order to …
=> Issue #71: Various Gremlin query patterns throw NPE when query.batch=true

docs/basics.adoc
fixes #151 
for the example below, I'm not sure if there's a more direct method of referencing the graph without opening it to be able to skip the close() step. Either way suggesting that the graph.close() be run prior isn't a bad thing.
```
+graph = def graph=ConfiguredGraphFactory.open("example");
+graph.close();
+org.janusgraph.core.util.JanusGraphCleanup.clear(graph)
```
-----
Please ensure that once the PR is submitted, you check Travis CI …
=> Adding documentation on dropping databases [skip ci]

AUTHORS.txt, CONTRIBUTORS.txt, docs/basics.adoc, docs/directindex.adoc, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexProvider.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchIndexTest.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneIndexTest.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexTest.java
Fixes #777 
Replace spaces in property names with an obscure unicode character in mapKey2Field() so that external indexing backends (Lucene, ElasticSearch, Solr) that disallow spaces in field names can still index those properties.
Added unit tests for all 3 backends and tested with a production ES index.
Also added another commit to update AUTHORS.txt and CONTRIBUTORS.txt to reflect this PR and 260e6fc7bb54f818a10f4c34938a512ebfaf22cc.
I'm targeting the 0.2 branch because for our use of JanusGraph this is a blocking bug, and so it would be quite nice to have it in an 0.2.1 release so we don't have to keep using our own snapshot build.
Since this was my first attempt at contributing, I'll note a couple interesting things I discovered:
- The ES tests (at least) don't run correctly on …
=> Fix #777: Allow external indexing of properties with spaces

docs/migrating.adoc, docs/upgrade.adoc, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
Signed-off-by: Scott McQuillan <scott.mcquillan@uk.ibm.com>
-----
**Note:** This pull request is targeted at 0.2 and replaces #977 which had been targeted at master 
This pull request has been raised following the discussions around pull request #843 the suggested fix for which would not have worked as expected, as it would have caused JanusGraph to create a second ID store named `janusgraph_ids` in addition to the existing one created by Titan and named `titan_ids`. 
Given that you must first populate Cassandra with data from Titan in order to reproduce the problem I wasn't able to create a unit test. But here's a walk through of how to re-create the problem:
```
gremlin>  graph = TitanFactory.open('conf/titan-cassandra.properties')
==>standardtitangraph[cassandrathrift:[127.0.0.1]] …
```
=> Only check the global configuration for graph.titan-version

README.md
Seeq is no longer using JanusGraph in production.
-----
- [/] Is there an issue associated with this PR? Is it referenced in the commit message?
- [/] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [/] Have you ensured that format looks appropriate for the output in which it is rendered?
- [/] If this PR is a documentation-only change, have you added a `[skip ci]`
=> [skip ci] Remove Seeq from the JanusGraph readme

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModule.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleV2d0.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleTest.java
This adds GraphSON support for JanusGraph predicates (Text and Geo) which is necessary to use them in GLVs.
I only implemented this for GraphSON 2 as it looks like GraphSON 3 currently doesn't even work with the default TinkerPop predicates (`P.within()`, `P.gt()`, ...). At least the test I added for that (`testTinkerPopPredicatesAsGraphSON`) fails with GraphSON 3 independent of my code changes.
Would be good to hear from someone with more knowledge of JanusGraph I/O if I'm doing something wrong here. When there are more problems with GraphSON 3 then a separate PR for that might be a good idea but I marked this PR as WIP until that has been clarified.
Issue: #1060
-----
to ensure the …
=> Add GraphSON 2 support for JanusGraph predicates #1060

janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleTest.java
Turned out that GraphSON 3.0 support was already there with the usual `JanusGraphIoRegistry`. The tests I added in my PR to add support for GraphSON deserialization of predicates (#1061) for some reason just didn't work with GraphSON 3.0 the way I implemented them. It looked like the `RequestMessage` wasn't serialized correctly. So I changed the tests to simply serialize `Bytecode` directly instead and that worked immediately with GraphSON 3.0.
To make sure that GraphSON 3.0 really works completely I tested it manually by connecting with Gremlin.Net and GraphSON 3 configured and I could execute several traversals without any problems, also some that included the new `g:Map` type that wasn't present in GraphSON 2.0.
To ensure that users can utilize GraphSON 3.0 directly when they start the …
=> Enable GraphSON 3.0 support by default #1075

janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/AbstractTypedRelation.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
Issue #1066 
1.  getOrCreatePropertyKey was getting called without the value and hence the code in the following file was not getting executed - [JanusGraphDefaultSchemaMaker.java#L44](https://github.com/JanusGraph/janusgraph/blob/037f8af5471f5e0a2becc2cb331c822936e7d01a/janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphDefaultSchemaMaker.java#L44). This resulted in the edge properties not having automatic type detection.
2. Added JUNIT tests for vertex and edge properties to verify auto data type detection
Signed-off-by: Prithvi Nambiar <prithvinambiar@gmail.com>
-----
tag to the first line of your commit message …
=> Issue #1066 - Fixed automatic type detection issue for edge properties

docs/basics.adoc, docs/cassandra.adoc, docs/configuredgraphfactory.adoc, docs/exampleconfig.adoc, docs/hadoop.adoc, docs/intro.adoc, docs/reindex.adoc, docs/solr.adoc, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-configurationgraph.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-es.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-solr.properties, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql.properties, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/janusgraph-cql-es-server.properties, pom.xml
Fixes #1023
* Added compact storage option for Cassandra 2 and earlier only. Default is to use compact storage when using Cassandra 2 and earlier, maintaining the previous behavior.
* Updated docs to prefer CQL over Thrift going forward.
* Updated to Cassandra 2.1.20.
-----
=> No longer use COMPACT STORAGE for Cassandra 3+ with CQL backend

docs/appendices.adoc, docs/doc-versions.adoc, docs/static/css/docs.css, docs/xsl/common.xsl
I created a page with links to all the available documentation folders and added it to the appendices. I also replaced the other versions link that pointed to the releases page with a dropdown to switch between doc versions. If you click on Other Doc Versions it will take you to the new Appendix E, Other documentation versions.
Open issue is in the [docs repo](https://github.com/JanusGraph/docs.janusgraph.org/issues/22) 
[Preview available here](https://chupman.github.io/docs.janusgraph.org/latest/index.html)
Currently the changes can only be seen from the 0.3.0-SNAPSHOT or latest url. The changes will need to be backported into all the branches we plan to host documentation for. Also right now the version links are hardcoded in …
=> Adding dropdown for versions

.travis.yml
After opening an issue, travis-ci/travis-ci#10111, it was pointed out that a space was getting placed before the mvn commands. 
I verified the fix on my [fork](https://travis-ci.org/chupman/janusgraph/builds/427963484)
-----
=> formatting fix to resolve travis-ci failures

janusgraph-core/src/main/java/org/janusgraph/graphdb/management/JanusGraphManager.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphChannelizerTest.java
Fixes issue #1200  
@dpitera When a new graph is created using the JanusGraphManager, the graph and its traversal source are added to the script engine's global variable bindings, but the traversal is not added to the graph manager's map of registered traversal sources; this prevents a client from creating a remote traversal object (using `GraphTraversalSource.withRemote()`) or from creating an aliased Gremlin Server client (using `Client.alias()`). This PR addresses that.
(Aside) I'm just getting the CLA process started on my end, so it may be some time for that to get addressed.
Signed-off-by: Paul Khermouch <paul.khermouch@civitaslearning.com>
-----
to ensure the following steps …
=> Issue #1200: Update traversal source map in JanusGraphManager when new graph is dynamically created

.gitignore, NOTICE.txt, docs/solr.adoc, janusgraph-solr/pom.xml, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/apache/solr/cloud/ConfigurableMiniSolrCloudCluster.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/MiniKDC.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexKerberosKeytabTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexKerberosMissingConfigTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrRunner.java, janusgraph-solr/src/test/resources/solr/jaas_keytab.conf
Fixes issue #1138.
Signed-off-by: Christopher Jackson <chris.jackson@us.ibm.com>
-----
=> Add support for kerberized solr instance (#1138)

pom.xml
I added 0.2.2 in addition to 0.2.1 so that if people create a 0.2.2 graph and then test it with a future snapshot build they won't hit the error. mentioned in #1285 
-----
=> Added graph versions 0.2.1 and 0.2.2 to compatible-versions

janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrRunner.java
Signed-off-by: Jerry He <jerryjch@apache.org>
Fixes #1165 
Fixed two things:
1.  The solr.zookeeper-url option should be String[] instead of String. See #1165 for error details.
2.  Fixed MapReduceIndex job's use and conversion of the String[] properties.
-----
=> Support list for Zookeeper URL for Solr cloud and index job #1165

BUILDING.md
I was building the container while reviewing a PR and thought it would be great to include instructions on how to use a release distribution since it can be a lot faster. 
I also brought in the update from this [commit](https://github.com/JanusGraph/janusgraph/commit/93ccb0dc10bc82ceee574a8887f2ecf6204bc3d4#diff-396d0b75211f5646b2fa730fbdf80a40) since I think it should have been targeted at the 0.2 branch originally.
-----
Please ensure that once …
=> [skip ci] Added instuctions on building a docker image from dist

janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/SubqueryIterator.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
This fix makes sure that we only apply limit to the query result stream when it is safe to do without a risk of losing valid results. 
Also includes a new unit test which illustrates the issue being fixed in a way easier to reproduce than originally reported on the issue #1125.
=> fixing issue #1125 premature limit application when using multiple indexes in graph query

.travis.yml
We only allowed them because they used to time out from time to time, but that doesn't seem to be the case any more.
This could have been a CTR commit, but I created a PR in case anyone has a good reason for keeping these Cassandra tests as allowed failures.
Fixes #1433
-----
- [-] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the …
=> Stop allowing CI test failures for Cassandra

janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/HMACAuthenticator.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/JanusGraphAbstractAuthenticator.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/JanusGraphSimpleAuthenticator.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/ConfigBuilder.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/CredentialsBuilder.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/HMACAuthenticatorTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/HmacConfigBuilder.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/JanusGraphAbstractAuthenticatorTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/MockedHmacAuthenticatorFactory.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/MockedJanusGraphAuthenticatorFactory.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/MockedSaslAndHmacAuthenticatorFactory.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/MockedSimpleAuthenticatorFactory.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/SaslAndHMACAuthenticatorTest.java
TinkerPop [deprecated](http://tinkerpop.apache.org/docs/3.4.0/upgrade/#_credential_dsl_changes) the old `CredentialGraph` with version 3.3.3 and it will be removed completely in version 3.4.0. Instead, the new Credential traversal DSL should be used.
So, this is a precondition for the upgrade to TinkerPop 3.4.0.
The tests made extensive use of mocking of the `CredentialGraph` which is now not possible any more. Since they were quite complex in general and contained a lot of duplicated code, I decided to refactor them completely instead of trying to fix them as that would have been probably even more work.
During the refactoring of the tests I also noticed some minor issues in the code which I also fixed.
I tested manually that authentication with the `JanusGraphSimpleAuthenticator` still …
=> Use new Credential DSL for authentication #1364

janusgraph-core/src/main/java/org/janusgraph/core/InvalidElementException.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategy.java
The following methods were deprecated in TinkerPop 3.3.z and removed in TinkerPop 3.4.0:
- `org.apache.tinkerpop.gremlin.structure.Element.Exceptions#elementAlreadyRemoved(Class, Object)`
- `org.apache.tinkerpop.gremlin.process.traversal.step.util.HasContainer#makeHasContainers(String, P)`
I just inlined these methods in the two places where they were called.
There were two more deprecated methods we're using that were removed in TinkerPop 3.4.0, but we can only remove them together with the upgrade to 3.4.0 as they're part of the `GraphManager` interface until 3.4.0, so we still have to implement them until 3.4.0:
- `org.apache.tinkerpop.gremlin.server.GraphManager#getGraphs()`
- `org.apache.tinkerpop.gremlin.server.GraphManager#getTraversalSources()`
Part of #1364
-----
Thank you for …
=> Stop using deprecated TinkerPop methods for upgrade to TinkerPop 3.4.0 #1364

janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilder.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilderTest.java
This PR is related to a flow to improve test coverage of the old `GraphDatabaseConfiguration`.
-----
=> Cover ReadConfigurationBuilder with unit tests

janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyOperationCountingTest.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java
Part of #1459
The test is still flaky so it doesn't fix the issue. This just ensures that the flaky test doesn't break the build.
-----
- [-] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of …
=> Mark Flaky Berkeley test as flaky

janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/StandardVertex.java
Hi,
Based on the comment by @FlorianHockmann for PR #1334 I am creating a new pull request on top of the 0.2 branch. Sorry if this is not the correct way to do it but I'm not a git expert and I couldn't figure out how to update the existing pull request.
Just merge this one and I can delete the other one I guess.
Fixes #1333 
Thanks,
Mike
---
Created a new mutex to lock during the updateLifyCycle method. Not sure what the origional intention of having this method be synchronized was,
but this should ensure the behavior is the same without the risk of
deadlock.
Also marked lifecycle as volatile since it can be updated and read by
different threads.
Signed-off-by: Mike Beaubien <mbbeaubi@umich.edu>
----- …
=> Prevent deadlock when vertices are removed in parallel

.travis.yml, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/AbstractTypedRelation.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheVertexProperty.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
The vertex equality check in `AbstractTypedRelation` was used to check whether the vertex was already loaded in the current transaction. This check only works if both objects are actually the same, e.g., with
`v == v.it()`. `v.eqauals(v.it())` doesn't work as it is always true because equals() only checks whether the ids are equal. So, this check cannot be used to check whether the vertex was loaded in the transaction.
The broken check whether the relation was already loaded resulted in failures when a relation was removed in a different transaction than the transaction the relation was loaded in. This led to the TinkerPop test failures.
This reverts PR #1118 basically which introduced this problem. The `StackOverflowError` that was fixed by PR #1118 is now instead fixed by removing the …
=> Fix removal of relations in other transaction

janusgraph-dist/janusgraph-dist-hadoop-2/Dockerfile
In this commit i also incorporated a small fix to the overall size by removing the zip file after extraction.
Retargeted modifictation for janusgraph 0.2 branch.
=> #1261 Makes Janusgraph docker run as a non-privileged user

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchIndexTest.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
This PR makes equal queries correctly work for string fields with dual mapping. Related issue: #1477
-----
=> Fix equals queries for dual-mapped string fields

janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphMultiVertexQuery.java, janusgraph-core/src/main/java/org/janusgraph/core/Transaction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/MultiVertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphEdgeVertexStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphLocalQueryOptimizerStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphPropertiesStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphVertexStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
Signed-off-by: Scott McQuillan <scott.mcquillan@uk.ibm.com>
Pull request  to un-deprecates multiQuery for issue #984 
In addition it adds an optimisation to use multiQuery to pre-fetch properties for multiple vertices into the cache if the next step of the query is a `has` step. For queries following large number of edges this eliminates many network trips to the storage backend for the vertex properties and can give significant performance improvements, see the issue for an example.
-----
- [x ] Is your initial contribution a single, squashed commit?
Travis CI …
=> Un-deprecate multiQuery #984 and pre-fetch properties to cache

janusgraph-cql/pom.xml, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-dist/src/assembly/static/conf/hadoop-graph/read-cql.properties, janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryRecordReader.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cql/CqlInputFormat.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/CqlInputFormatIT.java, janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/cql-read.properties, janusgraph-hadoop-parent/pom.xml
This adds a `CqlInputFormat` to enable Spark with CQL without relying on Thrift any more.
@farodin91 and I worked together on this one.
We already tested this in production with our graph with ~250 M vertices and could successfully execute some traversals on our Scylla backend with Spark.
Fixes #985.
-----
- [-] If …
=> Support CQL for OLAP

janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/CacheVertex.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/vertices/CacheVertexTest.java
I spent a couple hours digging into this issue today. I went through and confirmed that the new test [will fail](https://travis-ci.org/chupman/janusgraph/jobs/532023315) without the  code change. 
Fixes #357. Includes the commit from PR #362. Also includes the commit with the test created by @sjudeng.
[link to the test.](https://github.com/sjudeng/janusgraph/commit/c0df7b6f1a1a6083a11e9ac32961be1ba5255ef4) 
-----
- [] Is your initial contribution a single, squashed commit?
Please ensure that …
=> Repackaging of PR 362 NPE fix and test

janusgraph-dist/src/assembly/static/bin/gremlin-server.sh
fixes an unfinished task on #845 
I combined the best of our current `gremlin-server.sh`, `janusgraph.sh` and Tinkerpop's `gremlin-server.sh` script to make a supergroup equivalent  of a service wrapper.
-----
=> Improve gremlin-server.sh with start/stop support.

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
fixes #1595 
I added a default of true to `CF_COMPACT_STORAGE` to match its description and fix it returning null in Cassandra 3. I also added a conditional to `testUseCompactStorage()` that compact storage should only be enabled if the Cassandra version is less than 3.
I ran this update using the [.travis.yml.cassandra](https://travis-ci.org/chupman/janusgraph/builds/535092253) config in my fork to verify the fix. 
[Here's the failed CI build](https://travis-ci.org/chupman/janusgraph/builds/534967897) that originally alerted me to the issue for reference. 
-----
tag to the first line of …
=> Fix default option for CF_COMPACT_STORAGE and test in cassandra >= 3

.travis.yml
Removed `\`s for long line since it's already handled by `yaml` and it was just breaking commands. Also broke up some long lines. 
At least fixes the command not found issue in #1599 
-----
=> fixed breaking whitespace issue in .travis.yml for coverity job

pom.xml
To correctly proceed with the release process we should exclude `pom.xml.releaseBackup` files generated by `mvn clean release:prepare` from headers checking.
This problem was introduced in #1411 
-----
=> Exclude xml.releaseBackup files from headers check

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
…able build-in locking mechanism in JanusGraph for the case when locking is already provided by the application.
This allows to improve performance of underlying storage (Cassandra in our case) and doesn't make it perform redundant read-before-write operation for each column participated in transaction.
Fixes #1636
-----
=> external-locking configuration parameter for CQL #1636

janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/thrift/CassandraThriftKeyColumnValueStore.java
The method `convertException` in `CassandraThriftKeyColumnValueStore` was always throwing a `PermanentBackendException` even when it should have thrown a `TemporaryBackendException`, so that the operation could be retried.
This is because `TimedOutException` and `UnavailableException` (which are supposed to throw `TemporaryBackendException`) both extend `TException`.
The `if (e instanceof TException)` is not needed at all as at the end of the method there is already
```
else {
return new PermanentBackendException(e);
}
```
Signed-off-by: Marco Scoppetta <marco@grakn.ai>
-----
tag to the first line of your commit message to avoid spending …
=> Fix convertException in CassandraThriftKCVStore

janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/vertexcache/GuavaVertexCache.java, janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
The idea is to included deleted vertices in the `GuavaVertexCache` volatile map, in addition to  modified vertices. It can currently appear that `.remove()` operations can be lost on vertices.
To see this, take the following example: Obtain an instance of `CacheVertex` `V`, and delete it. Do a bunch of other read operations that fill the `GuavaVertexCache` and evicts our vertex `V`. When re-reading `V`, we get a new `CacheVertex` instance for which `V.isRemoved()` is `false`.
Happy to include a unit test if the community deems necessary and agrees with this change.
-----
Please ensure that once the PR is submitted, you check Travis CI for build …
=> Ensure deleted Elements remain in volatile tx cache map

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchRequest.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/AbstractESCompat.java
- Disables source retrieval
- Prevents unnecessary object creation with `Optional.ofNullable()`
Fixes #1651
-----
=> Disable source retrieval by default on ElasticSearch

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchConstants.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/AbstractESCompat.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/ES6Compat.java
Now painless scripts are parametrized and won't be compiled on every update and as a result load on ElasticSearch will be lower.
Fixes #1702 
-----
=> Improved support of ElasticSearch 6 by refactoring usage of painless scripts functionality

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchResponse.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/AbstractESCompat.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestCountResponse.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestSearchResponse.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchConfigTest.java
We only need total hits for `vertexTotals`, `edgeTotals`, `propertyTotals` index requests.
- Optimizes totals to run not a `search` query but `count` query
- Optimizes search queries which don't need Search API to not count total hits at all
Fixes #1679
-----
=> Optimize ES queries to not count total hits for all requests

docs/advanced-topics/serializer.md, docs/index-backend/field-mapping.md
Additional serializers and custom ES parameters were already in `v0.4.0`. That is why we don't need to show redundant notes when the user is looking for `v0.4` docs.
-----
=> Remove v0.3 specific doc notes [doc only]

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLResultSetKeyIterator.java
Fixes: #1813 
Fix to add a level of paging above the CQL driver to prevent OOM issus when performing reindexing operations.
Signed-off-by: Ted Wilmes <ted.wilmes@experoinc.com>
-----
=> Fix for reindexing OOM issue with CQL backend

docs/basics/janusgraph-cfg.md, docs/changelog.md, docs/storage-backend/bdb.md, janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java
When I want create two instance of berkeleydb with default configuration it lead to out of memory - default configuration 60% memory for instance
I can't proper set [MAX_MEMORY_PERCENT](https://docs.oracle.com/cd/E17277_02/html/java/com/sleepycat/je/EnvironmentConfig.html#MAX_MEMORY_PERCENT) because number of instance is unknown
Bdb has [SHARED_CACHE](https://docs.oracle.com/cd/E17277_02/html/java/com/sleepycat/je/EnvironmentConfig.html#SHARED_CACHE) it will manage shared cache by ourself
I think it would be better as default settings
-----
tag to the first line of your commit message …
=> Use shared cache by default for berkeleydb

janusgraph-dist/docker-compose.yml
Currently it is not possible to use janusgraph-dist, beacuse of not supported ES version in docker-compose. Update of version (and mapping for port) solves the problem.
For reference - this bug resulted in "gremlin-groovy is not an available GremlinScriptEngine" in gremlin repl.
-----
=> Fixed broken dist docker-compose (updated to supported ES version)

janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayBuffer.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/BufferPage.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/BufferPageUtils.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/InMemoryColumnValueStore.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/InMemoryKeyColumnValueStore.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/InMemoryKeyColumnValueStoreFragmentationReport.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/InMemoryStoreManager.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/MemoryEntryList.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/MultiPageEntryBuffer.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/SharedEntryBuffer.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/SharedEntryBufferFragmentationReport.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/SinglePageEntryBuffer.java, janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/BufferPageTest.java, janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/InMemoryColumnValueStoreTest.java, janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/InMemoryStoreManagerTest.java, janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/MultiPageEntryBufferTest.java, janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/TestPagedBufferColumnValueStore.java
We would like to contribute an improved implementation of in-memory backend for JanusGraph.
Please see issue #1482 for rationale and some comparative analysis vs existing "test-only" in-memory backend.
**_NOTE_**: This PR currently suggests adding the new backend rather than modifying the existing one, as it seemed cleaner and easier to compare performance within one codebase branch.
However, having read recent discussions about adding more backends into main repository vs maintenance costs, I am starting to think that actually modifying the existing in-memory backend could be a better idea.
This is because:
- the modifications are fairly straightforward and do not change the general structure of existing backend
- don’t add too much extra code or any external dependencies
- don’t require …
=> issue #1482 initial contribution of production in-memory backend

docs/storage-backend/inmemorybackend.md
to explain possible production use cases, limitations and alternatives (issue #1929) [doc only]
Signed-off-by: Dmitry Kovalev <dk.global@gmail.com>
-----
=> Update in-memory backend documentation

docs/basics/janusgraph-cfg.md, janusgraph-core/src/main/java/org/janusgraph/core/schema/LoggingSchemaMaker.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
Add a new DefaultSchemaMaker that logs auto created objects #1917
-----
=> Add a new DefaultSchemaMaker that logs auto created objects #1917

janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/JointIndexQuery.java
Pass limit for single index query
More info https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/janusgraph-users/cnVF3hC5OEY/vqq3Vc4HBgAJ
-----
=> Optimize single index query

janusgraph-berkeleyje/pom.xml, pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
=> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

docs/index-management/index-performance.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
This solves #1947 and also fixes one line that should have been refactored in #1190 (PR #1192)
Previously, creating a relation type index enforced a reindex operation in order to enable the index, even if one of the sort keys has been newly created within the same management transaction. Analogous to the handling of global indexes, this PR solves the issue and enables the index right away if it contains at least one new key and therefore is empty at creation time.
-----
=> Set RelationTypeIndex status to ENABLED when the index uses a new key

docs/changelog.md, janusgraph-es/pom.xml, pom.xml
Suppresses #1771
elasticsearch-rest-client 7.6.0 dependencies are:
- httpclient 4.5.10
- httpcore 4.4.12
- httpcore-nio 4.4.12
- httpasyncclient 4.1.4
...
httpclient 4.5.10 dependencies are:
- httpcore 4.4.12
...
httpasyncclient 4.1.4 dependencies are:
- httpclient 4.5.6
- httpcore-nio 4.4.10
- httpcore 4.4.10
...
Because elasticsearch-rest-client uses httpasyncclient (which uses old httpcore-nio) we should bump httpcomponents dependencies to necessary versions explicitly. 
I.e. :
- httpclient 4.5.10
- httpcore 4.4.12
- httpcore-nio 4.4.12
Otherwise we will have dependencies conflicts.
-----
to ensure the following steps …
=> Bump ElasticSearch to 7.6.0

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/util/datastructures/RangeInterval.java
```
java.lang.IllegalArgumentException
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
at org.janusgraph.util.datastructures.RangeInterval.setStart(RangeInterval.java:42)
at org.janusgraph.util.datastructures.RangeInterval.<init>(RangeInterval.java:37)
at org.janusgraph.util.datastructures.RangeInterval.intersect(RangeInterval.java:118)
...
```
-----
Please ensure that once the PR is submitted, you check Travis …
=> Fix range interval intersection

janusgraph-cassandra/src/test/java/org/janusgraph/hadoop/CassandraScanJobIT.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/AbstractConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/BasicConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/Configuration.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/MergedConfiguration.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/MixedConfiguration.java, janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLScanJobIT.java, janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/input/current/JanusGraphHadoopSetupImpl.java, janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/ConfigurationTest.java
- "ConfigElement.getPath" in "AbstractConfiguration.getPath" returns "ioformat.filter-partitioned-vertices", but the "config" variable only contains "janusgraphmr.ioformat.filter-partitioned-vertices". So the "includeRoot" argument has been added to be able to include root path of the "ConfigOption".
Signed-off-by: inho1213 <inho1213@naver.com>
-----
=> Make "janusgraphmr.ioformat.filter-partitioned-vertices" option work

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
When label is null and direction is both, adjacent constraint is overlooked.
This commit fixes this by setting isFitted to be false when adjacentVertex
is present.
Closes #1911
-----
=> Fix adjacent query bug when label is null and direction is both

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexHasIdOptimizerStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexIsOptimizerStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexOptimizerStrategy.java
This feature was originally part of #1937 which was splitted to decrease per-PR-complexity.
This PR introduces two new OptimizerStrategies, which further improve the existing optimizations based on adjacent vertex ids. In the current state, these queries will be optimized to check the adjacency on the edge before iterating to the vertex itself:
- `g.V(left).outE('label').where(_.inV().is(right))`
- `g.V(left).outE('label').filter(_.inV().is(right))`
The optimization of these queries is within the scope of #1960:
- `g.V(left).outE('label').where(__.inV().hasId(right))`
- `g.V(left).outE('label').filter(__.inV().hasId(right))`
With the new optimizer, these queries will also profit of optimization:
- `g.V(left).outE('label').inV().is(right)`
- …
=> Apply optimizations to queries to make use of adjacent ids

janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
While investigating some other issue, I found the constructQuery method is invoked twice sometimes. This PR aims to reduce unnecessary duplicate constructQuery calls without any functional impact.
-----
=> BasicVertexCentricQueryBuilder: Reduce duplicate constructQuery calls

janusgraph-core/pom.xml, janusgraph-core/src/main/java/org/janusgraph/core/util/ReflectiveConfigOptionLoader.java, janusgraph-test/src/test/java/org/janusgraph/core/util/ReflectiveConfigOptionLoaderTest.java, pom.xml
Updates reflections to `reflections8` which doesn't depend on guava.
Notice `reflections` version `0.9.12` is the newest version which doesn't depend on guava but it currently has a bug https://github.com/ronmamo/reflections/issues/273 which might be fixed by https://github.com/ronmamo/reflections/pull/278 in the future versions.
`reflections8` become obsolete after `reflections` version `0.9.12` but `reflections8` version `0.11.7` is a newer version than `reflections` version `0.9.11` and it doesn't depend on guava.
That is why, this PR updates `reflections` to `reflections8` which uses Java 8 Stream API instead of guava. In the future if the bug is fixed in `reflections` and a newer version of `reflections` is released with the bugfix we may go back to `reflections`. In the meantime I …
=> Move reflections to reflections8

janusgraph-dist/src/assembly/static/conf/es/elasticsearch.yml
Not sure if we can add a specific test for this fix because it isn't reproducible on linux (because distributed ES contains linux-x86_64 platform binaries). I have verified that adding this parameter in the ES configuration resolves the issue on macOS.
Fixes #2053
-----
=> Disable ML feature in testing ES distribution

docs/getting-started/installation.md
Solves #2069 
The documentation for all JanusGraph versions between v0.3 and v0.5 should be updated with the corrected information.
-----
=> Fix #2069: Replace misleading docs about default storage backend

janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStep.java
Closes #2042
-----
I ran the following sample program to test the optimization on my laptop using Cassandra + ES:
```java
public void testMultipleIndexQueryWithHeavyLoad() {
final PropertyKey name = makeKey("name", String.class);
final PropertyKey text = makeKey("text", String.class);
final JanusGraphIndex composite = mgmt.buildIndex("composite", Vertex.class).addKey(name).buildCompositeIndex();
final JanusGraphIndex mixed = mgmt.buildIndex("mixed", Vertex.class).addKey(text, getTextMapping()).buildMixedIndex(INDEX);
mixed.name();
composite.name();
finishSchema();
final int numV = 100000;
final String[] strings = {"houseboat", "humanoid", "differential", "extraordinary"};
final int modulo = 5;
for (int i = 0; i < numV; i++) {
final JanusGraphVertex v = tx.addVertex();
v.property("name", …
```
=> Disable smart limit adjustment for count query

docs/basics/server.md
@FlorianHockmann discovered this in #2076 
The error dates back to the earliest version of our documentation, v0.2.
For convenience, I splitted the corresponding example into two code blocks, making it easier to follow the steps to create a sessioned connection.
-----
=> Add missing `:remote console` to remote example in docs

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
This commit node makes sure the `CQLStoreManager` creates a `Cluster` object
without metrics when the JanusGraph configuration was set with `metrics.enabled=false`
Resolves: #2089
-----
=> Disable CQL metrics when JanusGraph configuration states `metrics.enabled=false`

janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilder.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilderTest.java
When evaluate discrepancies options we need check for existense, otherwise we catch exception when local config try to pass new one managed option with disallow empty predicate
-----
=> Fix global config overriding

docs/basics/janusgraph-cfg.md, janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java, janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java, janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJETx.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/log/kcvs/KCVSLog.java
- Introduce CACHE_MODE parameter -- tx may be configured without storage cache -- it is usefull during single full scan queries, like reindex
- Avoid interruption if store unsupported it -- `StoreFeature.supportsInterruption` used only for BDB but not handled in any places where interruption may occur
- Do no read messages infinitely when permanent exception occurred 
-----
Please ensure that once the PR is submitted, you check Travis CI for …
=> Improve OLAP queries for BerkeleyDB

docs/basics/janusgraph-cfg.md, docs/changelog.md, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchIndexTest.java
- Move INDEX_STORE_NAMES_CACHE from static to instance specific scope.
- Add possibility to disable INDEX_STORE_NAMES_CACHE cache
Fixes #2102
-----
=> Fix ElasticSearch INDEX_STORE_NAMES_CACHE should not be shared between instances

janusgraph-core/src/main/java/org/janusgraph/diskstorage/Mutation.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KCVMutation.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/cache/CacheTransaction.java
Instead of copying elements to a list and then again to a new list, this PR provides a function to copy all deletions in a single pass.
-----
=> Optimize KVCMutation construct for deletions in CacheTransaction

docs/index-backend/elasticsearch.md
- fix duplicated lines in index-backend/elasticsearch section Ingest Pipelines
-----
=> [doc only] remove duplicated doc lines

janusgraph-core/src/main/java/org/janusgraph/graphdb/management/ConfigurationManagementGraph.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/management/ConfigurationManagementGraphTest.java
We found that the cause of issue #2149 was due to a dangling transaction in the graph instance used by `ConfiguredGraphManager`. These changes make sure that the traversal source used to access the configuration for a graph always starts with a clean transaction.
-----
=> Fix #2149: get a clean transaction when querying the config graph

CONTRIBUTING.md
[doc-only] Fixes JanusGraph#1513.
The codacy-bot repository, as described in the issue, is no longer available, so the blocked user approach was highlighted as the appropriate solution.
-----
- [] If this PR is a documentation-only change, have you added a `[doc only]`
=> Adding codacy opt-out instructions

janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml, janusgraph-server/src/test/resources/org/janusgraph/graphdb/tinkerpop/gremlin-server-integration.yaml
when user set accept application/vnd.gremlin-v2.0+json it throws org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0 cannot be cast to org.apache.tinkerpop.gremlin.driver.ser.MessageTextSerializer
org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0 didn't implements org.apache.tinkerpop.gremlin.driver.ser.MessageTextSerializer
Signed-off-by: Hon <George-Hon@outlook.com>
-----
Please ensure that once the PR is submitted, you check Travis CI for …
=> fix serializer issues

janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Text.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
This reduces time complexity of fuzzy match from O(n^2) to O(n), where n
is the length of the string. This also adds tests which use fuzzy
predicates without index.
Closes #2164
-----
=> Optimize LevenshteinDistance used in Fuzzy predicates

janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
This fixes a bug in GraphCentricQueryBuilder which gives wrong
query limit estimate and thus harms performance.
Fixes #2206
-----
=> GraphCentricQueryBuilder: Fix wrong query limit estimate

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/PredicateCondition.java
Fixes #2188
The needed changes are already described in #2188. To solve this issue, it was also necessary to alter the definition of two `PredicateCondition`s being equal to each other. Nesting `P.without()` predicates on a property value within an `and()` step automatically adds a `PredicateCondition` that this property value must not equal `null`. Therefore, `PredicateCondition` should handle `null` values on equality checks.
-----
Please ensure that once the PR is submitted, you check Travis …
=> Allow nesting CONTAIN predicates with and/or

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheEdge.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheVertexProperty.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
When a CacheEdge or a CacheVertexProperty is updated, JanusGraph
creates a new edge/property with auto-generated longId, and then overrides
it with the old id. Since AddedRelationsContainer implementation
relies on the longId as part of hash key, creating a new edge/property
with new longId can lead to a commit exception. This bug appears
when a vertex property or an edge is updated and then deleted in the
same transaction.
Fixes #2138
-----
Please ensure that once the PR is submitted, you check …
=> Fix cached relation update hashcode change bug

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/VertexIDAssigner.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/VertexIDAssignerTest.java
When ids-flush is disabled, ids are re-assigned even if elements
already have ids, e.g. update of existing elements. This commit
fixes this bug and does not re-assign ids.
-----
=> Fix VertexIDAssigner bug when ids-flush is disabled

.gitignore, docs/basics/janusgraph-cfg.md, docs/changelog.md, janusgraph-cql/pom.xml, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLColValGetter.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLResultSetKeyIterator.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLTransaction.java, janusgraph-cql/src/main/java/org/janusgraph/hadoop/CqlHadoopStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLResultSetKeyIteratorTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CachingCQLStoreManager.java, janusgraph-dist/pom.xml, janusgraph-hadoop/pom.xml, pom.xml
Mostly based on #1733 .
This PR adds 2 DataStax drivers into `janusgraph-cql`:
- DataStax 4.9.0 is the main driver which is now used.
- DataStax 3.10.2 is the driver which is now used for Hadoop. `CqlBinaryRecordReader` which is used for Hadoop jobs is still using DataStax Cassandra Driver 3.x.y.
Notice, even so this PR adds 2 different versions of DataStax Cassandra Driver in the same module, those drivers are binary incompatible and share different classpath, thus they don't conflict with each other and can be used simultaneously. 
Later we can move CQL Hadoop formats from `janusgraph-cql` to a new module like `janusgraph-hadoop-cql` or something like that. It will allow to include only 4.x version of the driver into classpath for users who use `janusgraph-cql` but don't use …
=> Upgrade DataStax cassandra driver to 4.9.0 [full build]

docs/basics/janusgraph-cfg.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
Adds possibility to enable CQL request logger to debug queries. Tested manually.
Not sure how to cover this feature with tests without using reflection (which might be a bad approach).
Request tracker and a builtin request logger DataStax documentation for 4.9 driver version is here: https://docs.datastax.com/en/developer/java-driver/4.9/manual/core/request_tracker/
-----
Please ensure that once the PR is submitted, you check Travis …
=> Add optional datastax request logger

janusgraph-core/src/main/java/org/janusgraph/diskstorage/locking/consistentkey/ConsistentKeyLocker.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/locking/ConsistentKeyLockerTest.java
#2225: Fixed transaction leaks in ConsistentKeyLocker. Updated unit tests to detect leaked transaction.
(cherry picked from commit 12718473fae6e9172e292cfcd61de175d22b2577)
(cherry picked from commit 3e16a8fdd8dc81a47529cf0950d60c7ed3debdd3)
=> Fixes #2255: leaked transactions in ConsistentKeyLocker

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java, janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Cmp.java
=> Fix neq and null condition query behavior

pom.xml
According to the comment, snappy dependency was explicitly added to
fix some issue on JDK 7 running on MacOS. Since JDK 7 is no longer
supported by JanusGraph, this explicit dependency can be removed.
-----
=> Remove snappy dependency

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/locking/consistentkey/ConsistentKeyLocker.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
The old test fails to test the locking mechanism because one thread runs so fast such that other threads often fail before they commit. To properly test lock contention, we need to let them commit together. Note that this test still can only test local lock contention (threads running on the same process), but not the case where transactions running on different JVMs compete for locks.
-----
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to …
=> Rewrite testConcurrentConsistencyEnforcement to properly test lock contention

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/JanusGraphAssert.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/subquerycache/GuavaSubqueryCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/subquerycache/SubqueryCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/subquerycache/SubsetSubqueryCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/SubqueryIterator.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
This refactors indexCache used in transaction which caches index query results.
Now indexCache supports subset query, i.e., cached query responses can be
leveraged if new query and cached query only differ in limit.
Closes #2194
-----
=> Optimize performance of transaction-wise index query cache

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexFeatures.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/AbstractIndexSelectionStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/HasStepFolder.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/AbstractESCompat.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/BerkeleyElasticsearchTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchJanusGraphIndexTest.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
Currently, has(key) query does not use index at all. This commit
tries to use mixed index if possible. Geoshape type exists query
is not supported by Lucene and Solr index backends.
Related to #284
-----
=> Add mixed index support for has(key) query

docs/changelog.md, janusgraph-es/pom.xml, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java, pom.xml
I was unable to run Elasticsearch tests on my Macbook. Bumping to the latest version of ES solved the problem.
-----
=> Bump Elasticsearch version to 7.10.1

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/IndexSelectionUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexHasUniquePropertyOptimizerStrategy.java
Solve #2339 
As suggested, I added the ability to pass a filter to `getMatchingIndexes`. I also kept the old signature as a wrapper around the new function which just returns the unfiltered result.
-----
=> Allow passing a filter function to getMatchingIndexes

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeySliceQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/SliceQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/EdgeSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/ElementQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java
=> Indicate vertex-centric index usage in profiler result

docs/advanced-topics/eventual-consistency.md
Faunus was a standalone product (https://github.com/thinkaurelius/faunus)
which later merged into Titan codebase, and now is a part of JanusGraph-hadoop
module. This commit removes mention of Faunus in the documentation.
-----
=> [Doc] Remove mention of Faunus

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsTransaction.java
JanusGraphBlueprintsTransaction::addVertex calls ElementHelper.getIdValue(keyValues)
twice, which is unnecessary. Not sure whether this could be detected and optimized
by JIT (I don't think it could, though), but there is no harm to reduce the redundant
call anyway.
-----
=> Reduce redundant calls to getIdValue in addVertex method

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/JanusGraphAssert.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/ProfiledIterator.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/SubqueryIterator.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
1. Indicate "constructGraphCentricQuery" phase in profiler rather than a vague
"optimization" annotation, if applicable.
2. Indicate "GraphCentricQuery" in profiler if applicable. Previously profiling result
is corrupted when a gremlin query is satisfied by multiple graph centric queries.
Note that this PR does not fix https://github.com/JanusGraph/janusgraph/issues/2285 (corruption due to flattening multiple AND/OR groups). That issue is trickier and will be addressed in the next PR.
-----
=> Enhance GraphCentricQuery profiling

janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KCVSProxy.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeyColumnValueStore.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeySlicesIterator.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/MultiSlicesQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/StandardStoreFeatures.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/StoreFeatures.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreAdapter.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/MultiThreadsRowsCollector.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/RowsCollector.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/SingleThreadRowsCollector.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/MetricInstrumentedSlicesIterator.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/MetricInstrumentedStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseKeyColumnValueStore.java, janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/InMemoryKeyColumnValueStore.java, janusgraph-test/src/main/java/org/janusgraph/diskstorage/cache/KCVSCacheTest.java
`KeySlicesIterator` introduced to fix issue with key inconsistency while running parallel scans in `StandartScannerExcecutor`
fixes https://github.com/JanusGraph/janusgraph/issues/1527
Without this fix Aerospike (that doesn't guaranty order of keys while running scan operation) can't utilize Janusgraph jobs 
(Reindex, GhostVertexRemover)
=> KeySlicesIterator introduced

janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
`janusgraph-server.sh` is based on TinkerPop's `gremlin-server.sh` and is also affected by [TINKERPOP-2512](https://issues.apache.org/jira/browse/TINKERPOP-2512).
When starting `janusgraph-server.sh` the Java classpath contains each Jar file twice, because [$CLASSPATH already contains $CP](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh#L128), so Java [shouldn't be started with `-cp $CP:$CLASSPATH`](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh#L193).
-----
=> Avoid duplicate jars in classpath

docs/advanced-topics/eventual-consistency.md
Astyanax locking recipe is not valid anymore given Astyanax
Cassandra driver has been removed.
-----
=> [Doc] Remove mention of Astyanax in data consistency chapter

.github/workflows/ci-backend-cql.yml, janusgraph-backend-testutils/pom.xml, janusgraph-backend-testutils/src/main/java/org/janusgraph/core/AbstractConfiguredGraphFactoryTest.java, janusgraph-core/src/main/java/org/janusgraph/core/ConfiguredGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java, janusgraph-cql/src/test/java/org/janusgraph/core/cql/CQLConfiguredGraphFactoryTest.java, janusgraph-inmemory/src/test/java/org/janusgraph/core/inmemory/InmemoryConfiguredGraphFactoryTest.java, janusgraph-test/pom.xml, janusgraph-test/src/test/resources/log4j.properties
This PR address issue #2147 by refactoring the `drop()` method in the `ConfiguredGraphFactory` class.
The bug was in the call to `removeGraphFromCache(String graphName)` which internally tries to open the graph. Because of the order of the calls, the graph was already dropped by a call to `JanusGraphFactory.drop(graph)` which then result in the storage to be recreated.
-----
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon …
=> Fix #2147: graph is created again during the drop process

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializerTest.java
=> Make DateSerializer thread-safe

janusgraph-all/pom.xml, janusgraph-dist/pom.xml, janusgraph-server/pom.xml, janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphManagerImpl.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphServer.java, janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphSettings.java, janusgraph-server/src/main/proto/graph-manager.proto, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphManagerImplTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphServerTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphSettingsTest.java, janusgraph-server/src/test/java/org/janusgraph/graphdb/server/TestingServerClosable.java, janusgraph-server/src/test/resources/janusgraph-inmemory.properties, janusgraph-server/src/test/resources/janusgraph-server-with-grpc.yaml, janusgraph-server/src/test/resources/janusgraph-server-with-server-configs.yaml, janusgraph-server/src/test/resources/tinkergraph.properties, pom.xml
Part of #1853 
* Add basic config parameters to the gremlin-server.yaml
* Add first server component to get a janusgraph which is managed by a graphmanager by name
* Setup protobuf building process
* Allow testing of new grpc components
Signed-off-by: Jan Jansen <jan.jansen@gdata.de
-----
Follow up PRs
* add basic schema interaction using grpc
* add basic driver part
* setup integration test
* add auth and security
-----
=> Add grpc server to janusgraph-server

janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctOrderedIterator.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctUnorderedIterator.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/util/MultiDistinctUnorderedIteratorTest.java
By default tx vertex cache contains only 20k vertices, but references to these vertices collected in MultiDistinct*Iterator.allElements so these vertices still consume memory. For eliminate this, just store only Element.id() and now GC may clean up memory during long queries
-----
=> Fix memory utilization for long query

janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/configuration/WritableConfigurationTest.java
**Problem:**
A test method with many individual assertions stops being executed on the first failed assertion, which prevents the execution of the remaining ones.
**Solution:**
By using the JUnit5 grouped assertions feature, all assertions are executed and all failures will be reported together. In this refactoring, no original assertion was changed.
**Result:**
_Before:_
```
...
assertEquals("world", config.get("test.key", String.class));
assertEquals(ImmutableSet.of("test.key", "test.bar"), Sets.newHashSet(config.getKeys("test")));
assertEquals(ImmutableSet.of("storage.xyz", "storage.duba", "storage.abc"),
Sets.newHashSet(config.getKeys("storage")));
assertEquals(100,config.get("test.bar",Integer.class).intValue());
assertEquals(true, config.get("storage.xyz", Boolean.class)); …
```
=> Test Improvement: grouping individual assertions

.codecov.yml, .github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-core.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml
1. Notify config should be under codecov group, not coverage group
2. Remove codecov.notify.after_n_builds limit so that code coverage
is always available as a GitHub check, no matter how many codecov
reports are uploaded
3. Disable pull request comment feature since it is annoying and
unstable
4. Name codecov reports
-----
=> Fix codecov configs

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/BackendQueryHolder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/JointIndexQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/ProfileObservable.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/SimpleQueryProfiler.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BaseVertexCentricQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/profile/TP3ProfileWrapper.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java
Currently, when there is more than one backend query, annotations
(condition, orders, isFitted, isOrdered, query, index) of the last
one overwrites previous annotations in the profiling result.
This commit fixes this problem by avoiding flattening AND/OR query
groups. The drawback of this commit is those groups (AND-query, OR-query)
are not timed due to technical difficulty, which is left as future
work.
Fixes #2285
-----
=> Fix nested AND/OR profiler group issue

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphPerformanceMemoryTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/EdgeSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/RelationIdentifierUtils.java
It benefit when two vertices contains many edges of same type, but we can get only one by id. Instead of filter out in memory we can construct direct query (more info about data model layout https://docs.janusgraph.org/advanced-topics/data-model/)
-----
=> Utilize data model layout when getting edge by id

janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java
The old output confuses 'graph edge index' with 'vertex centric index (VCI)'
-----
=> Fix JanusGraphManagement::printIndexes output

.github/workflows/ci-backend-cql.yml, janusgraph-cql/pom.xml, janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java
since `scylladb/scylla` were comptible out of the box for
testcontinars, we now enable any docker image to be cosider as
cassandra comptible
Fixes: #2351
-----
=> Make any passed cassandra image consider as compatible

janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
A small enhancement that reduces an unnecessary duplicate call.
-----
=> BasicVertexCentricQueryBuilder: Reduce duplicate getExtendedSortKey calls

.github/workflows/ci-release.yml
Run TinkerPop tests 4 times a week.
Based on the next documentation: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
Fixes #1620
-----
=> Add job to run all TinkerPop tests on schedule

docs/operations/cache.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/CacheVertex.java
In some use cases, users might want to read from the underlying storage
backend again in the mid of a transaction, bypassing the vertex cache.
This commit adds a refresh method to CacheVertex which user could call
to clear the cache.
Related to https://lists.lfaidata.foundation/g/janusgraph-users/topic/81050716
-----
=> Add CacheVertex::refresh method to allow clearing vertex cache

janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
-----
When run in Docker (or Kubernetes) the `SIGTERM` signal is not received by the Java process.
This prevent the Shutdown Hooks to be executed properly.
Hence, the `exec` syntax could be preferred.
=> Add exec to start server

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java
PR #2137 Fixes a bug with VCI reindexing, but the tests are
not robust and fail manual mutation testing. This commit
rewrites the test and verifies the query results before
and after reindexing.
-----
=> Rewrite vertex-centric reindexing test

.codecov.yml, .github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-core.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml
1. In codecov reports, ignore all test files. Currently tests under janusgraph-cql module
are picked up by codecov. After this change, overall test coverage will be increased.
2. Upload jacoco artefacts in GitHub actions, so that developers can
download the generated jacoco test coverage reports and view locally
(e.g. in IDE).
-----
=> Ignore tests in codecov report and upload jacoco artefacts

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/VertexIDAssigner.java
Other pools are closed properly, but partitionVertexIdPool is missed.
-----
=> VertexIDAssigner: close partitionVertexIdPool in close method

janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/ArrayUtil.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayEntryList.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/ArrayUtilTest.java
StaticArrayEntryList::ensureSpace method expands an immutable
array by allocating a larger array and copies data from the old array
to the new one. It tries to avoid expensive copy operations by
doubling the estimated size each time, however, when the array
size is very large (larger than Integer.MAX_VALUE / 2), the new estimated
size will overflow and thus the array won't be effectively expanded.
As a consequence, it will be expanded into the minimum required
size, which is very ineffective and incurs great overhead.
This commit takes java.io.ByteArrayOutputStream implementation as a reference
and adds an ArrayUtil::growSpace method which can properly handle large
size and avoids integer overflow problems.
Related to #2524
-----
In order to …
=> Fix integer overflow bug in StaticArrayEntryList

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeySliceQuery.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/SliceQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/LimitAdjustingIterator.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryProcessor.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/JointIndexQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MultiKeySliceQuery.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
When LimitAdjustingIterator is in effect, multiple backend queries with
different limits (e.g. 1000, 2000, 4000, ...) are fired progressively.
They are, however, not all profiled. Currently, only the last backend
query is profiled because of a bug. This commit fixes it and now users
can see timing of each backend query to better understand whether they
need smart-limit or not.
This commit also fixes a minor thing with profiler output, such that when
QUERY.NO_LIMIT is used or no limit is given, we don't display Integer.MAX_VALUE
in the profile output.
-----
=> Fix profiling when limit adjusting is enabled

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializerTest.java
Fixes #2429
Follow up to #2430
Usage of StdDateFormat outside of Jackson's framework is discouraged.
StdDateFormat is not thread-safe and wrapping an instance of it in a ThreadLocal could result in data leaks.
Java 8 DateTimeFormatter is thread-safe.
-----
=> Use Java DateTimeFormatter instead of Jackson StdDateFormat

docs/configs/janusgraph-cfg.md, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
When meta.*.timestamps and/or meta.*.ttl are disabled (which are by default),
write timestamps and TTL info will not be retrieved. CQLKeyColumnValueStore,
however, retrieves them anyways, and simply discard them. This commit makes
CQL driver fetches them only when needed.
It also enhances relevant documentation so that users know how to make use of
these metadata if needed.
-----
=> CQLKeyColumnValueStore: Avoid fetching WRITETIME and/or TTL if no need

janusgraph-cql/pom.xml, pom.xml
Previously, due to a misconfiguration, serial tests are skipped
for Cassandra. This commit fixes the config and does some cleanup.
This commit also bumps the Scylladb version from 4.3.0 to 4.4.0.
-----
=> Enable serial tests for cassandra

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchIndexTest.java
Sorting on TEXTSTRING mapped fields threw the following ES error, because JG applied sorting to the wrong ES field.
```
Fielddata is disabled on text fields by default. Set fielddata=true on [#field] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
```
-----
=> Fix sorting TEXTSTRING mapped fields in ES

janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchScroll.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchScrollTest.java
The _scroll_id may change between requests and only the
most recently received one should be used.
Fixes #2582
-----
=> Always use the most recent _scroll_id

janusgraph-core/src/main/java/org/janusgraph/core/TransactionBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/AbstractScanJob.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/GraphProvider.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/VertexJobConverter.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/PartitionedVertexProgramExecutor.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/GhostVertexRemover.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRemoveJob.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardTransactionBuilder.java
This commit extracts common code from VertexJobConverter into the new class AbstractScanJob,
and makes both GhostVertexRemover and VertexJobConverter inherit it. Previously,
GhostVertexRemover inherits VertexJobConverter which does not make sense.
Part of #2555 
-----
=> Refactor GhostVertexRemover and VertexJobConverter

janusgraph-backend-testutils/src/main/java/org/janusgraph/core/attribute/TextArgument.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
Refines negated Text predicates so missing, i.e. null, values evaluate to false in the ElasticSearch backend:
```
gremlin> g.V().has('missingField', textNotRegex('.*'))
gremlin>
gremlin> g.V(86040L).propertyMap()
==>[]
gremlin> g.V(86040L).has('missingField', textNotRegex('.*'))
gremlin>
```
This adds an exists clause to the evaluation of each negated text predicate, aligning it to the JanusGraph implementation which assumes `.has(X, Y)` is equivalent to `.has(X).has(X, Y)`.
-----
=> Add exists clause to negated Text predicates

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
Changes to for #2607 which reported errors when testing with `storage.cql.atomic-batch-mutate=true` following the upgrade to the DataStax Cassandra driver to 4.9.0 made under #2169. I've also included the test from the issue which reproduced the problem and which prior to these changes failed.
Tracked the problem down using a debugger, to what was being passed to [BatchStatementBuilder::addStatements](https://docs.datastax.com/en/drivers/java/4.9/com/datastax/oss/driver/api/core/cql/BatchStatementBuilder.html#addStatements-java.lang.Iterable-) which was an `Iterator` when the method was expecting an `Iterable`. The debugger showed that no statements were getting added to the builder. Converting the `Iterator` to an `List` fixed the failing test and using the debugger I could see the …
=> Iterator changes for atomic batch mutate to fix #2607

docs/getting-started/installation.md, docs/operations/server.md, janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
Fixes #2146
* add a starting a Janusgraph with janusgraph-server.sh
* moves the janusgraph.sh section into the installation.md
* add usage command to janusgraph-server.md
* remove section for standalone Gremlin Server as we started
with jg 0.6 to extend Gremlin Server with some extra features
-----
I think this should be part of JG 0.6. JanusGraph Server part has gone under major restructuring during development cycle of JG 0.6. 
-----
=> Refactor server.md for janusgraph-server.sh

janusgraph-core/src/main/java/org/janusgraph/util/system/ConfigurationUtil.java, janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLInputFormatIT.java, janusgraph-cql/src/test/resources/cql-read-multi-hosts.properties, janusgraph-hbase/src/test/java/org/janusgraph/hadoop/HBaseInputFormatIT.java, janusgraph-hbase/src/test/java/org/janusgraph/hadoop/HBaseSnapshotInputFormatIT.java
This adds test cases to demonstrate that comma-delimited values can
be loaded by HadoopGraph in Spark usecase.
Prior to TinkerPop 3.5.0 upgrade, if config file has
`gremlin.graph=org.apache.tinkerpop.gremlin.hadoop.structure.HadoopGraph`,
which is typically the case for MapReduce/Spark traversals,
then `GraphFactory.open(filename)` would first read all comma delimited values
into a list, and then only retain the last value. A workaround is to
create a `PropertiesConfiguration` config object, disable comma delimiter, and
then call `GraphFactory.open(config)`.
This is auto-resolved by #2619 because since TinkerPop 3.5.0, comma-delimited
values are by default loaded as they are. This commit adds some test cases
to demonstrate this behaviour. The same tests fail without #2619.
-----
Thank you …
=> Add test for HadoopGraph loading comma delimited values

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java
Break vertices selection loop for properties prefetching when cache size is reached
-----
=> Break vertices selection loop for properties prefetching when cache size is reached

janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/vertices/StandardVertexTest.java
Vertices may change lifecycle but already evicted from cache, so update cache if vertex change here status
fix for #2627
-----
=> Fix inconsistent state of edge

janusgraph-cql/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryInputFormat.java
When setting up connections to Cassandra cluster for OLAP traversal,
it is recommended to provide all contact points, such that even if
some of them are unavailable at that time, the connections can still
be established.
This has been running for some time in our production cluster. So far, so good.
I also verified that even if one Cassandra node is not available when submitting
the MapReduce job, everything still works smoothly.
This is a follow-up of https://github.com/JanusGraph/janusgraph/pull/1436#discussion_r629018494
-----
=> Use all hosts available in CqlBinaryInputFormat config

janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java, janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/AbstractIndexManagementIT.java, janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/MapReduceRemoveIndexApp.java
Related to https://lists.lfaidata.foundation/g/janusgraph-users/topic/82821364
We used this to leverage Hadoop ToolRunner that can submit local files together with the MapReduce job, which will be available to all mappers on their working directories. The files are then used by mappers for authentication. So far, so good.
-----
=> MapReduceIndexManagement: Accept optional custom hadoop config

docs/changelog.md, docs/storage-backend/cassandra.md, janusgraph-core/src/main/java/org/janusgraph/diskstorage/common/AbstractStoreManager.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
=> Add experimental support for Amazon Managed KeySpace

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/HasStepFolder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexFilterOptimizerStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexHasIdOptimizerStrategy.java
Calls to `getHasContainers` of `JanusGraphStep` create new `ArrayList` and also spends time to populate that list. So, this commit tries to reduce calls to this method when not needed (i.e. reuse already computed values). Also, this PR reduces unnecessary creation of some collections (no need to create lists when they are used only once as Iterable. It would make sense to create lists if they are used more than once).
-----
=> Optimize getHasContainers usage

docs/schema/index.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java
Property names can be changed in JanusGraph, but there is no test for this
feature. This commit adds some test cases to ensure the behavior is correct.
It also updates documentation which points out the limitation of this feature.
Related to #2653
-----
=> Add tests and doc for property name change feature

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/JanusGraphAssert.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphEdgeVertexStep.java
Very small change which won't trigger unnecessary loop if tx cache is less than 2. Also changed a loop to use vanilla java (very small change as well). Added a test to cover the logic which was not previously covered.
-----
=> Do not trigger iteration on small cache in JanusGraphEdgeVertexStep initialization

janusgraph-core/src/main/java/org/janusgraph/graphdb/types/SchemaSource.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/VertexLabelVertex.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/indextype/CompositeIndexTypeWrapper.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/indextype/IndexTypeWrapper.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/indextype/MixedIndexTypeWrapper.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/EdgeLabelVertex.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/JanusGraphSchemaVertex.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/RelationTypeVertex.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/CollectionsUtil.java
getRelated is always computed as List so there is no sense to return Iterable instead of List.
In case the implementation of getRelated is changed to return Iterable then we can change the
dependant logic back to use Iterable instead of List.
Right now using List instead of Iterable allows us to create ArrayList in some places with correct size
instead of LinkedList which generally takes more space.
-----
=> Refactor JanusGraphSchemaVertex to return List instead of Iterable

docs/configs/janusgraph-cfg.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
For applications doing a lot of deletes, C* will produce many tombstones, preventing large queries (e.g. reads from M/R or Spark) from succeeding. Adding an option to set `gc_grace_seconds` would allow users to tailor JanusGraph to their workload.
Customizing `gc_grace_seconds` is mentioned a few times on the ML [[1](https://lists.lfaidata.foundation/g/janusgraph-users/topic/79936500#3196),[2](https://lists.lfaidata.foundation/g/janusgraph-users/topic/79936784#3956)] or in IBM [documentation](https://www.ibm.com/docs/en/nasm/1.1.6?topic=performance-changing-gc-grace-seconds-icp) showing this feature might be helpful.
-----
=> Add an option to set Cassandra's gc_grace_seconds

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/IndexMetricTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/TestMockIndexProvider.java, janusgraph-core/src/main/java/org/janusgraph/core/MixedIndexCountQuery.java, janusgraph-core/src/main/java/org/janusgraph/core/Transaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/BackendTransaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexProvider.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexTransaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/MetricInstrumentedIndexProvider.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MixedIndexCountQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/AbstractIndexSelectionStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/IndexSelectionStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphMixedIndexCountStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphMixedIndexCountStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/profile/TP3ProfileWrapper.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
This adds JanusGraphMixedIndexCountStrategy which leverages mixed index
to return the total count if applicable. The implementation idea is to
leverage the partial result of JanusGraphStepStrategy and JanusGraphStep
which handle folding and building a global graph centric query.
Closes #874
-----
=> Add strategy that optimize mixed index lookup followed by count step

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphTransaction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementLogger.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
Fix NPE when updating mixed index by ensuring the cache is not stale.  Fixes #1876.
=> Fix NPE when updating mixed index

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphTransaction.java, janusgraph-core/src/main/java/org/janusgraph/core/SchemaViolationException.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementLogger.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
An update to the mixed index would cause open transactions to fail and throw
NullPointerException if they happen to touch the same index. #2688 fixes this
by making schema changes transparent to all transactions. The fix is, however,
incomplete in the sense that transaction now still fails but fails silently.
Generally, there are two solutions:
1) Do not attempt to fix this issue, but provide a better error message.
2) Continue the fix in #2688 and make sure schema caches are cleared.
This commit reverts #2688 and provides a better error message when aborting
the transaction. Note that even if we choose 2) later, this commit still
remains valuable, because schema updates are propagated asynchronously
among JanusGraph instances.
This commit does not judge whether we should do 2) or not. It …
=> Abort transaction if mixed index schema gets updated concurrently

janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphTransaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/BackendTransaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexTransaction.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/KeyInformation.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementLogger.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
This is a continuation PR to https://github.com/JanusGraph/janusgraph/pull/2688, that properly invalidates stale cached data from index transactions.
=> Properly invalidate stale cached index data

docs/interactions/transactions.md, janusgraph-core/src/main/java/org/janusgraph/core/TransactionBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphTraversalUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphMultiQueryStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardTransactionBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/TransactionConfiguration.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/StandardTransactionBuilderTest.java
This allows users to turn on/off `query.batch` on the transaction level.
-----
=> Add multi-query option to transaction builder

janusgraph-dist/pom.xml
Looks like the mirror which we were using for Cassandra removed the link to our managed version (3.11.10). Probably due to the release of 3.11.11 and 4.0.0.
This PR fixes: https://github.com/JanusGraph/janusgraph/runs/3196377838
-----
=> Fix broken Casssandra link and update download-maven-plugin to 1.6.6 CTR

janusgraph-dist/src/assembly/static/conf/gremlin-server/janusgraph-cql-es-server.properties
JanusGraph 0.6 with a ConfiguredGraphFactory won't start if `storage.cql.local-datacenter` is not defined and a custom Cassandra datacenter is used (i.e. not datacenter1).
-----
=> Add cql.local-datacenter to sample properties file

janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphServer.java
While trying out JanusGraph 0.6, I was stuck with JanusGraphServer failing to start and a log line saying:
```
ERROR org.janusgraph.graphdb.server.JanusGraphServer - 0 0 - JanusGraph Server was unable to start and will now begin shutdown: java.lang.reflect.InvocationTargetException
```
This is not very informative, so a user would typically have to build a custom version of JanusGraph to figure out what the root cause is.
With the proposed change, one can understand from the logs that the root cause is in fact Cassandra being unreachable:
```
ERROR org.janusgraph.graphdb.server.JanusGraphServer - 0 0 - JanusGraph Server was unable to start and will now begin shutdown
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at …
```
=> Log exception when JanusGraphServer fails to start

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/HasStepFolder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
This is an attempt at fixing #2231. The basic premise is that since the current code makes that assumption of the traversal having only one `.or()` statement, I wrap any related pieces of code in another layer of collections to handle multiple. I've done a lot of testing around it and it seems to work fine without breaking other queries. I'm interested in what you think about this as I'm not a 100% sure that this is a right direction.
-----
=> Fix queries with multiple OR clauses

janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/ExecutorServiceInstrumentation.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/ExecutorServiceInstrumentationTest.java
Instrument ThreadPools when `metrics.enabled` is true.
Instrumentation is done by `com.codahale.metrics.{InstrumentedExecutorService,InstrumentedThreadFactory}`.
Metrics are logged to `<METRICS_PREFIX>.threadpools.<THREADPOOL_NAME>.{executorService,threadFactory}.*`
Mentioned in Discussion #2740.
-----
=> Instrument ThreadPools when metrics.enabled is true

docs/changelog.md, janusgraph-cql/pom.xml, janusgraph-hadoop/pom.xml, pom.xml
This aims to fix Spark traversal caused by scala version mismatch. Tested locally using the following steps:
```
:plugin use tinkerpop.hadoop
:plugin use tinkerpop.spark
graph = GraphFactory.open('conf/hadoop-graph/read-cql.properties')
g = graph.traversal().withComputer(SparkGraphComputer)
g.V().count()
```
TODOs:
=> Fix scala dependency conflict in spark traversal [cql-tests]

janusgraph-core/pom.xml, pom.xml
org.apache.commons:commons-configuration2 is used widely in JanusGraph but it is not
explicitly included in pom.xml, which causes coexistence of two different versions,
one introduced by tinkerpop and the other introduced by solr-test-framework. Although
the released jars only include the tinkerpop version, which is correct, it is better to
explicitly define this dependency in pom.xml.
-----
=> Explicitly add commons-configuration2 dependency

janusgraph-backend-testutils/pom.xml, janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/TestLoggerUtils.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLMutateManyFunctionBuilder.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLMutateManyFunctionWrapper.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLStoreFeaturesBuilder.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLStoreFeaturesWrapper.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLMultiWriteStoreTest.java
This PR simply wraps the code after `CQLSession` is created in `try catch` and then trigger `close` method in case the exception was thrown later in the constructor.
From https://docs.datastax.com/en/developer/java-driver/4.13/manual/core/ it is noted that `CqlSession` must always be properly closed.
I found that CQLSession isn't properly closed if the exception is thrown during CQLStoreManager construction after CQLSession is initialized.
The next property helped to find the leak `advanced.session-leak.threshold` (you can read more about it here: https://docs.datastax.com/en/developer/java-driver/4.13/manual/core/configuration/reference/).
The test which will fail on master branch (similar one is included in this PR):
```
@Test
public void shouldProperlyCloseSessionOnException() throws …
```
=> Ensure CQLSession is closed properly even on CQLStoreManager construction exception

docs/changelog.md, docs/configs/janusgraph-cfg.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java
Connection timeout is used for request timeout which is misleading. This PR fixes it by introducing additional `request-timeout` property.
-----
=> Fix wrong configuration is used for CQL requests timeout

janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BaseVertexCentricQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
QNF constraint form, JanusGraph variant of CNF (conjunctive normal form) with negation inlined,
is not required for vertex centric queries. This commit removes the checks for QNF, otherwise
queries like `has("duration", P.eq(0d).or(not(P.outside(0.1d, 0.3d))))` would fail.
Fixes #2773
-----
=> Remove QNF check for vertex centric query constraints

docs/configs/janusgraph-cfg.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
In the previous PR #2770 I also unintentionally changed the default time from 10 seconds to DataStax Driver default timeout which is 2 seconds. To not add additional breaking change this PR just changes the request timeouts back to 10 seconds. 
-----
=> Change CQL request timeout to the previous defaul 10s

docs/operations/server.md, janusgraph-dist/src/assembly/cfilter/conf/janusgraph-berkeleyje-es.properties, janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql.yaml, janusgraph-dist/src/test/expect/janusgraph-server-sh.after.expect.vm, janusgraph-dist/src/test/expect/janusgraph-server-sh.before.expect.vm
Fixes the bug when 2nd argument would be ignored to processed as configuration path. Thus the default inmemory configuration was used from `janusgraph.sh start` instead of Cassandra + ElasticSearch. This PR fixes it by allowing to pass optional 2nd argument which would represent configuration to be used.
The bug was reported by @FlorianHockmann here: https://lists.lfaidata.foundation/g/janusgraph-dev/message/1546
Tested these changes with `janusgraph.sh` (now it runs Cassandra + ElasticSearch as expected). Also tested `janusgraph-server.sh` with both default and custom configuration (works as expected).
Related to #2119
-----
In order to streamline the review of the contribution we ask …
=> Add possibility to use second argument as configuration path to janusgraph-server

janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
JanusGraphStep wrongly assumes an id must be a vertex id.
In fact, it could be an edge id.
Fixes #2848
-----
=> Fix g.E().hasId(eId) empty result bug

docs/configs/janusgraph-cfg.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
As explained in PR #2812 comments, CQL default timeout in JanusGraph
v0.5 was set to 12s. In JanusGraph v0.6, it is set to 10s.
This commit makes the timeout identical in v0.5 and v0.6.
-----
=> Change CQL request-timeout default value to 12s

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLProgrammaticConfigurationLoaderBuilder.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java
CQLConfigOption storage.cql.request-timeout defaults to 10s.
But this default value is not forwarded to CQL DriverConfigLoader.
Fixes #2811
-----
=> CQL default request-timeout should be JanusGraph default

docs/changelog.md, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql-es.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql.yaml, janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml, janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/AbstractGremlinServerIntegrationTest.java, janusgraph-server/src/test/resources/janusgraph-server-integration.yaml
This makes it possible to use comma-separated config values again, e.g., for `storage.hostname`.
The `DefaultGraphManager` from TinkerPop used until now uses the TinkerPop `GraphFactory` which uses `DisabledListDelimiterHandler`. So, comma separated config values are not supported with that `GraphManager`. `JanusGraphFactory` however uses comma-delimited `DefaultListDelimiterHandler`.
So, switching from TinkerPop's `DefaultGraphManager` to `JanusGraphManager` which uses the `JanusGraphFactory` allows to use comma-separated config values again.
Fixes #2822
The tests in `JanusGraphServerTest` all initialize a graph manager instance which is why they cannot be moved to `JanusGraphManager` as that is a singleton implementation which throws when a second instance is requested and the instance …
=> Use JanusGraphManager by default

janusgraph-dist/src/assembly/static/elasticsearch/config/jvm.options
This only mitigates the CVE for ES included the pre-packaged distribution. Users who maintain their own ES (or Solr) installation, need to apply the mitigation there by themselves.
The mitigation is recommended in the summary provided by Elasticsearch:
https://discuss.elastic.co/t/apache-log4j2-remote-code-execution-rce-vulnerability-cve-2021-44228-esa-2021-31/291476
Fixes #2891
-----
=> Add CVE-2021-44228 mitigation for ES

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/CompletedJobFuture.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/EmptyScanJobFuture.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/FailedJobFuture.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/ScanJobFuture.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScanner.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/keycolumnvalue/scan/CompletedJobFutureTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/keycolumnvalue/scan/EmptyScanJobFutureTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/keycolumnvalue/scan/FailedJobFutureTest.java
JanusGraphManagement.IndexJobFuture is used in many places, not limited to
index-related OLAP jobs. The current name is confusing and misleading.
This commit renames this interface and moves it out
of JanusGraphManagement class. This commit also moves its implementations
out of parent classes. No functional change is involved.
This is the first step towards exposing ghost vertex removal functionality to users.
-----
=> Refactor JanusGraphManagement.IndexJobFuture

janusgraph-dist/src/test/expect/spark-graph-computer.expect.vm, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyESAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlESAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/InMemoryAssemblyIT.java, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/JanusGraphAssemblyBaseIT.java
We have SparkGraphComputer tests in AbstractInputFormatIT, but not in distribution tests.
PR #2756 is an example which shows that dependency issues could damage the functionality even
if AbstractInputFormatIT passes. This commit aims to test basic SparkGraphComputer traversal
which leverages local Spark instance in gremlin console.
The new test fails without the fix in #2756.
-----
=> Add distribution test for SparkGraphComputer traversal

janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/EmptyAddedRelations.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/indexcache/EmptyIndexCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/subquerycache/EmptySubqueryCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/vertexcache/EmptyVertexCache.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTxTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/addedrelations/EmptyAddedRelationsTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/indexcache/EmptyIndexCacheTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/subquerycache/EmptySubqueryCacheTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/vertexcache/EmptyVertexCacheTest.java
Fixes JanusGraph#2898. Due to a race condition, vertexCache could be cleared before
it is accessed. To avoid NPEs, we cannot simply assign null to vertexCache
to release the memory.
This commit also surpresses https://lists.lfaidata.foundation/g/janusgraph-users/topic/potential_transaction_issue/85970858
by using a dummy empty vertexCache after transaction release. The root cause
for this bug is unknown, but likely it is due to another race condition.
To keep the behavior consistent with v0.5 and before, this commit surpresses
this issue and writes a warning log whenever the issue happens.
-----
=>  Fix NullPointerException caused by transaction release

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLStoreFeaturesBuilder.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
CQL byteordered partitioner supports both ordered scan and unordered
scan, however, it is annotated as incapable of unordered scans. This
commit fixes this by marking unorderedscan as true for byteordered
partitioner.
-----
=> Add unordered scan annotation for CQL byteordered partitioner [cql-tests]

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStoreTest.java
When a user specifies a `cql.compaction-strategy-class`, JanusGraph enforces that `cql.compaction-strategy-options` be set. This PR makes `cql.compaction-strategy-options` optional.
Unit test `testCompactionStrategyWithoutOptions` fails without this change.
Fixes #2908
-----
=> Allow CQL compaction-strategy-class without options

pom.xml
We're not directly using Jetty but a few dependencies have a dependency on it which is why it's in the pom.xml so we can prevent dependency conflicts. We currently seem to use the same Jetty version as Solr which is also the newest Jetty version used by any of our dependencies right now.
Using a variable for the Jetty version also enables Dependabot to update the version for all three Jetty dependencies together.
My motivation for this PR is simply that I looked into why Dependabot isn't able to update Jetty at the moment (#2870 + #2923). But it looks like we're not using Jetty ourselves so we just have to ensure that we don't get dependency conflicts from our dependencies that depend on Jetty.
Signed-off-by: Florian Hockmann <fh@florian-hockmann.de>
-----
Thank you for contributing to …
=> Ensure Jetty versions are aligned

docs/operations/management.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
This commit allows users to use ManagementSystem to run GhostVertexRemover,
leveraging a local thread pool to purge ghost vertices concurrently. It is
not very suitable for huge graphs which typically require a MapReduce cluster.
-----
=> Add Management API to run ghost vertex remover

janusgraph-backend-testutils/src/main/java/org/janusgraph/olap/OLAPTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraGraphComputer.java
In JanusGraph, graph.traversal().withComputer() traversal utilizes
the built-in FulgoraGraphComputer which uses a thread pool to execute
traversals in parallel. This thread pool, by default, however, only
has one thread. This commit makes the number of concurrency level to
the number of available processors.
I ran the test case locally a few times, and saw evident performance improvement after this fix.
-----
=> Increase GraphComputer concurrency level to num of CPU cores

pom.xml
The original developers of TitanDB made a ton of great work which is the foundation of JanusGraph. 
That said, over some time JanusGraph advanced a lot of things and many things were changed. 
At this point I don't think the original TitanDB developers are responsible for JanusGraph anymore and JanusGraph developers should now be listed as they are now more familiar with the updated code base.
If anyone have any reasonable objections, I'm good to leave the lists untouched. Otherwise I think it makes sense to replace these lists with JanusGraph related information.
Developers tag: https://maven.apache.org/pom.html#Developers
Contributors tag: https://maven.apache.org/pom.html#Contributors
-----
Thank you for contributing to …
=> Replace outdated developers and contributors list with the JanusGraph lists

requirements.txt
Updates mkdocs and fixes the introduces jinja problem which right now fails all documentation builds in GitHub actions: https://github.com/porunov/janusgraph/runs/6027485201?check_suite_focus=true
The fix was explained here:
https://github.com/readthedocs/readthedocs.org/issues/9064
-----
=> Fix mkdocs build is failing due to newer jinja2 releases

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexRecordEntry.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/index/IndexInfoRetriever.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/index/IndexMutationType.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/index/IndexRecords.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/index/IndexUpdate.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/IndexRecordUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
This PR contains refactoring only to prepare for #3022 . After this PR is merged I will rebase #3022 
What this refactoring does:
- Moves all nested classes from `IndexSerializer.java` to normal classes.
- Moves all static methods from `IndexSerializer.java` to a new class `IndexRecordUtil.java`.
- Converts some `IndexSerializer.java` class methods which will be shared in in #3022 into static methods and moves those methods to `IndexRecordUtil.java`.
Related to #1099
-----
=> Refactor index updates to prepare for #3022

docs/advanced-topics/eventual-consistency.md, docs/advanced-topics/stale-index.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/StaleIndexRecordUtil.java
With this change it will be possible to remove stale composite index entries from the graph.
Current limitations:
- Current approach didn't cover Mixed indices. I think it's possible to add this feature in the future PRs but I didn't dig into mixed index direct record changes yet.
- It's more challenging to change Edge composite index record but still possible in some cases. 
- Vertex centric indices were not covered. I guess it's more challenging but I didn't dig into changing entries of vertex centric indices yet. (not sure if that's needed at all)
Related to #1099
-----
=> Add possibility to remove composite index entries

janusgraph-benchmark/src/main/java/org/janusgraph/BenchmarkRunner.java
Currently, StaticArrayEntryListBenchmark causes OOM but
benchmark CI job does not exit. This commit sets up
JMH's shouldFailOnError option so that the CI job will
fail in case of any error. Moreover, this commit excludes
StaticArrayEntryListBenchmark from the standard benchmark
suite because it only tests a low-level API that is rarely
changed and thus does not have much value in CI.
[This example](https://github.com/li-boxuan/janusgraph/runs/6362035397?check_suite_focus=true) shows how shouldFailOnError option leads to CI job failure.
[This example](https://github.com/JanusGraph/janusgraph/runs/6349131794?check_suite_focus=true#step:6:594) shows the status quo: OOM does not lead to CI job failure.
----- …
=> Disable StaticArrayEntryListBenchmark and set FailOnError

docs/configs/janusgraph-cfg.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLProgrammaticConfigurationLoaderBuilder.java
Pull request #2937 fixes a regression issue on Netty
config for Cassandra's backend. This commit continues
the work and updates the configuration reference
documentation.
-----
=> Fix CQL Netty config doc

docs/changelog.md, janusgraph-all/pom.xml, janusgraph-backend-testutils/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-bigtable/pom.xml, janusgraph-core/pom.xml, janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-driver/pom.xml, janusgraph-es/pom.xml, janusgraph-examples/example-berkeleyje/pom.xml, janusgraph-examples/example-common/pom.xml, janusgraph-examples/example-cql/pom.xml, janusgraph-examples/example-hbase/pom.xml, janusgraph-examples/example-remotegraph/pom.xml, janusgraph-examples/example-tinkergraph/pom.xml, janusgraph-examples/pom.xml, janusgraph-grpc/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-hbase/pom.xml, janusgraph-inmemory/pom.xml, janusgraph-lucene/pom.xml, janusgraph-server/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, mkdocs.yml, pom.xml
I've noticed that I accidentally updated the tested TinkerPop version in the changelog of the already released version 0.6.1 as there was no entry for 0.6.2 yet at that time. So I fixed that also in this commit.
-----
=> JanusGraph release 0.6.2 [cql-tests] [tp-tests]

janusgraph-backend-testutils/src/main/java/org/janusgraph/core/AbstractConfiguredGraphFactoryTest.java, janusgraph-core/src/main/java/org/janusgraph/core/ConfiguredGraphFactory.java
Fixes #3054
The added unit test fails with NPE when ran against the master branch.
Changes in ConfiguredGraphFactory make the unit test pass.
-----
=> Guard against NPE when dropping non-existing graphs

docs/operations/configured-graph-factory.md
In configured-graph-factory.md, we didn't document how to
retrieve current configurations for a given graph. This commit
adds a simple example of how to retrieve graph configurations.
-----
=> Document ConfiguredGraphFactory::getConfiguration method

janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java, janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/InMemoryColumnValueStoreTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/database/IndexSerializerTest.java, pom.xml
This updates JUnit, TestContainers, Lombok, and Mockito together as it wasn't possible to only update TestContainers alone since it also depends on JUnit, see PR https://github.com/JanusGraph/janusgraph/pull/2972.
The same applies to Mockito.
These changes were necessary to update Mockito to v4:
Import of `org.mockito.Matchers` needed to be changed to `org.mockito.ArgumentMatchers`. `Matchers` was already only an alias for `ArgumentMatchers` before as described in the release notes:
https://github.com/mockito/mockito/releases/tag/v4.0.0
`any()` is the replacement for `anyObject()`:
https://github.com/mockito/mockito/pull/1931
Calling `property()` on a mocked `StandardVertex` resulted in a `NullPointer` exception, but we can also simply use a `DetachedProperty` as all accesses to that …
=> Update test dependencies

pom.xml
Some PRs to update other dependencies created by Dependabot had dependency convergence errors because these dependencies already use SLF4J 1.7.36. Merging this first should resolve those errors.
-----
=> Bump SLF4J to v1.7.36

docs/changelog.md, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java, pom.xml
related to #3131 
this one bumps to last ES 7 available version.
(you can close the other one if this one fits better.)
-----
Signed-off-by: Lionel Fleury <lionel_fleury@hotmail.com>
=> Bump Elasticsearch to 7.17.5

.github/workflows/ci-benchmark.yml, janusgraph-benchmark/pom.xml, janusgraph-benchmark/src/main/java/org/janusgraph/BenchmarkRunner.java, janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryBenchmark.java
Currently, all our benchmarks are using the in-memory backend. This PR sets up the infrastructure for Cassandra-based benchmarks and adds a multi-query benchmark using the CQL backend.
-----
=> Setup Cassandra benchmark env and add CQLMultiQueryBenchmark

.github/dependabot.yml
This changes the target branch for Dependabot PRs to v0.6 so we can get dependency updates already for the next 0.6 release instead of having to wait for 1.0.0 or manually backport them from master to v0.6. That however of course means that we need to manually merge v0.6 into master after merging a Dependabot PR (like we already do for other PRs that target v0.6).
For major updates, we need to manually change the target branch of Dependabot PRs to master as we probably don't want those on v0.6. Unfortunately, it's not possible to configure Dependabot to treat major updates differently than, e.g., patch level updates, as far as I know.
Also note that Dependabot currently ignores this setting for security updates. It seems to even ignore all settings if this option is used:
> When you use …
=> Dependabot should target v0.6 by default

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
If a mixed index consists of multiple properties, then an element can be
indexed as long as it contains one of these properties. In this case, a
query like `has(keyA, neq(val))` could match an element without `keyA`
as long as it is indexed by this mixed index. This commit fixes this bug
by adding an existence condition, i.e. matching an element only if it
has the given key present.
Fixes #3164
-----
=> Fix mixed index query for neq condition

janusgraph-all/pom.xml, janusgraph-benchmark/pom.xml, janusgraph-benchmark/src/main/java/org/janusgraph/VertexCacheBenchmark.java, janusgraph-core/pom.xml, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/vertexcache/CaffeineVertexCache.java, janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-driver/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-server/pom.xml, janusgraph-solr/pom.xml, pom.xml
Fix the issue #3185
Guava cache has performance bug in 100% read scenario. The solution is to use Caffeine cache which is also suggested by Guava community. See google/guava#2408 for more details. Meanwhile, Caffeine cache beats Guava cache in all scenarios.
The following result is for read scenario.
Benchmark (cacheType) Mode Cnt Score Error Units
VertexCacheBenchmark.run guava avgt 5 0.001 ± 0.001 ms/op
VertexCacheBenchmark.run caffeine avgt 5 ≈ 10⁻⁴ ms/op
-----
=> Replace Guava cache with Caffeine cache for vertex cache

docs/interactions/transactions.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/core/TransactionBuilder.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/BackendTransaction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardTransactionBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/TransactionConfiguration.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/StandardTransactionBuilderTest.java
Not sure if we necessary need this or not but thought this could be helpful for someone who needs to enable / disable db-cache access per transaction.
Another way to control db-cache access would be to control that option in the current running transaction which could allow enabling / disabling db-cache access even per query if necessary:
```
StandardJanusGraphTx tx = (StandardJanusGraphTx) graph.newTransaction();
BackendTransaction backendTransaction = tx.getTxHandle();
backendTransaction.disableCache();
tx.traversal().V().has("name", "hello").next();
backendTransaction.enableCache();
tx.traversal().V().has("name", "world").next();
```
----- …
=> Add clear way to disable db-cache per transaction

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-release.yml, docs/changelog.md, janusgraph-cql/pom.xml, janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java, janusgraph-cql/src/test/resources/cassandra4-byteordered.yaml, janusgraph-cql/src/test/resources/cassandra4-murmur-client-auth.yaml, janusgraph-cql/src/test/resources/cassandra4-murmur-ssl.yaml, janusgraph-cql/src/test/resources/cassandra4-murmur.yaml, janusgraph-dist/README.md, janusgraph-dist/pom.xml, janusgraph-dist/src/assembly/descriptor/common-full.component.xml, janusgraph-dist/src/assembly/static/cassandra/bin/cassandra, janusgraph-dist/src/assembly/static/cassandra/conf/cassandra.yaml, janusgraph-dist/src/assembly/static/cassandra/conf/jvm-server.options, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/JanusGraphAssemblyBaseIT.java, pom.xml
Fixes #3017
* Upgrade Cassandra testing dist version to 4.0.6
* Enable full dist builds on java 11 tests
* Fix log collection during local testing
-----
=> activate cql tests for cassandra 4 [tp-tests]

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/cache/ExpirationKCVSCache.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/cache/KCVSCache.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/cache/NoKCVSCache.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/cache/CacheInvalidationService.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/cache/KCVSCacheInvalidationService.java
This PR adds possibility to manually expire / invalidate db-cache entries.
Related to #3155
-----
=> Add possibility to manual db-cache invalidation

.github/workflows/ci-index-solr.yml, docs/advanced-topics/hadoop.md, docs/changelog.md, janusgraph-all/pom.xml, janusgraph-core/src/main/java/org/janusgraph/core/JanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/ElementUtils.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsTransaction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphStepStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/CloseableIteratorUtils.java, janusgraph-cql/src/test/resources/cql-read.properties, janusgraph-hadoop/pom.xml, janusgraph-hbase/src/test/java/org/janusgraph/hadoop/HBaseInputFormatIT.java, janusgraph-hbase/src/test/resources/hbase-read-snapshot.properties, janusgraph-hbase/src/test/resources/hbase-read.properties, mkdocs.yml, pom.xml
Fixes https://github.com/JanusGraph/janusgraph/issues/3069
-----
=> Update TinkerPop 3.6.1 [tp-tests]

janusgraph-driver/pom.xml, pom.xml
- [Bump commons-text from 1.9 to 1.10.0](https://github.com/JanusGraph/janusgraph/pull/3261)
=> [v0.6] Bump commons-text from 1.9 to 1.10.0

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/IndexAppliesToFunction.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/IndexRecordUtil.java
Related #3155 #3263 #3264
-----
=> Add possibility to invalidate cached indices with indexOnly constraint

pom.xml
- [Bump protobuf-java from 3.21.6 to 3.21.7](https://github.com/JanusGraph/janusgraph/pull/3239)
=> [v0.6] Bump protobuf-java from 3.21.6 to 3.21.7

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-core.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml
- [Bump codecov/codecov-action from 1 to 3](https://github.com/JanusGraph/janusgraph/pull/3284)
=> [v0.6] Bump codecov/codecov-action from 1 to 3

.github/workflows/ci-publish.yml
- [Bump actions/setup-python from 2 to 4](https://github.com/JanusGraph/janusgraph/pull/3282)
=> [v0.6] Bump actions/setup-python from 2 to 4

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml, .github/workflows/ci-release.yml
- [Bump actions/upload-artifact from 2 to 3](https://github.com/JanusGraph/janusgraph/pull/3283)
=> [v0.6] Bump actions/upload-artifact from 2 to 3

pom.xml
- [Bump cassandra-driver.version from 4.14.1 to 4.15.0](https://github.com/JanusGraph/janusgraph/pull/3293)
=> [v0.6] Bump cassandra-driver.version from 4.14.1 to 4.15.0

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml, .github/workflows/ci-java-11.yml, .github/workflows/ci-publish.yml, .github/workflows/ci-release.yml, .github/workflows/lint-proto.yml
- [Bump actions/checkout from 2 to 3](https://github.com/JanusGraph/janusgraph/pull/3286)
=> [v0.6] Bump actions/checkout from 2 to 3

pom.xml
- [Bump nimbus-jose-jwt from 9.8.1 to 9.25.6](https://github.com/JanusGraph/janusgraph/pull/3289)
=> [v0.6] Bump nimbus-jose-jwt from 9.8.1 to 9.25.6

pom.xml
- [Bump jackson2.version from 2.13.4 to 2.14.0](https://github.com/JanusGraph/janusgraph/pull/3287)
=> [v0.6] Bump jackson2.version from 2.13.4 to 2.14.0

docs/advanced-topics/stale-index.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/StaleIndexRecordUtil.java
Continuation of #3022
Related to #1099
-----
=> Add possibility to remove stale mixed index entries for given vertices or edges

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml, .github/workflows/ci-java-11.yml, .github/workflows/ci-publish.yml, .github/workflows/ci-release.yml
- [Bump actions/setup-java from 1 to 3](https://github.com/JanusGraph/janusgraph/pull/3285)
=> [v0.6] Bump actions/setup-java from 1 to 3

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml, .github/workflows/ci-java-11.yml, .github/workflows/ci-release.yml
- [Bump actions/cache from 2 to 3](https://github.com/JanusGraph/janusgraph/pull/3320)
=> [v0.6] Bump actions/cache from 2 to 3

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLStoreFeaturesBuilder.java
AWSKeyspace now supports TTL. So updating the feature builder accordingly
Fixes: https://github.com/JanusGraph/janusgraph/issues/3325
=> CQLStoreFeature updated - AWSKeyspace supports cell level TTL

pom.xml
- [Bump test dependencies (JUnit & Mockito)](https://github.com/JanusGraph/janusgraph/pull/3343)
=> [v0.6] Bump test dependencies (JUnit & Mockito)

pom.xml
- [Bump netty4.version from 4.1.82.Final to 4.1.85.Final](https://github.com/JanusGraph/janusgraph/pull/3310)
=> [v0.6] Bump netty4.version from 4.1.82.Final to 4.1.85.Final

docs/changelog.md, docs/operations/configured-graph-factory.md, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/converter/ReadConfigurationConverter.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/test/java/org/janusgraph/core/es/ElasticsearchConfiguredGraphFactoryTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/converter/ReadConfigurationConverterTest.java
Fix #3338
The elasticsearch backend now uses the graph name by default if no index name is configured. This is relevant for users of `ConfiguredGraphFactory` who use template configurations and want to assign index names automatically upon graph creation.
Co-authored-by: Florian Hockmann <fh@florian-hockmann.de>
=> Use graph name for ES indices if index name is not configured

cassandra-hadoop-util/pom.xml, janusgraph-all/pom.xml, janusgraph-backend-testutils/pom.xml, janusgraph-benchmark/pom.xml, janusgraph-berkeleyje/pom.xml, janusgraph-bigtable/pom.xml, janusgraph-core/pom.xml, janusgraph-cql/pom.xml, janusgraph-dist/pom.xml, janusgraph-doc/pom.xml, janusgraph-driver/pom.xml, janusgraph-es/pom.xml, janusgraph-examples/example-berkeleyje/pom.xml, janusgraph-examples/example-common/pom.xml, janusgraph-examples/example-cql/pom.xml, janusgraph-examples/example-hbase/pom.xml, janusgraph-examples/example-remotegraph/pom.xml, janusgraph-examples/example-tinkergraph/pom.xml, janusgraph-examples/pom.xml, janusgraph-grpc/pom.xml, janusgraph-hadoop/pom.xml, janusgraph-hbase/pom.xml, janusgraph-inmemory/pom.xml, janusgraph-lucene/pom.xml, janusgraph-server/pom.xml, janusgraph-solr/pom.xml, janusgraph-test/pom.xml, mkdocs.yml, pom.xml
Once this PR is merged, I'll continue with the release process and publish the release candidate (or better to say: let our new awesome release process do it). So, if there are issues with the current state on `master` or anything that you think should be included for this release candidate, then please comment here.
I've followed the release docs, but did not change the `changelog.md` because I assumed that we don't want to include release candidates there. People can check out the unfinished entry for 1.0.0 there to get an idea of the changes for 1.0.0-rc1. I think that should be enough for a release candidate.
Discussion thread: https://lists.lfaidata.foundation/g/janusgraph-dev/topic/95312566
=> JanusGraph release candidate 1.0.0-rc1 [cql-tests] [tp-tests]

janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/HadoopRecordReader.java, janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/JanusGraphVertexDeserializer.java
- [Fix the issue [#3344]](https://github.com/JanusGraph/janusgraph/pull/3346)
=> [v0.6] Fix the issue [#3344]

pom.xml
- [Bump commons-net from 3.8.0 to 3.9.0](https://github.com/JanusGraph/janusgraph/pull/3366)
=> [v0.6] Bump commons-net from 3.8.0 to 3.9.0

.github/dependabot.yml
Otherwise we won't get backports for security updates which is bad.
Dependabot only uses the config for security updates if no target-branch is configured:
> target-branch
> [...]
> When you use this option, the settings for this package manager will no longer affect any pull requests raised for security updates.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch
The reason is probably that security updates should always be applied directly to the main branch to ensure that the warnings are only resolved if the updates are applied to the main branch. Since we have already configured `master` as the `target-branch` we can also remove the option as that is also the default. This will hopefully let …
=> Apply Dependabot config also for security updates

docs/storage-backend/cassandra.md
This commit improves the doc for Amazon Keyspace usage, including:
1. Add hint on the potential problem of doing full-scan
2. Include a list of all available partition names
3. Change default partitioner to the current Amazon default one
Closes #3391
-----
=> Amazon Keyspace: Add hint on full-scan

pom.xml
- [Bump error_prone_annotations from 2.14.0 to 2.16](https://github.com/JanusGraph/janusgraph/pull/3347)
=> [v0.6] Bump error_prone_annotations from 2.14.0 to 2.16

RELEASING.md
Summary:
* SKS keyservers are down.
* Better describe how to compile the release notes.
* No PR necessary for version update after release.
* Announce release also on Discord & Twitter.
=> Add release lessons learned from 1.0.0-rc1

pom.xml
- [Bump avro from 1.11.0 to 1.11.1](https://github.com/JanusGraph/janusgraph/pull/3387)
=> [v0.6] Bump avro from 1.11.0 to 1.11.1

pom.xml
- [Bump jackson2.version from 2.14.0 to 2.14.1](https://github.com/JanusGraph/janusgraph/pull/3383)
=> [v0.6] Bump jackson2.version from 2.14.0 to 2.14.1

pom.xml
- [Bump netty4.version from 4.1.85.Final to 4.1.86.Final](https://github.com/JanusGraph/janusgraph/pull/3411)
=> [v0.6] Bump netty4.version from 4.1.85.Final to 4.1.86.Final

pom.xml
- [Bump httpcomponents.httpcore.version from 4.4.15 to 4.4.16](https://github.com/JanusGraph/janusgraph/pull/3410)
=> [v0.6] Bump httpcomponents.httpcore.version from 4.4.15 to 4.4.16

pom.xml
- [Bump httpclient from 4.5.13 to 4.5.14](https://github.com/JanusGraph/janusgraph/pull/3413)
=> [v0.6] Bump httpclient from 4.5.13 to 4.5.14

janusgraph-examples/pom.xml, pom.xml
- [Bump exec-maven-plugin from 3.0.0 to 3.1.0](https://github.com/JanusGraph/janusgraph/pull/3311)
- [Require Maven 3.2.5](https://github.com/JanusGraph/janusgraph/pull/3311)
=> [v0.6] Bump exec-maven-plugin from 3.0.0 to 3.1.0 | Require Maven 3.2.5

pom.xml
- [Bump maven-jar-plugin from 3.2.2 to 3.3.0](https://github.com/JanusGraph/janusgraph/pull/3382)
=> [v0.6] Bump maven-jar-plugin from 3.2.2 to 3.3.0

pom.xml
- [Bump mockito.version from 4.8.1 to 4.10.0](https://github.com/JanusGraph/janusgraph/pull/3424)
=> [v0.6] Bump mockito.version from 4.8.1 to 4.10.0

docs/changelog.md
- [Remove Bigtable as tested compatibility](https://github.com/JanusGraph/janusgraph/pull/3372)
=> [v0.6] Remove Bigtable as tested compatibility

janusgraph-hadoop/pom.xml, janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/JanusGraphVertexDeserializer.java, janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java, janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/formats/util/HadoopRecordReaderTest.java
As the issue https://github.com/JanusGraph/janusgraph/issues/3367 pointed, the edgeID is not unique in a distributed environment. So, the fix here is use a RelationIdentifier similiar ID as edgeID, which will be "relationId-outVertexId-typeId-inVertexId".
The UT here created a JanusGraph with inmemory backed. A KeyIterator is used to full scan the backend KCVStore, and it was passed to HadoopRecordReader to iterate and fetch every vertex, then validating the edgeID format.
=> Fix edgeID inconsistency between OLAP and OLTP queries

pom.xml
- [Bump graalvm-nativeimage.version from 22.2.0 to 22.3.1](https://github.com/JanusGraph/janusgraph/pull/3471)
=> [v0.6] Bump graalvm-nativeimage.version from 22.2.0 to 22.3.1

pom.xml
- [Bump jacoco-maven-plugin from 0.8.7 to 0.8.8](https://github.com/JanusGraph/janusgraph/pull/3482)
=> [v0.6] Bump jacoco-maven-plugin from 0.8.6 to 0.8.8

.github/workflows/ci-backend-cql-dummy.yml, .github/workflows/ci-backend-hbase-dummy.yml, .github/workflows/ci-core-dummy.yml, .github/workflows/ci-index-es-dummy.yml, .github/workflows/ci-index-solr-dummy.yml, .github/workflows/ci-release-dummy.yml
For reference: #3460
We want to use required checks for PRs that prevent merging of PRs if these checks didn't pass. This also makes it possible to use auto-merging.
However, we don't want to build and test PRs that for example only change docs, but such PRs still need to pass the required checks. This forces us to create duplicates of workflows with required checks that are executed only for those PRs (where no code is changed). These duplicate workflows will immediately turn green.
The workflows simply need to have the same name.
This approach is recommended in the GitHub docs:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
I …
=> Let required checks pass for doc PRs

pom.xml
- [Bump netty4.version from 4.1.86.Final to 4.1.87.Final](https://github.com/JanusGraph/janusgraph/pull/3483)
=> [v0.6] Bump netty4.version from 4.1.86.Final to 4.1.87.Final

pom.xml
- [Bump maven-javadoc-plugin from 3.4.0 to 3.4.1](https://github.com/JanusGraph/janusgraph/pull/3497)
=> [v0.6] Bump maven-javadoc-plugin from 3.4.0 to 3.4.1

CONTRIBUTING.md, docs/development.md
Fixes #3404
Unfortunately, adding the backport labels is a manual process right now that we have to do as committers because:
* Labels cannot be added already by a pull request template: https://github.com/community/community/discussions/12815
* Contributors cannot add them themselves as they lack the required permissions to add labels.
We can however look into adding some action that automatically adds labels to all PRs: https://github.com/actions/labeler Then we would only have to remove the label again on PRs that should not be backported (as that should be fewer than the PRs that we want to backport).
-----
=> Document new backporting strategy

docs/changelog.md
I wanted to do this with a CTR commit as the change is minimal, but looks like the branch protection rules currently don't allow that.
=> Fix index name in Changelog CTR

pom.xml
- [Bump gson from 2.9.1 to 2.10.1](https://github.com/JanusGraph/janusgraph/pull/3474)
=> [v0.6] Bump gson from 2.9.1 to 2.10.1

pom.xml
- [Bump junit.version from 5.9.1 to 5.9.2](https://github.com/JanusGraph/janusgraph/pull/3461)
- [Also bump junit-platform to 1.9.2](https://github.com/JanusGraph/janusgraph/pull/3461)
=> [v0.6] Bump junit.version from 5.9.1 to 5.9.2 | Also bump junit-platform to 1.9.2

janusgraph-hbase/docker/Dockerfile
HBase tests are currently failing because the test container could not be started as the specified Curl version isn't available any more in the base image.
I don't see much value in pinning the Curl version as it can easily lead to such problems and I guess Curl is stable enough between versions so that our usage won't break.
-----
=> Fix Curl version not found

pom.xml
- [Bump jackson2.version from 2.14.1 to 2.14.2](https://github.com/JanusGraph/janusgraph/pull/3519)
=> [v0.6] Bump jackson2.version from 2.14.1 to 2.14.2

pom.xml
- [Bump snappy-java from 1.1.8.4 to 1.1.9.1](https://github.com/JanusGraph/janusgraph/pull/3535)
=> [v0.6] Bump snappy-java from 1.1.7.6 to 1.1.9.1

pom.xml
- [Bump maven-dependency-plugin from 3.3.0 to 3.5.0](https://github.com/JanusGraph/janusgraph/pull/3546)
=> [v0.6] Bump maven-dependency-plugin from 3.3.0 to 3.5.0

pom.xml
- [Bump mockito.version from 4.10.0 to 4.11.0](https://github.com/JanusGraph/janusgraph/pull/3561)
=> [v0.6] Bump mockito.version from 4.10.0 to 4.11.0

README.md
I can't find any information about this _Unifi Catalog & Discovery_ at all so I think we should remove it completely.
For Celum and Times Internet, only the links to the respective blog posts don't work any more.
Fixes #3568
-----
=> Remove dead links from README.md

pom.xml
- [Bump jna from 5.12.1 to 5.13.0](https://github.com/JanusGraph/janusgraph/pull/3518)
This actually bumps jna from 5.7.0 to 5.13.0 as `v0.6` was a lot behind here. Let's see whether the builds work for this.
=> [v0.6] Bump jna from 5.7.0 to 5.13.0

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
Applies limit to count in case it exists in the query. Due to count taking place in aggregation logic it's easier to fix it for each index provider.
Fixes #3199
Replacement for #3452
-----
=> Fix Index Providers limited count

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
Applies limit to count in case it exists in the query. Due to count taking place in aggregation logic it's easier to fix it for each index provider.
Fixes #3199
Replaces #3452
-----
=> [v0.6] Fix Index Providers limit on aggregated count

janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/KeySelector.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/LimitAdjustingIterator.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/ResultSetIterator.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MultiKeySliceQuery.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctOrderedIterator.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctUnorderedIterator.java
Without fix could not reindex store with more than Integer.MAX_VALUE entries because `KeySelector.limit` is integer
=> Fix NO_LIMIT handling for key-value stores

docs/getting-started/installation.md
As janusgraph-docker#123 is resolved since 1.0.0-rc2 release, we can remove the ARM machine warning from the installation guide.
-----
=> installation.md: Remove ARM warning

janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
In #3646, @FlorianHockmann reported a bug that caused JanusGraph to reject valid edges because it was unable to confirm the compliance with the connection constraints. In contrast to our initial assumption, the cache was not root of the issue. In fact, the updated cache behavior only uncovered the actual issue.
When checking the connection constraints, we expect to find a schema edge which points to the corresponding schema vertex of the target vertex. As of now this correspondence is checked with `==`. Therefore the check fails if one of both elements has been evicted from the cache and had to be fetched from the backend while the other one remained in the cache. In this case, both representations are equal but not the same anymore. An easy fix (which I also verified in our production …
=> Check connection constraints based on label IDs

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphBaseTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
Some tests have been flaky, probably caused by index management operations exceeding the 10 second limit. By default, a timeout of 60 seconds is enforced, which should be enough for our tests to pass.
Aims to fix #3651 
-----
=> Increase timeout for index management operations in tests

janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/MultiThreadsRowsCollector.java
The check is redundant because it won't be matched after breaking out of the while loop.
https://github.com/JanusGraph/janusgraph/blob/73f7ba238f0b85a07b8f058b68b7db965ba69550/janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/MultiThreadsRowsCollector.java#L125
-----
=> [MINOR] Remove redundant check

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MultiKeySliceQuery.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
Currently, multiKSQ (multi-key slice query) does not show concrete queries fired in profiling results. This sometimes makes debugging difficult.
This work is inspired by a user question on the Discord channel.
-----
=> Profiler: Display multiKSQ detail

pom.xml
- [Bump grpc.version from 1.54.0 to 1.54.1](https://github.com/JanusGraph/janusgraph/pull/3708)
=> [v0.6] Bump grpc.version from 1.54.0 to 1.54.1

pom.xml
- [Bump testcontainers.version from 1.17.6 to 1.18.0](https://github.com/JanusGraph/janusgraph/pull/3715)
=> [v0.6] Bump testcontainers.version from 1.17.6 to 1.18.0

docs/advanced-topics/partitioning.md
This is a recreation of #3719 to hopefully trigger the required workflows which aren't executed if the PR is created by a Workflow.
=> [v0.6] Partitioning: Discourage usage of vertex cut feature

janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/MultiVertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/VertexCentricQueryBuilder.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
- Do not copy vertices into an array when all vertices are non-paritioned
- Do not add and then remove vertices into / from resolved vertices set. Instead add only resolved vertices into a set
- Use optional initial vertices size estimate for multi-query
-----
=> Reduce redundant operations in MultiVertexCentricQueryBuilder

docs/changelog.md, janusgraph-dist/src/assembly/static/bin/gremlin.sh, janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
Log4j isn't available anymore in the lib directory, but Reload4j is. Since Reload4j is a drop-in replacement for Log4j which fixes security issues of Log4j, it makes sense to switch to that. This should provide an elegant, non-breaking way, to avoid the security issues of Log4j.
We only need to do this for `v0.6` as `master` already uses Log4j2.
I verified manually that the expected logs appear again with `bin/janusgraph-server.sh` and that the Log4j config file is used by Reload4j.
Fixes #3681
NOTE: We need to add the changelog entry afterwards also on `master` to get it included in the docs for 1.0.0, too.
-----
=> Use Reload4j as the default logging implementation

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphMultiQueryStep.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphMultiQueryStrategy.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphUnusedMultiQueryRemovalStrategy.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphMultiQueryStrategyTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
=> Remove unused JanusGraphMultiQueryStep when possible [tp-tests][cql-tests]

janusgraph-dist/src/test/expect/remote-console.expect.vm, janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java, pom.xml
When connecting to a remote gremlin server from gremlin console, a NoSuchMethodError is thrown. This commit fixes this bug and adds an integration test to verify correctness.
Fixes #3763
-----
=> Fix snakeyaml NoSuchMethodError in remote console

.github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml, BUILDING.md, README.md, docs/operations/container.md, janusgraph-dist/README.md, janusgraph-dist/docker/.dockerignore, janusgraph-dist/docker/Dockerfile, janusgraph-dist/docker/build-and-push-image.sh, janusgraph-dist/docker/conf/janusgraph-berkeleyje-es-server.properties, janusgraph-dist/docker/conf/janusgraph-berkeleyje-lucene-server.properties, janusgraph-dist/docker/conf/janusgraph-berkeleyje-server.properties, janusgraph-dist/docker/conf/janusgraph-cql-es-server.properties, janusgraph-dist/docker/conf/janusgraph-cql-server.properties, janusgraph-dist/docker/conf/janusgraph-inmemory-server.properties, janusgraph-dist/docker/docker-entrypoint.sh, janusgraph-dist/docker/examples/docker-compose-cql-es.yml, janusgraph-dist/docker/examples/docker-compose-mount.yml, janusgraph-dist/docker/examples/docker-compose.yml, janusgraph-dist/docker/load-initdb.sh, janusgraph-dist/docker/scripts/remote-connect.groovy, janusgraph-dist/docker/test-image.sh, janusgraph-dist/pom.xml, mkdocs.yml
- [Move Janusgraph docker into main repo](https://github.com/JanusGraph/janusgraph/pull/3782)
=> [v0.6] Move Janusgraph docker into main repo

pom.xml
- [Bump testcontainers.version from 1.18.0 to 1.18.3](https://github.com/JanusGraph/janusgraph/pull/3805)
=> [v0.6] Bump testcontainers.version from 1.18.0 to 1.18.3

.github/ISSUE_TEMPLATE/bug-report.md, README.md
Users shouldn't start any more with Gitter and instead better go directly to Discord.
Fixes #3819
-----
=> Remove Gitter from docs

pom.xml
- [Bump junit.version from 5.9.2 to 5.9.3](https://github.com/JanusGraph/janusgraph/pull/3753)
- [Also bump junit-platform to 1.9.3](https://github.com/JanusGraph/janusgraph/pull/3753)
=> [v0.6] Bump junit.version from 5.9.2 to 5.9.3 | Also bump junit-platform to 1.9.3

pom.xml
- [Bump build-helper-maven-plugin from 3.3.0 to 3.4.0](https://github.com/JanusGraph/janusgraph/pull/3834)
=> [v0.6] Bump build-helper-maven-plugin from 3.3.0 to 3.4.0

.github/workflows/backport.yml
We need to use a PAT (personal access token) instead of the default `GITHUB_TOKEN` as that doesn't trigger any workflow runs by design:
> When you use the repository's GITHUB_TOKEN to perform tasks, events
> triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch
> and repository_dispatch, will not create a new workflow run. This
> prevents you from accidentally creating recursive workflow runs.
Source: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
The PAT used here is from our new bot: https://github.com/janusgraph-automations So that should become the author of backporting PRs from now on.
This fixes #3635
----- …
=> Trigger Actions for Backport PRs

pom.xml
- [Bump grpc.version from 1.54.1 to 1.56.0](https://github.com/JanusGraph/janusgraph/pull/3833)
=> [v0.6] Bump grpc.version from 1.54.1 to 1.56.0

pom.xml
- [Bump snappy-java from 1.1.9.1 to 1.1.10.1](https://github.com/JanusGraph/janusgraph/pull/3837)
=> [v0.6] Bump snappy-java from 1.1.9.1 to 1.1.10.1

pom.xml
- [Bump netty-handler from 4.1.93.Final to 4.1.94.Final](https://github.com/JanusGraph/janusgraph/pull/3845)
=> [v0.6] Bump netty-handler from 4.1.93.Final to 4.1.94.Final

pom.xml
I am not sure why we needed these dependencies but it seems like we don't need them any more.
They were added as part of an update to a newer TinkerPop version so maybe we needed those entries simply to avoid dependency convergence errors:
https://github.com/JanusGraph/janusgraph/commit/ae07bbdcde56267109b456788b66272cabe40763
=> Remove unnecessary Guice dependencies [tp-tests]

pom.xml
These dependencies have been added 10 years ago and I can't find any place where they are still used:
https://github.com/JanusGraph/janusgraph/commit/94e75d3fa968c0d2cf890c1883ccbb2f21a391e3
=> Remove 2 unused dependencies

pom.xml
- [Bump error_prone_annotations from 2.18.0 to 2.20.0](https://github.com/JanusGraph/janusgraph/pull/3861)
=> [v0.6] Bump error_prone_annotations from 2.18.0 to 2.20.0

.github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml
- [Update ci-publish Java to 8.0.372+7](https://github.com/JanusGraph/janusgraph/pull/3866)
=> [v0.6] Update ci-publish Java to 8.0.372+7

janusgraph-cql/src/test/java/org/janusgraph/core/cql/CQLConfiguredGraphFactoryTest.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java, janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLIndexManagementIT.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/cache/ExpirationCacheTest.java
=> mark flaky tests

janusgraph-cql/src/test/java/org/janusgraph/core/cql/CQLConfiguredGraphFactoryTest.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java, janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLIndexManagementIT.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/cache/ExpirationCacheTest.java
- [mark flaky tests](https://github.com/JanusGraph/janusgraph/pull/3319)
=> [v0.6] mark flaky tests

janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/ConfigurationManagementGraphServerTest.java
The test has been failing quite often lately, probably simply because it didn't wait long enough for the new graph to be created, at least for slow hardware like we have with GH Actions.
I executed the test at least 10 times with this change in GH Actions and it didn't fail a single time so I guess that this increased timeout is enough.
Fixes #3849
-----
=> Increase wait time for slow ConfigurationManagementGraphServerTest

janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/ConfigurationManagementGraphServerTest.java
- [Increase wait time for slow test run](https://github.com/JanusGraph/janusgraph/pull/3870)
=> [v0.6] Increase wait time for slow test run

pom.xml
- [Bump grpc.version from 1.56.0 to 1.56.1](https://github.com/JanusGraph/janusgraph/pull/3873)
=> [v0.6] Bump grpc.version from 1.56.0 to 1.56.1

pom.xml
- [Bump cassandra-driver.version from 4.16.0 to 4.17.0](https://github.com/JanusGraph/janusgraph/pull/3885)
=> [v0.6] Bump cassandra-driver.version from 4.16.0 to 4.17.0

.github/workflows/ci-backend-cql-dummy.yml, .github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase-dummy.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-backend-scylla-dummy.yml, .github/workflows/ci-backend-scylla.yml, .github/workflows/ci-benchmark.yml, .github/workflows/ci-core-dummy.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es-dummy.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr-dummy.yml, .github/workflows/ci-index-solr.yml, .github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml, .github/workflows/ci-release-dummy.yml, .github/workflows/ci-release.yml, .github/workflows/docker-release-tags.yml, RELEASING.md, janusgraph-dist/docker/Dockerfile, janusgraph-dist/docker/build-and-push-image.sh, janusgraph-dist/pom.xml
=> Re-tag images after release mark ready

.github/workflows/ci-backend-cql-dummy.yml, .github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase-dummy.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-core-dummy.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es-dummy.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr-dummy.yml, .github/workflows/ci-index-solr.yml, .github/workflows/ci-java-11.yml, .github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml, .github/workflows/ci-release-dummy.yml, .github/workflows/ci-release.yml, .github/workflows/docker-release-tags.yml, RELEASING.md, janusgraph-dist/docker/Dockerfile, janusgraph-dist/docker/build-and-push-image.sh, janusgraph-dist/pom.xml
- [Re-tag images after release mark ready](https://github.com/JanusGraph/janusgraph/pull/3842)
=> [v0.6] Re-tag images after release mark ready

docs/index-backend/text-search.md
-----
Prompted from a conversation on [Discord](https://discord.com/channels/981533699378135051/981533699378135054/1137300643300786186). @li-boxuan suggested spinning up a PR for it.
It appears `textContainsPhrase` was not documented for full-text search predicates, but its negation was documented.
=> Document textContainsPhrase

docs/index-backend/text-search.md
- [Document textContainsPhrase (#3907)](https://github.com/JanusGraph/janusgraph/pull/3907)
=> [v0.6] Document textContainsPhrase (#3907)

pom.xml
- [Bump netty4.version from 4.1.94.Final to 4.1.96.Final](https://github.com/JanusGraph/janusgraph/pull/3909)
=> [v0.6] Bump netty4.version from 4.1.94.Final to 4.1.96.Final

pom.xml
- [Bump grpc.version from 1.56.1 to 1.57.1](https://github.com/JanusGraph/janusgraph/pull/3910)
=> [v0.6] Bump grpc.version from 1.56.1 to 1.57.1

.github/dependabot.yml
junit and junit-platform need to be updated together which is why we always had to manually do the update since Dependabot could only create one PR per dependency.
The new grouping feature should solve this as it lets Dependabot create a single PR for both packages:
https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
=> Let Dependabot update JUnit dependencies together

pom.xml
- [Bump grpc.version from 1.57.1 to 1.57.2](https://github.com/JanusGraph/janusgraph/pull/3926)
=> [v0.6] Bump grpc.version from 1.57.1 to 1.57.2

pom.xml
- [Bump org.xerial.snappy:snappy-java from 1.1.10.1 to 1.1.10.3](https://github.com/JanusGraph/janusgraph/pull/3899)
=> [v0.6] Bump org.xerial.snappy:snappy-java from 1.1.10.1 to 1.1.10.3

pom.xml
- [Bump testcontainers.version from 1.18.3 to 1.19.0](https://github.com/JanusGraph/janusgraph/pull/3940)
=> [v0.6] Bump testcontainers.version from 1.18.3 to 1.19.0

pom.xml
- [Bump org.easymock:easymock from 5.1.0 to 5.2.0](https://github.com/JanusGraph/janusgraph/pull/3936)
=> [v0.6] Bump org.easymock:easymock from 5.1.0 to 5.2.0

pom.xml
- [Bump junit.version from 5.9.3 to 5.10.0](https://github.com/JanusGraph/janusgraph/pull/3935)
- [Also bump junit-platform to 1.10.0](https://github.com/JanusGraph/janusgraph/pull/3935)
=> [v0.6] Bump junit.version from 5.9.3 to 5.10.0 | Also bump junit-platform to 1.10.0

janusgraph-dist/pom.xml
- [Bump com.googlecode.maven-download-plugin:download-maven-plugin](https://github.com/JanusGraph/janusgraph/pull/3946)
=> [v0.6] Bump com.googlecode.maven-download-plugin:download-maven-plugin

pom.xml
- [Bump com.google.errorprone:error_prone_annotations from 2.20.0 to 2.21.1](https://github.com/JanusGraph/janusgraph/pull/3954)
=> [v0.6] Bump com.google.errorprone:error_prone_annotations from 2.20.0 to 2.21.1

README.md
The company Linkurious has multiple products, but nowadays only their Ogma library supports JanusGraph (opposed to Linkurious Enterprise). However, our link already pointed to the Ogma docs, so I just changed the text for the link.
=> Rename Linkurious to Ogma

TESTING.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/log/LogTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyOperationCountingTest.java, janusgraph-cql/src/test/java/org/janusgraph/core/cql/CQLConfiguredGraphFactoryTest.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphCacheTest.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLOLAPTest.java, janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLIndexManagementIT.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/BerkeleyElasticsearchTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/CQLSolrTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java, janusgraph-test/src/test/java/org/janusgraph/diskstorage/cache/ExpirationCacheTest.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/vertices/StandardVertexTest.java
- [Mark more tests as flaky](https://github.com/JanusGraph/janusgraph/pull/3961)
=> [v0.6] Mark more tests as flaky

janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphCacheTest.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
Follow-up to #3961 where I forgot to remove this argument from these 2 tests because they are using `ParameterizedRepeatedIfExceptionsTest` instead of `RepeatedIfExceptionsTest`.
This could have been a CTR commit, but unfortunately pushing directly to `master` doesn't work any more due to the required checks we have in place (which we need for the auto-merge feature).
=> Remove minSuccess arguments from remaining tests

janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/BerkeleyElasticsearchTest.java
Looks like the backport went wrong here as it included 3 tests which aren't present at all on `v0.6`. This currently breaks the build on `v0.6`. Not sure why the checks still passed for the backporting PR: #3982
=> Fix backport of: Mark more tests as flaky

.github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml
- [Bump docker/setup-qemu-action from 2 to 3](https://github.com/JanusGraph/janusgraph/pull/3969)
=> [v0.6] Bump docker/setup-qemu-action from 2 to 3

.github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml
- [Bump docker/setup-buildx-action from 2 to 3](https://github.com/JanusGraph/janusgraph/pull/3970)
=> [v0.6] Bump docker/setup-buildx-action from 2 to 3

.github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml
- [Bump docker/login-action from 2 to 3](https://github.com/JanusGraph/janusgraph/pull/3971)
=> [v0.6] Bump docker/login-action from 2 to 3

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctOrderedIterator.java
Sample of code to reproduce issue
```
gremlin> graph=JanusGraphFactory.open("inmemory")
gremlin> graph.traversal()\
.addV().property("a", "1").property("t", "1")\
.addV().property("a", "1").property("t", "1")\
.addV().property("b", "1").property("t", "1")\
.addV().property("b", "1").property("t", "1")\
.iterate()
gremlin> graph.tx().commit();
gremlin> graph.traversal().V().or(has("a", "1"), has("b", "1")).valueMap()
==>[a:[1],t:[1]]
==>[a:[1],t:[1]]
==>[t:[1],b:[1]]
==>[t:[1],b:[1]]
gremlin> graph.traversal().V().or(has("a", "1"), has("b", "1")).order().by("t").valueMap() <--- Issue here
==>[t:[1],b:[1]]
==>[t:[1],b:[1]]
graph.close()
```
-----
to ensure the following steps have been …
=> Fix ordered iterator

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctOrderedIterator.java
- [Merge pull request #3972 from mad/fix-ordered-iterator](https://github.com/JanusGraph/janusgraph/pull/3972)
=> [v0.6] Merge pull request #3972 from mad/fix-ordered-iterator

pom.xml
- [Bump com.google.errorprone:error_prone_annotations from 2.21.1 to 2.22.0](https://github.com/JanusGraph/janusgraph/pull/4009)
=> [v0.6] Bump com.google.errorprone:error_prone_annotations from 2.21.1 to 2.22.0

pom.xml
- [Bump netty4.version from 4.1.97.Final to 4.1.99.Final](https://github.com/JanusGraph/janusgraph/pull/4008)
=> [v0.6] Bump netty4.version from 4.1.97.Final to 4.1.99.Final

pom.xml
- [Bump metrics.version from 4.2.19 to 4.2.20](https://github.com/JanusGraph/janusgraph/pull/4010)
=> [v0.6] Bump metrics.version from 4.2.19 to 4.2.20

pom.xml
- [Bump org.xerial.snappy:snappy-java from 1.1.10.3 to 1.1.10.5](https://github.com/JanusGraph/janusgraph/pull/4006)
=> [v0.6] Bump org.xerial.snappy:snappy-java from 1.1.10.3 to 1.1.10.5

pom.xml
We have a very old version of io.netty:netty dependency in our dependency management that is not being used anyways. This commit removes this dependency management so that dependabot does not report it as security vulnerability.
-----
=> Remove dangling netty dependency management

pom.xml
See CVE-2023-39410 for vulnerablity in avro 1.11.2 and below
-----
=> Bump avro to 1.11.3

pom.xml
This fixes a dependency convergence errors with testcontainers which for some reason only occurs on `v0.6` and prevents backporting the latest testcontainers update (see #4026):
```sh
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.apache.commons:commons-compress:1.23.0 paths to dependency are:
+-org.janusgraph:janusgraph-driver:0.6.4-SNAPSHOT
+-org.testcontainers:testcontainers:1.19.1
+-org.apache.commons:commons-compress:1.23.0 (managed) <-- org.apache.commons:commons-compress:1.24.0
]
```
I'm not sure though why Dependabot hasn't created a PR for this update yet. Its latest log shows that it checked for an update:
```
updater | …
```
=> Update commons-compress to 1.24.0

pom.xml
- [Update commons-compress to 1.24.0](https://github.com/JanusGraph/janusgraph/pull/4027)
=> [v0.6] Update commons-compress to 1.24.0

pom.xml
- [Bump avro to 1.11.3](https://github.com/JanusGraph/janusgraph/pull/4024)
=> [v0.6] Bump avro to 1.11.3

pom.xml
- [Bump testcontainers.version from 1.19.0 to 1.19.1](https://github.com/JanusGraph/janusgraph/pull/4019)
=> [v0.6] Bump testcontainers.version from 1.19.0 to 1.19.1

pom.xml
- [Remove dangling netty dependency management](https://github.com/JanusGraph/janusgraph/pull/4023)
=> [v0.6] Remove dangling netty dependency management

pom.xml
This reverts commit 58294e4adb64a15e38c263ddd5fe319e42866d9b, which causes a few test failure consistently.
-----
=> [v0.6] Revert "Bump metrics.version from 4.2.19 to 4.2.20"

.github/workflows/docker-release-tags.yml
- [fix docker-release-tags action](https://github.com/JanusGraph/janusgraph/pull/4053)
=> [v0.6] fix docker-release-tags action

docs/storage-backend/scylladb.md, janusgraph-dist/pom.xml
The idea in this PR is to add another profile which replaces `janusgraph-cql` with `janusgraph-scylla` when activated. Thus, allowing users to build a distribution release either with DataStax drivers or Scylla drivers. 
Building distribution with CQL libs in this PR is the same as we have in our `release` workflow:
```
mvn clean install -Pjanusgraph-release -DskipTests=true --batch-mode --also-make -Dgpg.skip=true
```
Building distribution with Scylla libs in this PR requires activating additional profile `use-scylla`:
```
mvn clean install -Pjanusgraph-release -Puse-scylla -DskipTests=true --batch-mode --also-make -Dgpg.skip=true
```
**Update**: moved previous discussion message into the [following comment](https://github.com/JanusGraph/janusgraph/issues/3580#issuecomment-1763176986), …
=> Add possibility to build JanusGraph Scylla Release

pom.xml
- [Merge pull request #4063 from JanusGraph/dependabot/maven/org.jacoco-org.jacoco.ant-0.8.11](https://github.com/JanusGraph/janusgraph/pull/4063)
=> [v0.6] Merge pull request #4063 from JanusGraph/dependabot/maven/org.jacoco-org.jacoco.ant-0.8.11

.github/workflows/ci-release.yml
=> add trivy scan to docker

docs/changelog.md
- [Move 0.6 branch to EOL](https://github.com/JanusGraph/janusgraph/pull/4081)
=> [v1.0] Move 0.6 branch to EOL

docs/configs/janusgraph-cfg.md, docs/storage-backend/cassandra.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java
Amazon Keyspace creates keyspace and tables asynchronously. As such, users have to retry graph creation multiple times until they don't see errors like `unconfigured table janusgraph.system_properties`. To address this problem, this commit adds a config option, `storage.cql.init-wait-time`, that does a blocking wait after each table creation request. Changes have been manually tested against Amazon Keyspace.
-----
=> Add INIT_WAIT_TIME CQL option to sleep after table creation

pom.xml
- [Bump protobuf.version from 3.24.3 to 3.25.0](https://github.com/JanusGraph/janusgraph/pull/4088)
=> [v1.0] Bump protobuf.version from 3.24.3 to 3.25.0

.github/workflows/ci-docs.yml
- [revert menu.js and update ci-docs](https://github.com/JanusGraph/janusgraph/pull/4097)
=> [v1.0] revert menu.js and update ci-docs

mkdocs.yml
- [fix structur failure](https://github.com/JanusGraph/janusgraph/pull/4104)
=> [v0.6] fix structur failure

docs.Dockerfile, docs/advanced-topics/hadoop.md, docs/basics/configuration-reference.md, docs/changelog.md, docs/connecting/java.md, docs/getting-started/installation.md, docs/index-backend/search-predicates.md, mkdocs.yml, requirements.txt
This will backport the following commits from `v1.0` to `v0.5`:
- [fix update mkdocs](https://github.com/JanusGraph/janusgraph/pull/4102)
=> [v0.5] fix update mkdocs

docs.Dockerfile, docs/advanced-topics/hadoop.md, docs/basics/configuration-reference.md, docs/changelog.md, docs/getting-started/installation.md, docs/index-backend/search-predicates.md, mkdocs.yml, requirements.txt
This will backport the following commits from `v1.0` to `v0.4`:
- [fix update mkdocs](https://github.com/JanusGraph/janusgraph/pull/4102)
=> [v0.4] fix update mkdocs

docs.Dockerfile, docs/advanced-topics/hadoop.md, docs/basics/configuration-reference.md, docs/changelog.md, docs/getting-started/installation.md, docs/index-backend/search-predicates.md, docs/storage-backend/cassandra.md, mkdocs.yml, requirements.txt
This will backport the following commits from `v1.0` to `v0.3`:
- [fix update mkdocs](https://github.com/JanusGraph/janusgraph/pull/4102)
=> [v0.3] fix update mkdocs

docs.Dockerfile, docs/advanced-topics/hadoop.md, docs/basics/configuration-reference.md, docs/changelog.md, docs/index-backend/search-predicates.md, mkdocs.yml, requirements.txt
This will backport the following commits from `v1.0` to `v0.2`:
- [fix update mkdocs](https://github.com/JanusGraph/janusgraph/pull/4102)
=> [v0.2] fix update mkdocs

.github/workflows/ci-docs.yml
- [fix ci-docs with typo repository-name](https://github.com/JanusGraph/janusgraph/pull/4112)
=> [v1.0] fix ci-docs with typo repository-name

janusgraph-hbase/pom.xml, pom.xml
- [get rid of htrace cves](https://github.com/JanusGraph/janusgraph/pull/4123)
=> [v1.0] get rid of htrace cves

pom.xml
- [Bump metrics.version from 4.2.21 to 4.2.22](https://github.com/JanusGraph/janusgraph/pull/4091)
=> [v1.0] Bump metrics.version from 4.2.21 to 4.2.22

.github/workflows/ci-release.yml
- [Bump aquasecurity/trivy-action from 0.12.0 to 0.14.0](https://github.com/JanusGraph/janusgraph/pull/4095)
=> [v1.0] Bump aquasecurity/trivy-action from 0.12.0 to 0.14.0

docs/configs/janusgraph-cfg.md, docs/storage-backend/cassandra.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java, janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java
- [Add INIT_WAIT_TIME CQL option to sleep after table creation](https://github.com/JanusGraph/janusgraph/pull/4094)
=> [v1.0] Add INIT_WAIT_TIME CQL option to sleep after table creation

.github/dependabot.yml
Looks like Dependabot applies the `pattern` to the `groupId` and not the `artifactId` which explains why the feature didn't work for us so far (which I originally tried in #3918). I tried this out on a small demo project and successfully managed to get Dependabot to create a group update PR:
https://github.com/FlorianHockmann/dependabot-grouped-update-test/pull/6
=> Fix junit group config for Dependabot

cassandra-hadoop-util/pom.xml, janusgraph-hadoop/pom.xml, pom.xml
- [Update Zookeeper to fix cve [cql-tests][tp-tests]](https://github.com/JanusGraph/janusgraph/pull/4130)
=> [v1.0] Update Zookeeper to fix cve [cql-tests][tp-tests]

janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/CompletableFutureUtilTest.java, janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java
=> Fix two unit tests failing locally

janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/CompletableFutureUtilTest.java, janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java
- [Fix two unit tests failing locally](https://github.com/JanusGraph/janusgraph/pull/4140)
=> [v1.0] Fix two unit tests failing locally

.github/workflows/ci-core.yml
Add a new Github action for `janusgraph-core` unit tests
FI `janusgraph-core` unit tests will fail until #4140 is merged.
-----
=> Enable janusgraph-core unit tests in CI

.github/workflows/ci-core.yml
- [Enable janusgraph-core unit tests in CI](https://github.com/JanusGraph/janusgraph/pull/4158)
=> [v1.0] Enable janusgraph-core unit tests in CI

pom.xml
- [Bump jackson2.version from 2.15.3 to 2.16.0](https://github.com/JanusGraph/janusgraph/pull/4136)
=> [v1.0] Bump jackson2.version from 2.15.3 to 2.16.0

pom.xml
- [Bump protobuf.version from 3.25.0 to 3.25.1](https://github.com/JanusGraph/janusgraph/pull/4137)
=> [v1.0] Bump protobuf.version from 3.25.0 to 3.25.1

pom.xml
- [Bump org.checkerframework:checker-qual from 3.39.0 to 3.40.0](https://github.com/JanusGraph/janusgraph/pull/4089)
=> [v1.0] Bump org.checkerframework:checker-qual from 3.39.0 to 3.40.0

pom.xml
- [Bump testcontainers.version from 1.19.1 to 1.19.3](https://github.com/JanusGraph/janusgraph/pull/4132)
=> [v1.0] Bump testcontainers.version from 1.19.1 to 1.19.3

janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyGraphTest.java, pom.xml
- [Bump the junit group with 6 updates](https://github.com/JanusGraph/janusgraph/pull/4135)
- [Add missing JUnit annotations to Berkeley tests](https://github.com/JanusGraph/janusgraph/pull/4135)
=> [v1.0] Bump the junit group with 6 updates | Add missing JUnit annotations to Berkeley tests

.github/workflows/ci-benchmark.yml, .github/workflows/ci-publish-official.yml
- [Bump actions/setup-python from 4 to 5](https://github.com/JanusGraph/janusgraph/pull/4177)
=> [v1.0] Bump actions/setup-python from 4 to 5

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-backend-scylla-dummy.yml, .github/workflows/ci-backend-scylla.yml, .github/workflows/ci-benchmark.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml, .github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml, .github/workflows/ci-release.yml
- [Bump actions/setup-java from 3 to 4](https://github.com/JanusGraph/janusgraph/pull/4157)
=> [v1.0] Bump actions/setup-java from 3 to 4

pom.xml
- [Bump ch.qos.logback:logback-classic from 1.2.11 to 1.2.13](https://github.com/JanusGraph/janusgraph/pull/4173)
=> [v1.0] Bump ch.qos.logback:logback-classic from 1.2.11 to 1.2.13

pom.xml
- [Bump com.nimbusds:nimbus-jose-jwt from 9.37 to 9.37.3](https://github.com/JanusGraph/janusgraph/pull/4179)
=> [v1.0] Bump com.nimbusds:nimbus-jose-jwt from 9.37 to 9.37.3

pom.xml
- [Bump grpc.version from 1.59.0 to 1.59.1](https://github.com/JanusGraph/janusgraph/pull/4148)
=> [v1.0] Bump grpc.version from 1.59.0 to 1.59.1

janusgraph-dist/pom.xml, janusgraph-examples/pom.xml, pom.xml
- [Bump org.codehaus.mojo:exec-maven-plugin from 3.1.0 to 3.1.1](https://github.com/JanusGraph/janusgraph/pull/4151)
=> [v1.0] Bump org.codehaus.mojo:exec-maven-plugin from 3.1.0 to 3.1.1

pom.xml
- [Bump org.codehaus.mojo:build-helper-maven-plugin from 3.4.0 to 3.5.0](https://github.com/JanusGraph/janusgraph/pull/4150)
=> [v1.0] Bump org.codehaus.mojo:build-helper-maven-plugin from 3.4.0 to 3.5.0

.github/workflows/ci-release.yml
- [Bump aquasecurity/trivy-action from 0.14.0 to 0.16.1](https://github.com/JanusGraph/janusgraph/pull/4201)
=> [v1.0] Bump aquasecurity/trivy-action from 0.14.0 to 0.16.1

requirements.txt
- [Bump jinja2 from 3.1.2 to 3.1.3](https://github.com/JanusGraph/janusgraph/pull/4205)
=> [v1.0] Bump jinja2 from 3.1.2 to 3.1.3

pom.xml
- [Bump log4j2.version from 2.20.0 to 2.22.1](https://github.com/JanusGraph/janusgraph/pull/4200)
=> [v1.0] Bump log4j2.version from 2.20.0 to 2.22.1

pom.xml
- [Bump commons-net:commons-net from 3.9.0 to 3.10.0](https://github.com/JanusGraph/janusgraph/pull/4196)
=> [v1.0] Bump commons-net:commons-net from 3.9.0 to 3.10.0

pom.xml
- [Bump commons-io:commons-io from 2.11.0 to 2.15.1](https://github.com/JanusGraph/janusgraph/pull/4195)
=> [v1.0] Bump commons-io:commons-io from 2.11.0 to 2.15.1

docs/index-backend/elasticsearch.md
`index.[X].elasticsearch.index-name` is incorrect and does not result in changing the default index name prefix in Elasticsearch.   The fix makes the option name consistent with [janusgraph-cfg.md](https://github.com/JanusGraph/janusgraph/blob/master/docs/configs/janusgraph-cfg.md). Testing confirmed that `index.[X].index-name` indeed results in the index name prefix change, as expected.
-----
=> fix index-name config option name

docs/index-backend/elasticsearch.md
- [fix index-name config option name](https://github.com/JanusGraph/janusgraph/pull/4225)
=> [v1.0] fix index-name config option name

pom.xml
- [Bump netty4.version from 4.1.101.Final to 4.1.105.Final](https://github.com/JanusGraph/janusgraph/pull/4211)
=> [v1.0] Bump netty4.version from 4.1.101.Final to 4.1.105.Final

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-backend-scylla-dummy.yml, .github/workflows/ci-backend-scylla.yml, .github/workflows/ci-benchmark.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml, .github/workflows/ci-publish-commit.yml, .github/workflows/ci-release.yml
- [Bump actions/cache from 3 to 4](https://github.com/JanusGraph/janusgraph/pull/4212)
=> [v1.0] Bump actions/cache from 3 to 4

pom.xml
- [Bump org.apache.maven.plugins:maven-checkstyle-plugin](https://github.com/JanusGraph/janusgraph/pull/4217)
=> [v1.0] Bump org.apache.maven.plugins:maven-checkstyle-plugin

pom.xml
- [Bump org.apache.commons:commons-lang3 from 3.12.0 to 3.14.0](https://github.com/JanusGraph/janusgraph/pull/4224)
=> [v1.0] Bump org.apache.commons:commons-lang3 from 3.12.0 to 3.14.0

pom.xml
- [Bump metrics.version from 4.2.22 to 4.2.23](https://github.com/JanusGraph/janusgraph/pull/4213)
=> [v1.0] Bump metrics.version from 4.2.22 to 4.2.23

pom.xml
- [Bump org.apache.maven.plugins:maven-compiler-plugin](https://github.com/JanusGraph/janusgraph/pull/4238)
=> [v1.0] Bump org.apache.maven.plugins:maven-compiler-plugin

pom.xml
- [Bump metrics.version from 4.2.23 to 4.2.25](https://github.com/JanusGraph/janusgraph/pull/4236)
=> [v1.0] Bump metrics.version from 4.2.23 to 4.2.25

pom.xml
- [Bump netty4.version from 4.1.105.Final to 4.1.106.Final](https://github.com/JanusGraph/janusgraph/pull/4237)
=> [v1.0] Bump netty4.version from 4.1.105.Final to 4.1.106.Final

.github/workflows/ci-release.yml
- [Bump aquasecurity/trivy-action from 0.16.1 to 0.17.0](https://github.com/JanusGraph/janusgraph/pull/4244)
=> [v1.0] Bump aquasecurity/trivy-action from 0.16.1 to 0.17.0

pom.xml
- [Bump org.apache.maven.plugins:maven-source-plugin from 3.2.1 to 3.3.0](https://github.com/JanusGraph/janusgraph/pull/4239)
=> [v1.0] Bump org.apache.maven.plugins:maven-source-plugin from 3.2.1 to 3.3.0

pom.xml
- [Bump org.apache.maven.plugins:maven-enforcer-plugin from 3.3.0 to 3.4.1](https://github.com/JanusGraph/janusgraph/pull/4243)
=> [v1.0] Bump org.apache.maven.plugins:maven-enforcer-plugin from 3.3.0 to 3.4.1

janusgraph-hbase/docker/Dockerfile
The curl command to download the HBase distribution failed with the following error:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
```
Simply removing the `--no-install-recommends` option when installing curl fixed the issue. So it looks like curl now needs another package to verify the SSL certificate.
Note that whether `http://` or `https://` is used for the URL doesn't make a difference here. I guess archive.apache.org simply redirects to the HTTPS version anyway.
This also updates the debian image used to be more up to date. The previously used Buster image is only maintained by the LTS team right now and support will completely end in June:
https://wiki.debian.org/LTS
=> Fix HBase test Dockerfile

janusgraph-hbase/docker/Dockerfile
- [Fix HBase test Dockerfile](https://github.com/JanusGraph/janusgraph/pull/4268)
=> [v1.0] Fix HBase test Dockerfile

.github/workflows/ci-benchmark.yml
Our regression test CI does not pin python version - it simply uses 3.x. Since python 3.12, setuptools package, which is needed by ccm package we use, is no longer included by default. This fixes the problem by explicitly installing setuptools package.
Fixes #4154
-----
=> Fix missing setuptools package for regression test

.github/workflows/ci-benchmark.yml
- [Fix missing setuptools package for regression test](https://github.com/JanusGraph/janusgraph/pull/4262)
=> [v1.0] Fix missing setuptools package for regression test

pom.xml
- [Bump the junit group with 6 updates](https://github.com/JanusGraph/janusgraph/pull/4253)
=> [v1.0] Bump the junit group with 6 updates

pom.xml
- [Bump grpc.version from 1.61.0 to 1.61.1](https://github.com/JanusGraph/janusgraph/pull/4254)
=> [v1.0] Bump grpc.version from 1.61.0 to 1.61.1

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphCustomIdTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphFeatures.java
g.io(path).read() would fail if the vertex contains custom string-type vertex ID due to a bug in JanusGraphVertexFeatures. This fixes this bug and adds two unit tests for gryo and graphson format.
-----
=> Fix io step read path for string-type vertex ID

janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphPGraphBinarySerializerTest.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleTest.java
The predicates added in #2559 were not supported by `JanusGraphPSerializer` and could thus not be used when connecting via remote to JanusGraph Server.
Fixes #4275
-----
=> Support new text predicates via JanusGraph Server

.github/workflows/ci-release.yml
- [Bump aquasecurity/trivy-action from 0.17.0 to 0.18.0](https://github.com/JanusGraph/janusgraph/pull/4280)
=> [v1.0] Bump aquasecurity/trivy-action from 0.17.0 to 0.18.0

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphCustomIdTest.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphFeatures.java
- [Fix io step read path for string-type vertex ID](https://github.com/JanusGraph/janusgraph/pull/4278)
=> [v1.0] Fix io step read path for string-type vertex ID

pom.xml
- [Bump org.apache.commons:commons-compress from 1.24.0 to 1.26.0](https://github.com/JanusGraph/janusgraph/pull/4267)
=> [v1.0] Bump org.apache.commons:commons-compress from 1.24.0 to 1.26.0

janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphPGraphBinarySerializerTest.java, janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleTest.java
- [Support new text predicates via JanusGraph Server](https://github.com/JanusGraph/janusgraph/pull/4279)
=> [v1.0] Support new text predicates via JanusGraph Server

pom.xml
- [Bump com.google.errorprone:error_prone_annotations from 2.23.0 to 2.25.0](https://github.com/JanusGraph/janusgraph/pull/4265)
=> [v1.0] Bump com.google.errorprone:error_prone_annotations from 2.23.0 to 2.25.0

janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/AddedRelationsContainer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/ConcurrentAddedRelations.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/EmptyAddedRelations.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/SimpleAddedRelations.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/addedrelations/EmptyAddedRelationsTest.java
- [Returning a copied collection to avoid corrupted iterator by multiple threads](https://github.com/JanusGraph/janusgraph/pull/3913)
=> [v1.0] Returning a copied collection to avoid corrupted iterator by multiple threads

pom.xml
- [Bump org.apache.maven.plugins:maven-gpg-plugin from 3.0.1 to 3.1.0](https://github.com/JanusGraph/janusgraph/pull/4288)
=> [v1.0] Bump org.apache.maven.plugins:maven-gpg-plugin from 3.0.1 to 3.1.0

pom.xml
- [Bump org.jctools:jctools-core from 4.0.1 to 4.0.3](https://github.com/JanusGraph/janusgraph/pull/4290)
=> [v1.0] Bump org.jctools:jctools-core from 4.0.1 to 4.0.3

pom.xml
- [Bump org.checkerframework:checker-qual from 3.40.0 to 3.42.0](https://github.com/JanusGraph/janusgraph/pull/4295)
=> [v1.0] Bump org.checkerframework:checker-qual from 3.40.0 to 3.42.0

pom.xml
- [Bump com.fasterxml.woodstox:woodstox-core from 6.5.1 to 6.6.1](https://github.com/JanusGraph/janusgraph/pull/4281)
=> [v1.0] Bump com.fasterxml.woodstox:woodstox-core from 6.5.1 to 6.6.1

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphCustomIdTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphCacheTest.java
We only annotated the test for CQL as flaky, but it's also flaky for other backends. contributor @kptfh already commented on the issue that it's also flaky for the Aerospike backend:
https://github.com/JanusGraph/janusgraph/issues/1498#issuecomment-475640179
and Natalia recently commented on Discord that the test is flaky for in-memory.
So, we should just move the annotation to the test itself to be not specific for any backend. Since the test is copied to `JanusGraphCustomIdTest`, we also need the annotation there (and this is also the place where Natalia hit the flaky test).
Issue: #1498 (not fixed by this)
-----
=> Mark test as flaky for all backends

pom.xml
- [Bump testcontainers.version from 1.19.3 to 1.19.7](https://github.com/JanusGraph/janusgraph/pull/4299)
=> [v1.0] Bump testcontainers.version from 1.19.3 to 1.19.7

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-backend-scylla.yml, .github/workflows/ci-core.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml
- [Bump codecov/codecov-action from 3 to 4](https://github.com/JanusGraph/janusgraph/pull/4240)
- [Add Codecov token (required in v4)](https://github.com/JanusGraph/janusgraph/pull/4240)
=> [v1.0] Bump codecov/codecov-action from 3 to 4 | Add Codecov token (required in v4)

pom.xml
- [Bump commons-codec:commons-codec from 1.15 to 1.16.1](https://github.com/JanusGraph/janusgraph/pull/4296)
=> [v1.0] Bump commons-codec:commons-codec from 1.15 to 1.16.1

pom.xml
- [Bump graalvm-nativeimage.version from 23.1.1 to 23.1.2](https://github.com/JanusGraph/janusgraph/pull/4302)
=> [v1.0] Bump graalvm-nativeimage.version from 23.1.1 to 23.1.2

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphCustomIdTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphCacheTest.java
- [Mark test as flaky for all backends](https://github.com/JanusGraph/janusgraph/pull/4309)
=> [v1.0] Mark test as flaky for all backends

pom.xml
- [Bump netty4.version from 4.1.106.Final to 4.1.107.Final](https://github.com/JanusGraph/janusgraph/pull/4305)
=> [v1.0] Bump netty4.version from 4.1.106.Final to 4.1.107.Final

pom.xml
- [Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.5.0 to 3.6.3](https://github.com/JanusGraph/janusgraph/pull/4306)
=> [v1.0] Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.5.0 to 3.6.3

pom.xml
- [Bump grpc.version from 1.61.1 to 1.62.2](https://github.com/JanusGraph/janusgraph/pull/4319)
=> [v1.0] Bump grpc.version from 1.61.1 to 1.62.2

pom.xml
- [Bump org.json:json from 20231013 to 20240303](https://github.com/JanusGraph/janusgraph/pull/4321)
=> [v1.0] Bump org.json:json from 20231013 to 20240303

pom.xml
- [Bump log4j2.version from 2.22.1 to 2.23.1](https://github.com/JanusGraph/janusgraph/pull/4307)
=> [v1.0] Bump log4j2.version from 2.22.1 to 2.23.1

pom.xml
- [Bump org.apache.maven.plugins:maven-release-plugin from 3.0.0 to 3.0.1](https://github.com/JanusGraph/janusgraph/pull/4330)
=> [v1.0] Bump org.apache.maven.plugins:maven-release-plugin from 3.0.0 to 3.0.1

pom.xml
- [Bump netty4.version from 4.1.107.Final to 4.1.108.Final](https://github.com/JanusGraph/janusgraph/pull/4354)
=> [v1.0] Bump netty4.version from 4.1.107.Final to 4.1.108.Final

.github/workflows/ci-release.yml
- [Bump aquasecurity/trivy-action from 0.18.0 to 0.19.0](https://github.com/JanusGraph/janusgraph/pull/4352)
=> [v1.0] Bump aquasecurity/trivy-action from 0.18.0 to 0.19.0

pom.xml
=> Bump TinkerPop from 3.7.0 to 3.7.1 [tp-tests][cql-tests]

mkdocs.yml, pom.xml
- [Bump TinkerPop from 3.7.0 to 3.7.1 [tp-tests][cql-tests]](https://github.com/JanusGraph/janusgraph/pull/4199)
=> [v1.0] Bump TinkerPop from 3.7.0 to 3.7.1 [tp-tests][cql-tests]

pom.xml
- [Bump graalvm-nativeimage.version from 23.1.2 to 24.0.0](https://github.com/JanusGraph/janusgraph/pull/4357)
=> [v1.0] Bump graalvm-nativeimage.version from 23.1.2 to 24.0.0

.github/workflows/ci-publish-official.yml, pom.xml
- [Add CycloneDX SBOM to release process](https://github.com/JanusGraph/janusgraph/pull/4100)
=> [v1.0] Add CycloneDX SBOM to release process

pom.xml
- [Bump org.apache.hbase.thirdparty:hbase-noop-htrace from 4.1.5 to 4.1.6](https://github.com/JanusGraph/janusgraph/pull/4365)
=> [v1.0] Bump org.apache.hbase.thirdparty:hbase-noop-htrace from 4.1.5 to 4.1.6

pom.xml
- [Bump org.apache.rat:apache-rat-plugin from 0.15 to 0.16.1](https://github.com/JanusGraph/janusgraph/pull/4364)
=> [v1.0] Bump org.apache.rat:apache-rat-plugin from 0.15 to 0.16.1

pom.xml
- [Bump jetty.version from 9.4.53.v20231009 to 9.4.54.v20240208](https://github.com/JanusGraph/janusgraph/pull/4378)
=> [v1.0] Bump jetty.version from 9.4.53.v20231009 to 9.4.54.v20240208

pom.xml
- [Bump grpc.version from 1.62.2 to 1.63.0](https://github.com/JanusGraph/janusgraph/pull/4379)
=> [v1.0] Bump grpc.version from 1.62.2 to 1.63.0

pom.xml
- [Bump commons-io:commons-io from 2.15.1 to 2.16.1](https://github.com/JanusGraph/janusgraph/pull/4382)
=> [v1.0] Bump commons-io:commons-io from 2.15.1 to 2.16.1

pom.xml
- [Bump netty4.version from 4.1.108.Final to 4.1.109.Final](https://github.com/JanusGraph/janusgraph/pull/4388)
=> [v1.0] Bump netty4.version from 4.1.108.Final to 4.1.109.Final

pom.xml
- [Bump jackson2.version from 2.16.1 to 2.17.0](https://github.com/JanusGraph/janusgraph/pull/4331)
=> [v1.0] Bump jackson2.version from 2.16.1 to 2.17.0

janusgraph-dist/pom.xml
- [Bump com.googlecode.maven-download-plugin:download-maven-plugin](https://github.com/JanusGraph/janusgraph/pull/4389)
=> [v1.0] Bump com.googlecode.maven-download-plugin:download-maven-plugin

janusgraph-benchmark/pom.xml
- [Bump org.apache.commons:commons-exec from 1.3 to 1.4.0](https://github.com/JanusGraph/janusgraph/pull/4390)
=> [v1.0] Bump org.apache.commons:commons-exec from 1.3 to 1.4.0

.github/workflows/ci-backend-cql.yml, .github/workflows/ci-backend-hbase.yml, .github/workflows/ci-backend-scylla.yml, .github/workflows/ci-core.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-index-es.yml, .github/workflows/ci-index-solr.yml, .github/workflows/ci-release.yml
- [Bump actions/upload-artifact from 3 to 4](https://github.com/JanusGraph/janusgraph/pull/4184)
=> [v1.0] Bump actions/upload-artifact from 3 to 4

pom.xml
- [Bump org.cyclonedx:cyclonedx-maven-plugin from 2.7.10 to 2.8.0](https://github.com/JanusGraph/janusgraph/pull/4394)
=> [v1.0] Bump org.cyclonedx:cyclonedx-maven-plugin from 2.7.10 to 2.8.0

pom.xml
- [Bump org.apache.maven.plugins:maven-clean-plugin from 3.2.0 to 3.3.2](https://github.com/JanusGraph/janusgraph/pull/4396)
=> [v1.0] Bump org.apache.maven.plugins:maven-clean-plugin from 3.2.0 to 3.3.2

pom.xml
- [Bump org.apache.commons:commons-compress from 1.26.0 to 1.26.1](https://github.com/JanusGraph/janusgraph/pull/4395)
=> [v1.0] Bump org.apache.commons:commons-compress from 1.26.0 to 1.26.1

pom.xml
- [Bump com.google.guava:guava from 32.1.3-jre to 33.1.0-jre](https://github.com/JanusGraph/janusgraph/pull/4329)
=> [v1.0] Bump com.google.guava:guava from 32.1.3-jre to 33.1.0-jre

pom.xml
- [Bump org.ow2.asm:asm from 9.6 to 9.7](https://github.com/JanusGraph/janusgraph/pull/4406)
=> [v1.0] Bump org.ow2.asm:asm from 9.6 to 9.7

docs/configs/janusgraph-cfg.md, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientRetryTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java
Closes #4408
To wait between retries since the code being called into Elasticsearch's client appears to be the synchronous API I opted for just using `Thread.sleep`. If there's a better utility or if a different approach is desired happy change.
Additionally I marked the new configuration options with the `LOCAL` flag. I noticed `retry_on_conflict` went with `MASKABLE` but it didn't seem readily apparent what further obligations would be needed to fulfill the "global" portion of that contract, so just figured it'd be best to start with `LOCAL` and ask about it in the PR.
---
=> Added retry logic if client request returns an error code that is configured for retrying

janusgraph-berkeleyje/src/test/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyVariableLengthKCVSTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreAdapter.java
- [Fix OrderedKeyValueStoreAdapter ArrayIndexOutOfBoundsIssue with test](https://github.com/JanusGraph/janusgraph/pull/4402)
=> [v1.0] Fix OrderedKeyValueStoreAdapter ArrayIndexOutOfBoundsIssue with test

pom.xml
- [Bump org.apache.maven.plugins:maven-gpg-plugin from 3.1.0 to 3.2.4](https://github.com/JanusGraph/janusgraph/pull/4415)
=> [v1.0] Bump org.apache.maven.plugins:maven-gpg-plugin from 3.1.0 to 3.2.4

janusgraph-dist/pom.xml
Often times I see read timeout during janusgraph-distribution building process in GitHub Actions. It seems mostly it happens while downloading ElasticSearch or Cassandra. It usually downloads the packages almost fully (like ~80%) but then for some of the files parts the timeout happens which prevent build from passing.
The was no any default timeout prior to 1.7.0 release of maven-download plugin, but starting from 1.7.0 the default timeout is 3 seconds.
This PR sets `readTimeOut` for ElasticSearch and Cassandra downloads up to 30 minutes. Alternatively, we could remove timeout as it was previously, but knowing that the GitHub Action will timeout in 60 minutes anyways it seems unreasonable to having this timeout more than 30 minutes. I'm also OK setting it to lower values or remove …
=> Increase maven wget timeout for ElasticSearch and Cassandra to 30 minutes

janusgraph-dist/pom.xml
- [Increase maven wget timeout for ElasticSearch and Cassandra to 30 minutes](https://github.com/JanusGraph/janusgraph/pull/4419)
=> [v1.0] Increase maven wget timeout for ElasticSearch and Cassandra to 30 minutes

pom.xml
- [Bump com.google.errorprone:error_prone_annotations from 2.26.1 to 2.27.0](https://github.com/JanusGraph/janusgraph/pull/4423)
=> [v1.0] Bump com.google.errorprone:error_prone_annotations from 2.26.1 to 2.27.0

pom.xml
- [Bump org.javassist:javassist from 3.29.2-GA to 3.30.2-GA](https://github.com/JanusGraph/janusgraph/pull/4429)
=> [v1.0] Bump org.javassist:javassist from 3.29.2-GA to 3.30.2-GA

requirements.txt
- [Bump jinja2 from 3.1.3 to 3.1.4](https://github.com/JanusGraph/janusgraph/pull/4436)
=> [v1.0] Bump jinja2 from 3.1.3 to 3.1.4

pom.xml
- [Bump hbase2.version from 2.5.6-hadoop3 to 2.5.8-hadoop3](https://github.com/JanusGraph/janusgraph/pull/4421)
=> [v1.0] Bump hbase2.version from 2.5.6-hadoop3 to 2.5.8-hadoop3

.github/workflows/ci-release.yml
- [Bump aquasecurity/trivy-action from 0.19.0 to 0.20.0](https://github.com/JanusGraph/janusgraph/pull/4438)
=> [v1.0] Bump aquasecurity/trivy-action from 0.19.0 to 0.20.0

pom.xml
- [Bump org.jacoco:org.jacoco.ant from 0.8.11 to 0.8.12](https://github.com/JanusGraph/janusgraph/pull/4422)
=> [v1.0] Bump org.jacoco:org.jacoco.ant from 0.8.11 to 0.8.12

pom.xml
- [Bump curator.version from 5.5.0 to 5.6.0](https://github.com/JanusGraph/janusgraph/pull/4432)
=> [v1.0] Bump curator.version from 5.5.0 to 5.6.0

janusgraph-dist/docker/docker-entrypoint.sh
I'm having issue with Janusgraph whenever the OS create files or folders in the Janusgraph owned directory. For example, when the system restart unexpectedly and a `lost+found` folder is created. The `lost+found` created by `fsck` have root only access, so `chown` will fail.
I don't think `chown` need to be recursive because files that are created & used by Janusgraph will all be created by the default user (`janusgraph`) anyway.
=> fix: chown fail when OS create folders or files with root only permission

janusgraph-dist/docker/docker-entrypoint.sh
- [fix: chown fail when OS create folders or files with root only permission](https://github.com/JanusGraph/janusgraph/pull/4428)
=> [v1.0] fix: chown fail when OS create folders or files with root only permission

.github/workflows/backport.yml
- [Bump sqren/backport-github-action from 9.3.1 to 9.5.1](https://github.com/JanusGraph/janusgraph/pull/4447)
=> [v1.0] Bump sqren/backport-github-action from 9.3.1 to 9.5.1

pom.xml
- [Bump org.apache.hbase.thirdparty:hbase-noop-htrace from 4.1.6 to 4.1.7](https://github.com/JanusGraph/janusgraph/pull/4442)
=> [v1.0] Bump org.apache.hbase.thirdparty:hbase-noop-htrace from 4.1.6 to 4.1.7

pom.xml
- [Bump testcontainers.version from 1.19.7 to 1.19.8](https://github.com/JanusGraph/janusgraph/pull/4446)
=> [v1.0] Bump testcontainers.version from 1.19.7 to 1.19.8

pom.xml
- [Bump jackson2.version from 2.17.0 to 2.17.1](https://github.com/JanusGraph/janusgraph/pull/4453)
=> [v1.0] Bump jackson2.version from 2.17.0 to 2.17.1

pom.xml
- [Bump org.projectlombok:lombok from 1.18.30 to 1.18.32](https://github.com/JanusGraph/janusgraph/pull/4460)
=> [v1.0] Bump org.projectlombok:lombok from 1.18.30 to 1.18.32

pom.xml
- [Bump commons-codec:commons-codec from 1.16.1 to 1.17.0](https://github.com/JanusGraph/janusgraph/pull/4461)
=> [v1.0] Bump commons-codec:commons-codec from 1.16.1 to 1.17.0

pom.xml
This performs the update from Dependabot's PR #4452 manually as Dependabot for some reason thinks that this update is for some reason no longer possible.
The update includes (copied from Dependabot's description):
Bumps lucene-solr.version from 8.11.2 to 8.11.3.
Updates org.apache.lucene:lucene-core from 8.11.2 to 8.11.3
Updates org.apache.lucene:lucene-analyzers-common from 8.11.2 to 8.11.3
Updates org.apache.lucene:lucene-queryparser from 8.11.2 to 8.11.3
Updates org.apache.lucene:lucene-spatial-extras from 8.11.2 to 8.11.3
Updates org.apache.lucene:lucene-backward-codecs from 8.11.2 to 8.11.3
Updates org.apache.solr:solr-solrj from 8.11.2 to 8.11.3
Updates org.apache.solr:solr-test-framework from 8.11.2 to 8.11.3
=> Bump lucene-solr.version from 8.11.2 to 8.11.3

pom.xml
- [Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.0.0 to 3.2.5](https://github.com/JanusGraph/janusgraph/pull/4468)
=> [v1.0] Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.0.0 to 3.2.5

pom.xml
- [Bump org.apache.maven.plugins:maven-surefire-plugin from 3.0.0 to 3.2.5](https://github.com/JanusGraph/janusgraph/pull/4459)
=> [v1.0] Bump org.apache.maven.plugins:maven-surefire-plugin from 3.0.0 to 3.2.5

pom.xml
- [Bump org.objenesis:objenesis from 3.3 to 3.4](https://github.com/JanusGraph/janusgraph/pull/4469)
=> [v1.0] Bump org.objenesis:objenesis from 3.3 to 3.4

pom.xml
- [Bump lucene-solr.version from 8.11.2 to 8.11.3](https://github.com/JanusGraph/janusgraph/pull/4458)
=> [v1.0] Bump lucene-solr.version from 8.11.2 to 8.11.3

pom.xml
- [---](https://github.com/JanusGraph/janusgraph/pull/4473)
=> [v1.0] ---

pom.xml
- [Bump net.bytebuddy:byte-buddy from 1.14.13 to 1.14.15](https://github.com/JanusGraph/janusgraph/pull/4443)
=> [v1.0] Bump net.bytebuddy:byte-buddy from 1.14.13 to 1.14.15

pom.xml
- [Bump org.checkerframework:checker-qual from 3.42.0 to 3.43.0](https://github.com/JanusGraph/janusgraph/pull/4484)
=> [v1.0] Bump org.checkerframework:checker-qual from 3.42.0 to 3.43.0

.github/workflows/ci-release.yml
- [Bump aquasecurity/trivy-action from 0.20.0 to 0.21.0](https://github.com/JanusGraph/janusgraph/pull/4477)
=> [v1.0] Bump aquasecurity/trivy-action from 0.20.0 to 0.21.0

pom.xml
- [Bump org.apache.maven.plugins:maven-dependency-plugin](https://github.com/JanusGraph/janusgraph/pull/4481)
=> [v1.0] Bump org.apache.maven.plugins:maven-dependency-plugin

pom.xml
- [Bump org.apache.commons:commons-compress from 1.26.1 to 1.26.2](https://github.com/JanusGraph/janusgraph/pull/4497)
=> [v1.0] Bump org.apache.commons:commons-compress from 1.26.1 to 1.26.2

pom.xml
- [Bump org.apache.maven.plugins:maven-deploy-plugin from 3.1.1 to 3.1.2](https://github.com/JanusGraph/janusgraph/pull/4500)
=> [v1.0] Bump org.apache.maven.plugins:maven-deploy-plugin from 3.1.1 to 3.1.2

pom.xml
- [Bump org.ow2.asm:asm-commons from 9.6 to 9.7](https://github.com/JanusGraph/janusgraph/pull/4501)
=> [v1.0] Bump org.ow2.asm:asm-commons from 9.6 to 9.7

pom.xml
- [Bump net.bytebuddy:byte-buddy from 1.14.15 to 1.14.17](https://github.com/JanusGraph/janusgraph/pull/4504)
=> [v1.0] Bump net.bytebuddy:byte-buddy from 1.14.15 to 1.14.17

pom.xml
- [Bump org.apache.maven.plugins:maven-enforcer-plugin from 3.4.1 to 3.5.0](https://github.com/JanusGraph/janusgraph/pull/4507)
=> [v1.0] Bump org.apache.maven.plugins:maven-enforcer-plugin from 3.4.1 to 3.5.0

pom.xml
- [Bump com.google.errorprone:error_prone_annotations from 2.27.0 to 2.28.0](https://github.com/JanusGraph/janusgraph/pull/4496)
=> [v1.0] Bump com.google.errorprone:error_prone_annotations from 2.27.0 to 2.28.0

.github/workflows/ci-release.yml
- [Bump aquasecurity/trivy-action from 0.21.0 to 0.22.0](https://github.com/JanusGraph/janusgraph/pull/4503)
=> [v1.0] Bump aquasecurity/trivy-action from 0.21.0 to 0.22.0

pom.xml
- [Bump org.apache.commons:commons-text from 1.11.0 to 1.12.0](https://github.com/JanusGraph/janusgraph/pull/4513)
=> [v1.0] Bump org.apache.commons:commons-text from 1.11.0 to 1.12.0

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
Hello,
While using JanusGraph, i have sometimes encountered a case where cassandra keyspace fails. When it happens, the real exception is swallowed by a NullPointerException.
This PR fixes this.
Cordially,
=> Fix NPE on keyspace creation

janusgraph-dist/docker/Dockerfile
Hello,
The current docker image for janusgraph is huge. After analysis, it seems that the `chown` instruction [here](https://github.com/JanusGraph/janusgraph/blob/v1.0.0/janusgraph-dist/docker/Dockerfile#L76) has the undesirable side effect of doubling the size of the docker image, because the whole janusgraph installation has changed owner and is then copied into the layer.
This PR makes use of the `--chown` flag of the Dockerfile `COPY` command, and should greatly decrease the size of the Janusgraph docker image.
=> halve docker image size

docs/configs/janusgraph-cfg.md, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchJanusGraphIndexTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientBulkRequestsTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientRetryTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java
Closes #4488
Reused the retry logic from https://github.com/JanusGraph/janusgraph/pull/4409 to also apply to bulk requests if an inner bulk item request failed.
-----
=> Retry bulk request if all errors are configured retry error codes & Split large bulk requests

docs/configs/janusgraph-cfg.md, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientBulkRequestsTest.java
Closes #4529
- Reference the ElasticSearch documentation in the bulk chunker size limit config option
- Cleaning up the population of the ES bulk request path logic
- Submitting bulk request items that are below the configured limit, then throwing for overly large items
-----
=> ES Bulk Retry Follow-up Items

.github/workflows/ci-release.yml
- [Bump aquasecurity/trivy-action from 0.22.0 to 0.23.0](https://github.com/JanusGraph/janusgraph/pull/4517)
=> [v1.0] Bump aquasecurity/trivy-action from 0.22.0 to 0.23.0

pom.xml
- [Bump netty4.version from 4.1.110.Final to 4.1.111.Final](https://github.com/JanusGraph/janusgraph/pull/4520)
=> [v1.0] Bump netty4.version from 4.1.110.Final to 4.1.111.Final

janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
- [Fix NPE on keyspace creation](https://github.com/JanusGraph/janusgraph/pull/4516)
=> [v1.0] Fix NPE on keyspace creation

janusgraph-dist/docker/Dockerfile
- [halve docker image size](https://github.com/JanusGraph/janusgraph/pull/4527)
=> [v1.0] halve docker image size

.github/workflows/ci-release.yml
- [Bump aquasecurity/trivy-action from 0.23.0 to 0.24.0](https://github.com/JanusGraph/janusgraph/pull/4537)
=> [v1.0] Bump aquasecurity/trivy-action from 0.23.0 to 0.24.0

pom.xml
- [Bump jackson2.version from 2.17.1 to 2.17.2](https://github.com/JanusGraph/janusgraph/pull/4544)
=> [v1.0] Bump jackson2.version from 2.17.1 to 2.17.2

pom.xml
- [Bump org.jctools:jctools-core from 4.0.3 to 4.0.5](https://github.com/JanusGraph/janusgraph/pull/4547)
=> [v1.0] Bump org.jctools:jctools-core from 4.0.3 to 4.0.5

pom.xml
- [Bump net.bytebuddy:byte-buddy from 1.14.17 to 1.14.18](https://github.com/JanusGraph/janusgraph/pull/4548)
=> [v1.0] Bump net.bytebuddy:byte-buddy from 1.14.17 to 1.14.18

pom.xml
- [Bump org.apache.maven.plugins:maven-jar-plugin from 3.4.1 to 3.4.2](https://github.com/JanusGraph/janusgraph/pull/4550)
=> [v1.0] Bump org.apache.maven.plugins:maven-jar-plugin from 3.4.1 to 3.4.2

pom.xml
- [Bump commons-cli:commons-cli from 1.6.0 to 1.8.0](https://github.com/JanusGraph/janusgraph/pull/4543)
=> [v1.0] Bump commons-cli:commons-cli from 1.6.0 to 1.8.0

pom.xml
- [Bump com.google.errorprone:error_prone_annotations from 2.28.0 to 2.29.0](https://github.com/JanusGraph/janusgraph/pull/4556)
=> [v1.0] Bump com.google.errorprone:error_prone_annotations from 2.28.0 to 2.29.0

pom.xml
- [Bump org.hdrhistogram:HdrHistogram from 2.1.12 to 2.2.2](https://github.com/JanusGraph/janusgraph/pull/4552)
=> [v1.0] Bump org.hdrhistogram:HdrHistogram from 2.1.12 to 2.2.2

pom.xml
- [Bump org.apache.maven.plugins:maven-source-plugin from 3.3.0 to 3.3.1](https://github.com/JanusGraph/janusgraph/pull/4560)
=> [v1.0] Bump org.apache.maven.plugins:maven-source-plugin from 3.3.0 to 3.3.1

pom.xml
- [Bump grpc.version from 1.64.0 to 1.65.1](https://github.com/JanusGraph/janusgraph/pull/4559)
=> [v1.0] Bump grpc.version from 1.64.0 to 1.65.1

pom.xml
- [Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.2.5 to 3.3.1](https://github.com/JanusGraph/janusgraph/pull/4565)
=> [v1.0] Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.2.5 to 3.3.1

pom.xml
- [Bump org.projectlombok:lombok from 1.18.32 to 1.18.34](https://github.com/JanusGraph/janusgraph/pull/4564)
=> [v1.0] Bump org.projectlombok:lombok from 1.18.32 to 1.18.34

pom.xml
- [Bump org.easymock:easymock from 5.2.0 to 5.3.0](https://github.com/JanusGraph/janusgraph/pull/4569)
=> [v1.0] Bump org.easymock:easymock from 5.2.0 to 5.3.0

pom.xml
- [Bump netty4.version from 4.1.111.Final to 4.1.112.Final](https://github.com/JanusGraph/janusgraph/pull/4568)
=> [v1.0] Bump netty4.version from 4.1.111.Final to 4.1.112.Final

pom.xml
Cobertura can be used to calculate test coverage, but I don't think that we are using it any more. I at least cannot find any usage of this plugin.
Docs can be found here:
https://www.mojohaus.org/cobertura-maven-plugin/
Build Helper Maven Plugin provides several build utilities, but I also can't find any place where we actually use the plugin. Docs: https://www.mojohaus.org/build-helper-maven-plugin/
I just noticed these plugins as Dependabot created a PR to update the build helper plugin: #4554.
~_Note: I'm opening this in draft state because I want to verify first that coverage data is still included in the PR and not broken by removing Cobertura._~
=> Remove 2 unused Maven plugins

pom.xml
- [Bump commons-codec:commons-codec from 1.17.0 to 1.17.1](https://github.com/JanusGraph/janusgraph/pull/4573)
=> [v1.0] Bump commons-codec:commons-codec from 1.17.0 to 1.17.1

pom.xml
- [Bump curator.version from 5.6.0 to 5.7.0](https://github.com/JanusGraph/janusgraph/pull/4574)
=> [v1.0] Bump curator.version from 5.6.0 to 5.7.0

pom.xml
- [Remove 2 unused Maven plugins](https://github.com/JanusGraph/janusgraph/pull/4557)
=> [v1.0] Remove 2 unused Maven plugins

pom.xml
- [Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.6.3 to 3.8.0](https://github.com/JanusGraph/janusgraph/pull/4579)
=> [v1.0] Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.6.3 to 3.8.0

pom.xml
- [Bump graalvm-nativeimage.version from 24.0.0 to 24.0.2](https://github.com/JanusGraph/janusgraph/pull/4580)
=> [v1.0] Bump graalvm-nativeimage.version from 24.0.0 to 24.0.2

pom.xml
- [Bump com.google.guava:guava from 33.1.0-jre to 33.2.1-jre](https://github.com/JanusGraph/janusgraph/pull/4581)
=> [v1.0] Bump com.google.guava:guava from 33.1.0-jre to 33.2.1-jre

pom.xml
- [Bump metrics.version from 4.2.25 to 4.2.26](https://github.com/JanusGraph/janusgraph/pull/4592)
=> [v1.0] Bump metrics.version from 4.2.25 to 4.2.26

pom.xml
- [Bump org.apache.maven.plugins:maven-surefire-plugin from 3.2.5 to 3.3.1](https://github.com/JanusGraph/janusgraph/pull/4591)
=> [v1.0] Bump org.apache.maven.plugins:maven-surefire-plugin from 3.2.5 to 3.3.1

pom.xml
- [Bump org.sonatype.plugins:nexus-staging-maven-plugin](https://github.com/JanusGraph/janusgraph/pull/4590)
=> [v1.0] Bump org.sonatype.plugins:nexus-staging-maven-plugin

pom.xml
- [Bump com.google.code.gson:gson from 2.10.1 to 2.11.0](https://github.com/JanusGraph/janusgraph/pull/4603)
=> [v1.0] Bump com.google.code.gson:gson from 2.10.1 to 2.11.0

pom.xml
- [Bump net.java.dev.jna:jna from 5.13.0 to 5.14.0](https://github.com/JanusGraph/janusgraph/pull/4602)
=> [v1.0] Bump net.java.dev.jna:jna from 5.13.0 to 5.14.0

pom.xml
- [Bump protobuf.version from 3.25.3 to 3.25.4](https://github.com/JanusGraph/janusgraph/pull/4608)
=> [v1.0] Bump protobuf.version from 3.25.3 to 3.25.4

pom.xml
- [Bump org.apache.maven.plugins:maven-release-plugin from 3.0.1 to 3.1.1](https://github.com/JanusGraph/janusgraph/pull/4611)
=> [v1.0] Bump org.apache.maven.plugins:maven-release-plugin from 3.0.1 to 3.1.1

pom.xml
- [Bump org.checkerframework:checker-qual from 3.43.0 to 3.45.0](https://github.com/JanusGraph/janusgraph/pull/4609)
=> [v1.0] Bump org.checkerframework:checker-qual from 3.43.0 to 3.45.0

pom.xml
- [Bump scylla-driver.version from 4.17.0.1 to 4.18.0.1](https://github.com/JanusGraph/janusgraph/pull/4610)
=> [v1.0] Bump scylla-driver.version from 4.17.0.1 to 4.18.0.1

pom.xml
- [Bump org.apache.commons:commons-lang3 from 3.14.0 to 3.15.0](https://github.com/JanusGraph/janusgraph/pull/4615)
=> [v1.0] Bump org.apache.commons:commons-lang3 from 3.14.0 to 3.15.0

pom.xml
- [Bump com.fasterxml.woodstox:woodstox-core from 6.6.2 to 7.0.0](https://github.com/JanusGraph/janusgraph/pull/4614)
=> [v1.0] Bump com.fasterxml.woodstox:woodstox-core from 6.6.2 to 7.0.0

pom.xml
- [Bump grpc.version from 1.65.1 to 1.66.0](https://github.com/JanusGraph/janusgraph/pull/4626)
=> [v1.0] Bump grpc.version from 1.65.1 to 1.66.0

pom.xml
- [Bump testcontainers.version from 1.20.0 to 1.20.1](https://github.com/JanusGraph/janusgraph/pull/4620)
=> [v1.0] Bump testcontainers.version from 1.20.0 to 1.20.1

pom.xml
- [Bump commons-net:commons-net from 3.10.0 to 3.11.1](https://github.com/JanusGraph/janusgraph/pull/4621)
=> [v1.0] Bump commons-net:commons-net from 3.10.0 to 3.11.1

docs/changelog.md
- [Document changes for inmemory backend with Janusgraph 0.5.0 upgrade](https://github.com/JanusGraph/janusgraph/pull/4630)
=> [v1.0] Document changes for inmemory backend with Janusgraph 0.5.0 upgrade

pom.xml
- [Bump org.checkerframework:checker-qual from 3.45.0 to 3.46.0](https://github.com/JanusGraph/janusgraph/pull/4636)
=> [v1.0] Bump org.checkerframework:checker-qual from 3.45.0 to 3.46.0

pom.xml
- [Bump commons-cli:commons-cli from 1.8.0 to 1.9.0](https://github.com/JanusGraph/janusgraph/pull/4634)
=> [v1.0] Bump commons-cli:commons-cli from 1.8.0 to 1.9.0

pom.xml
- [Bump commons-logging:commons-logging from 1.3.1 to 1.3.3](https://github.com/JanusGraph/janusgraph/pull/4633)
=> [v1.0] Bump commons-logging:commons-logging from 1.3.1 to 1.3.3

pom.xml
- [Bump org.apache.commons:commons-lang3 from 3.15.0 to 3.16.0](https://github.com/JanusGraph/janusgraph/pull/4643)
=> [v1.0] Bump org.apache.commons:commons-lang3 from 3.15.0 to 3.16.0

janusgraph-solr/pom.xml
- [Bump org.apache.kerby:kerb-simplekdc from 2.0.3 to 2.1.0](https://github.com/JanusGraph/janusgraph/pull/4644)
=> [v1.0] Bump org.apache.kerby:kerb-simplekdc from 2.0.3 to 2.1.0

pom.xml
- [Bump metrics.version from 4.2.26 to 4.2.27](https://github.com/JanusGraph/janusgraph/pull/4642)
=> [v1.0] Bump metrics.version from 4.2.26 to 4.2.27

pom.xml
- [Bump org.cyclonedx:cyclonedx-maven-plugin from 2.8.0 to 2.8.1](https://github.com/JanusGraph/janusgraph/pull/4648)
=> [v1.0] Bump org.cyclonedx:cyclonedx-maven-plugin from 2.8.0 to 2.8.1

pom.xml
- [Bump commons-logging:commons-logging from 1.3.3 to 1.3.4](https://github.com/JanusGraph/janusgraph/pull/4649)
=> [v1.0] Bump commons-logging:commons-logging from 1.3.3 to 1.3.4

pom.xml
- [Bump com.google.errorprone:error_prone_annotations from 2.29.2 to 2.30.0](https://github.com/JanusGraph/janusgraph/pull/4652)
=> [v1.0] Bump com.google.errorprone:error_prone_annotations from 2.29.2 to 2.30.0

pom.xml
- [Bump org.apache.maven.plugins:maven-deploy-plugin from 3.1.2 to 3.1.3](https://github.com/JanusGraph/janusgraph/pull/4655)
=> [v1.0] Bump org.apache.maven.plugins:maven-deploy-plugin from 3.1.2 to 3.1.3

pom.xml
- [Bump net.bytebuddy:byte-buddy from 1.14.18 to 1.15.1](https://github.com/JanusGraph/janusgraph/pull/4666)
=> [v1.0] Bump net.bytebuddy:byte-buddy from 1.14.18 to 1.15.1

pom.xml
- [Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.8.0 to 3.10.0](https://github.com/JanusGraph/janusgraph/pull/4673)
=> [v1.0] Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.8.0 to 3.10.0

pom.xml
- [Bump com.google.guava:guava from 33.2.1-jre to 33.3.0-jre](https://github.com/JanusGraph/janusgraph/pull/4670)
=> [v1.0] Bump com.google.guava:guava from 33.2.1-jre to 33.3.0-jre

pom.xml
- [Bump org.easymock:easymock from 5.3.0 to 5.4.0](https://github.com/JanusGraph/janusgraph/pull/4677)
=> [v1.0] Bump org.easymock:easymock from 5.3.0 to 5.4.0

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ModifierType.java, janusgraph-core/src/test/java/org/janusgraph/graphdb/TestModifierType.java
Fix the issue https://github.com/JanusGraph/janusgraph/issues/4658:
ModifierType and TypeDefinitionCategory has circular initialization dependency, as a result, if we access ModifierType before TypeDefinitionCategory, it will cause java.lang.ExceptionInInitializerError problem.
A UT is included. No document change.
-----
=> Fix the circular initialization dependency #4658

janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ModifierType.java, janusgraph-core/src/test/java/org/janusgraph/graphdb/TestModifierType.java
Backporting #4664 to v1.0 branch
=> Backport #4664 to v1.0

docs/storage-backend/scylladb.md, janusgraph-dist/pom.xml
Currently on a system with disabled docker if you try to build a project with the following command:
```
mvn clean install -Pjanusgraph-release -DskipTests=true --batch-mode --also-make -Dgpg.skip=true
```
You will get an exception:
```
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
In some situations users don't need to build the docker image during JanusGraph build process. Thus, `-Pskip-docker` argument is added to allow skipping Docker image build.
I.e. the following command is passing normally and JanusGraph artifacts are built as expected:
```
mvn clean install -Pjanusgraph-release -Pskip-docker -DskipTests=true --batch-mode --also-make -Dgpg.skip=true
```
-----
In order to …
=> Allow skipping Docker build from main build process

docs/changelog.md, docs/schema/index-management/index-performance.md, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java, janusgraph-benchmark/src/main/java/org/janusgraph/CQLCompositeIndexInlinePropBenchmark.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphIndex.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/cache/CacheInvalidationService.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/index/IndexUpdate.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/index/IndexUpdateContainer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/JanusGraphIndexWrapper.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/IndexRecordUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/StaleIndexRecordUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/InternalRelationType.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/VertexWithInlineProps.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/CompositeIndexType.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/TypeDefinitionCategory.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/indextype/CompositeIndexTypeWrapper.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/indextype/IndexReferenceType.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/system/BaseKey.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/system/EmptyRelationType.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/RelationTypeVertex.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/util/SubqueryIterator.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/CacheVertex.java, janusgraph-test/src/test/java/org/janusgraph/graphdb/database/IndexSerializerTest.java
Inlining vertex properties into a search index structure (CompositeIndex) can offer significant performance and efficiency benefits.
1. **Performance Improvements**
Faster Querying: Inlining vertex properties directly within the index allows the search engine to retrieve all relevant data from the index itself. This means queries don’t need to make additional calls to data stores to fetch full vertex information, significantly reducing lookup time.
2. **Data Locality**
In distributed storages, having inlined properties ensures that more complete data exists within individual partitions or shards. This reduces cross-node network calls and improves the overall query performance by ensuring data is more local to the request being processed.
3. **Cost of Indexing vs. Storage Trade-off**
While …
=> Inlining vertex properties into a CompositeIndex structure

docs/changelog.md, docs/configs/janusgraph-cfg.md, docs/storage-backend/bdb.md, janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java, janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyGraphTest.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/ConfigOption.java, janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreManagerAdapter.java, janusgraph-core/src/main/java/org/janusgraph/util/system/ConfigurationUtil.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchSetup.java
This PR exposes all BerkeleyJE configuration options to users, so that they have better control over internal settings (this functionality was requested in #1623).
Overall there is a good discussion in #1623 about deadlocks and timeouts that BerkeleyJE storage backend has. Thus, I also skimmed through the comments as well as my past tests with `BerkeleyJE` and added potential configurations suggestions based on user's feedback in documentation that may help users to get started. That said, this configuration may not fix all the issues and most likely have it's own flaws.
-----
=> Expose BerkeleyJE configs [tp-tests]

README.md
=> Add link to the janusgraph-visualizer

docs/configs/janusgraph-cfg.md, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java, janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
Closes discussion #4688 
-----
=> Replace deprecated compression options in cql

.github/workflows/ci-release.yml
Currently trivy scan jobs started to failing in all commits (see [here](https://github.com/JanusGraph/janusgraph/actions/runs/11663626552/job/32532820274) for example). 
This is due to rate limits and the root issue is the following:  https://github.com/aquasecurity/trivy-action/issues/389
Thus, this PR makes trivy scan job tentative for now.
-----
=> Make trivy scan tentative to overcome rate limits

.github/workflows/ci-release.yml
- [Make trivy scan tentative to overcome rate limits](https://github.com/JanusGraph/janusgraph/pull/4717)
=> [v1.0] Make trivy scan tentative to overcome rate limits

pom.xml
- [Bump com.google.protobuf:protobuf-java from 3.25.4 to 3.25.5](https://github.com/JanusGraph/janusgraph/pull/4681)
=> [v1.0] Bump com.google.protobuf:protobuf-java from 3.25.4 to 3.25.5

pom.xml
This will backport the following commits from `master` to `v1.1`:
- [Bump io.netty:netty-common from 4.1.112.Final to 4.1.115.Final](https://github.com/JanusGraph/janusgraph/pull/4725)
=> [v1.1] Bump io.netty:netty-common from 4.1.112.Final to 4.1.115.Final

docs/basics/connecting/python.md
I have noticed that in the latest JanusGraph documentation the JanusGraph-Python package is not mentioned on the https://docs.janusgraph.org/basics/connecting/python/ page. With this PR, I have added the missing reference following the format used for JanusGraph.Net.
-----
=> added reference to JanusGraph-Python package

janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java, janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexTest.java, janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/StandardTokenizerTest.java
-----
Fixes https://github.com/JanusGraph/janusgraph/issues/4165
Closes https://github.com/JanusGraph/janusgraph/issues/4164
=> Solr textContainsPhrase & Solr Client Tokenizer Alignment

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphCustomIdTest.java, janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/IndexRecordUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
This PR introduces new schema management APIs to JanusGraph to enhance debugging capabilities, especially for issues where information is derived from logs. These APIs provide utilities to map between vertex IDs and their hex string representation, retrieve index key hex strings, and obtain index information using hex strings.
The added methods are:
`getVertexId(String hexString)`
```
Purpose: Converts a hex string back to its corresponding vertex ID.
Parameters:
hexString: A hexadecimal string representing the vertex ID.
Returns:
Vertex ID as an object.
```
`getIndexKey(String indexName, Map<String, Object> fieldValues)`
```
Purpose: Generates a hex string representing a schema index's index key bytes for given index name and vertex properties values.
Parameters:
indexName: The name of …
```
=> Schema Management APIs for Enhanced Debugging in JanusGraph

janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/CompositeIndexInfo.java, janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/IndexRecordUtil.java, janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
Enhancements for this API, introduced in the [PR](https://github.com/JanusGraph/janusgraph/pull/4754)
to return not only index structure but also corresponding field values:
```
getIndexInfo(String hexString)
Purpose: Decodes a hex string to retrieve composite index information.
Parameters:
hexString: A hexadecimal string representing the index key.
Returns:
CompositeIndexType: The composite index details.
```
=> Returning Composite index structure and field values for hex string

AUTHORS.txt, CONTRIBUTORS.txt
We haven't updated AUTHORS and CONTRIBUTORS for 7 years. AUTHORS is generated by `git log --all --format='%aN <%cE>' | sort -u --ignore-case` with manual cleanup. CONTRIBUTORS is updated per my best knowledge.
-----
=> Update AUTHORS and CONTRIBUTORS

README.md
=> README.md: Add DOI and citation guide

janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/log/LogTest.java
Improves the readability of the test. Replaces manual exception handling with the testing framework's built-in features (e.g., assertThrows), improving readability, maintainability, and debugging efficiency.
-----
=> Improve readability of testReadMarkerCompatibility

mkdocs.yml
=> Update copyright year to 2025 in docs CTR

pom.xml
This will backport the following commits from `master` to `v1.1`:
- [Bump org.eclipse.jetty:jetty-server](https://github.com/JanusGraph/janusgraph/pull/4789)
=> [v1.1] Bump org.eclipse.jetty:jetty-server

.github/workflows/ci-release.yml
This will backport the following commits from `master` to `v1.1`:
- [Bump aquasecurity/trivy-action from 0.28.0 to 0.31.0](https://github.com/JanusGraph/janusgraph/pull/4796)
=> [v1.1] Bump aquasecurity/trivy-action from 0.28.0 to 0.31.0

janusgraph-dist/docker/Dockerfile, janusgraph-hbase/docker/Dockerfile
This PR fixes HBase test failures caused by Docker build issues where the `apt-get update` command was failing with exit code 100.
The HBase tests were failing with the following error:
```
org.testcontainers.containers.ContainerFetchException: Can't get Docker image
...
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: The command '/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y socat' returned a non-zero code: 100
```
The issue was caused by using outdated base images:
- `openjdk:8-jre-buster` in the HBase Dockerfile
- `debian:buster-slim` in the dist Dockerfile
Debian Buster reached end-of-life and its repositories are no longer accessible via standard URLs, causing `apt-get update` to fail.
- Updated HBase …
=> Fix HBase Docker build failures due to outdated buster repositories

.github/workflows/ci-index-es-dummy.yml, .github/workflows/ci-index-es.yml, docs/changelog.md, janusgraph-es/pom.xml, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticMajorVersion.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/ES9Compat.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/ESCompatUtils.java, janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchIndexTest.java, janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java, pom.xml
=> Add ElasticSearch 9 support

.github/workflows/ci-publish-commit.yml, .github/workflows/ci-publish-official.yml, RELEASING.md, pom.xml
=> Fix maven central publishing CTR
